In [2]:
# ============================================================
# AI MEETING INTELLIGENCE SYSTEM
# COMPREHENSIVE EXPERIMENTAL EVALUATION
# ============================================================

PROJECT_NAME = "AI Meeting Intelligence System"
EXPERIMENT_VERSION = "2.0"

print("=" * 70)
print(PROJECT_NAME)
print("Comprehensive Experimental Evaluation")
print("Version:", EXPERIMENT_VERSION)
print("=" * 70)

======================================================================
AI Meeting Intelligence System
Comprehensive Experimental Evaluation
Version: 2.0
======================================================================

In [3]:
import platform
import sys
import torch

print("Python version:", sys.version.split()[0])
print("Operating system:", platform.system())

if torch.cuda.is_available():
    print("✅ CUDA GPU available")
    print("GPU:", torch.cuda.get_device_name(0))
    print("CUDA version:", torch.version.cuda)
else:
    print("⚠️ CUDA GPU not available")
    print("Whisper will run on CPU.")

Python version: 3.13.15
Operating system: Linux
✅ CUDA GPU available
GPU: Tesla T4
CUDA version: 12.8

In [4]:
!pip install -q --upgrade \
    google-genai \
    openai-whisper \
    pydantic \
    pandas \
    numpy \
    scipy \
    scikit-learn \
    statsmodels \
    rapidfuzz \
    jiwer \
    krippendorff \
    openpyxl \
    python-docx \
    reportlab \
    matplotlib \
    tqdm \
    psutil

print("✅ All required packages installed.")

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.4/62.4 kB 5.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.3/57.3 kB 6.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.3/35.3 MB 33.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 95.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 253.0/253.0 kB 23.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 83.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.2/80.2 kB 8.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.6/155.6 kB 15.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.9/118.9 kB 8.2 MB/s eta 0:00:00
✅ All required packages installed.

In [5]:
import os
import json
import time
import random
import statistics
import platform
import sys
import re
import traceback

from pathlib import Path
from datetime import datetime

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
import whisper

from tqdm.auto import tqdm

from jiwer import wer, cer

from sklearn.metrics import (
    precision_score,
    recall_score,
    f1_score,
    accuracy_score
)

from scipy import stats

from pydantic import BaseModel, Field
from typing import List, Optional, Literal

from google import genai
from google.genai import types

print("✅ All libraries imported successfully.")

AttributeError: 'numpy.ufunc' object has no attribute '__module__' and no __dict__ for setting new attributes

In [6]:
!pip install -q --upgrade --force-reinstall \
    numpy==2.5.0 \
    scipy==1.16.1 \
    scikit-learn==1.9.0 \
    pandas \
    matplotlib

print("✅ Scientific Python packages reinstalled.")
print("⚠️ Now restart the Colab runtime before running any other cells.")

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 5.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.6/123.6 kB 12.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 97.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.2/35.2 MB 24.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 362.9/362.9 kB 33.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 115.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 306.1/306.1 kB 31.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 84.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 467.4/467.4 kB 39.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.0/130.0 kB 14.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 105.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 122.8/122.8 kB 12.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 229.9/229.9 kB 24.4 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires google-auth==2.49.0, but you have google-auth 2.57.0 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.3, but you have pandas 3.0.5 which is incompatible.
dask-cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
numba 0.61.2 requires numpy<2.3,>=1.24, but you have numpy 2.5.0 which is incompatible.
cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
✅ Scientific Python packages reinstalled.
⚠️ Now restart the Colab runtime before running any other cells.

In [1]:
import sys
import numpy
import pandas
import scipy

print("Python:", sys.version.split()[0])
print("NumPy:", numpy.__version__)
print("Pandas:", pandas.__version__)
print("SciPy:", scipy.__version__)

try:
    import sklearn
    print("scikit-learn:", sklearn.__version__)
    print("✅ scikit-learn imported successfully")
except Exception as e:
    print("❌ scikit-learn import failed")
    print(type(e).__name__ + ":", e)

Python: 3.13.15
NumPy: 2.5.0
Pandas: 3.0.5
SciPy: 1.16.1
scikit-learn: 1.9.0
✅ scikit-learn imported successfully

In [2]:
import os
import json
import time
import random
import statistics
import platform
import sys
import re
import traceback

from pathlib import Path
from datetime import datetime

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
import whisper

from tqdm.auto import tqdm
from jiwer import wer, cer

from sklearn.metrics import (
    precision_score,
    recall_score,
    f1_score,
    accuracy_score
)

from scipy import stats

from pydantic import BaseModel, Field
from typing import List, Optional, Literal

from google import genai
from google.genai import types

print("✅ All required libraries imported successfully.")

ImportError: Numba needs NumPy 2.2 or less. Got NumPy 2.5.

In [3]:
!pip install -q --force-reinstall numpy==2.2.6

print("✅ NumPy changed to version 2.2.6")
print("⚠️ Restart the Colab session now.")

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires google-auth==2.49.0, but you have google-auth 2.57.0 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.3, but you have pandas 3.0.5 which is incompatible.
dask-cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
✅ NumPy changed to version 2.2.6
⚠️ Restart the Colab session now.

In [1]:
import numpy as np
import numba
import whisper

print("NumPy version:", np.__version__)
print("Numba version:", numba.__version__)
print("✅ Whisper imported successfully")

NumPy version: 2.2.6
Numba version: 0.61.2
✅ Whisper imported successfully

In [2]:
import os
import json
import time
import random
import statistics
import platform
import sys
import re
import traceback

from pathlib import Path
from datetime import datetime

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
import whisper

from tqdm.auto import tqdm
from jiwer import wer, cer

from sklearn.metrics import (
    precision_score,
    recall_score,
    f1_score,
    accuracy_score
)

from scipy import stats

from pydantic import BaseModel, Field
from typing import List, Optional, Literal

from google import genai
from google.genai import types

print("✅ All required libraries imported successfully.")

✅ All required libraries imported successfully.

In [3]:
# ============================================================
# REPRODUCIBILITY SETTINGS
# ============================================================

RANDOM_SEED = 42

random.seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)

torch.manual_seed(RANDOM_SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(RANDOM_SEED)

print("✅ Random seed fixed at:", RANDOM_SEED)
print("✅ Reproducibility settings applied.")

✅ Random seed fixed at: 42
✅ Reproducibility settings applied.

In [4]:
# ============================================================
# EXPERIMENTAL PROJECT FOLDER STRUCTURE
# ============================================================

from pathlib import Path

PROJECT_ROOT = Path("/content/AI_Meeting_Intelligence_Evaluation")

DIRS = {
    "data": PROJECT_ROOT / "data",
    "audio": PROJECT_ROOT / "data" / "audio",
    "reference_transcripts": PROJECT_ROOT / "data" / "reference_transcripts",
    "system_transcripts": PROJECT_ROOT / "data" / "system_transcripts",

    "annotator_1": PROJECT_ROOT / "gold_standard" / "annotator_1",
    "annotator_2": PROJECT_ROOT / "gold_standard" / "annotator_2",
    "consensus": PROJECT_ROOT / "gold_standard" / "consensus",

    "generic_outputs": PROJECT_ROOT / "outputs" / "generic",
    "structured_outputs": PROJECT_ROOT / "outputs" / "structured",
    "repeatability": PROJECT_ROOT / "outputs" / "repeatability",

    "asr_results": PROJECT_ROOT / "evaluation" / "asr",
    "extraction_results": PROJECT_ROOT / "evaluation" / "extraction",
    "human_results": PROJECT_ROOT / "evaluation" / "human",
    "time_results": PROJECT_ROOT / "evaluation" / "time_saving",

    "tables": PROJECT_ROOT / "results" / "tables",
    "graphs": PROJECT_ROOT / "results" / "graphs",
    "logs": PROJECT_ROOT / "logs",
    "reports": PROJECT_ROOT / "reports"
}

for folder in DIRS.values():
    folder.mkdir(parents=True, exist_ok=True)

print("✅ Experimental folder structure created successfully.")
print("Project root:", PROJECT_ROOT)
print("Total folders created:", len(DIRS))

✅ Experimental folder structure created successfully.
Project root: /content/AI_Meeting_Intelligence_Evaluation
Total folders created: 18

In [5]:
# ============================================================
# SAVE EXPERIMENTAL ENVIRONMENT INFORMATION
# ============================================================

import psutil

environment_info = {
    "experiment_version": EXPERIMENT_VERSION,
    "date_time": datetime.now().isoformat(),
    "python_version": sys.version,
    "platform": platform.platform(),
    "cpu_count": os.cpu_count(),
    "ram_gb": round(psutil.virtual_memory().total / (1024 ** 3), 2),
    "cuda_available": torch.cuda.is_available(),
    "gpu": torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU",
    "numpy_version": np.__version__,
    "torch_version": torch.__version__,
    "random_seed": RANDOM_SEED
}

environment_file = PROJECT_ROOT / "experimental_environment.json"

with open(environment_file, "w", encoding="utf-8") as f:
    json.dump(environment_info, f, indent=2)

print(json.dumps(environment_info, indent=2))
print("\n✅ Environment information saved successfully.")
print("Saved file:", environment_file)

NameError: name 'EXPERIMENT_VERSION' is not defined

In [6]:
# ============================================================
# RESTORE PROJECT CONSTANTS AFTER RUNTIME RESTART
# ============================================================

PROJECT_NAME = "AI Meeting Intelligence System"
EXPERIMENT_VERSION = "2.0"

print("✅ Project constants restored.")
print("Project:", PROJECT_NAME)
print("Experiment version:", EXPERIMENT_VERSION)

✅ Project constants restored.
Project: AI Meeting Intelligence System
Experiment version: 2.0

In [8]:
# ============================================================
# SAVE EXPERIMENTAL ENVIRONMENT INFORMATION
# ============================================================

import psutil

environment_info = {
    "experiment_version": EXPERIMENT_VERSION,
    "date_time": datetime.now().isoformat(),
    "python_version": sys.version,
    "platform": platform.platform(),
    "cpu_count": os.cpu_count(),
    "ram_gb": round(psutil.virtual_memory().total / (1024 ** 3), 2),
    "cuda_available": torch.cuda.is_available(),
    "gpu": torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU",
    "numpy_version": np.__version__,
    "torch_version": torch.__version__,
    "random_seed": RANDOM_SEED
}

environment_file = PROJECT_ROOT / "experimental_environment.json"

with open(environment_file, "w", encoding="utf-8") as f:
    json.dump(environment_info, f, indent=2)

print(json.dumps(environment_info, indent=2))
print("\n✅ Environment information saved successfully.")
print("Saved file:", environment_file)

{
  "experiment_version": "2.0",
  "date_time": "2026-09-01T13:25:59.509013",
  "python_version": "3.13.15 (main, Aug  6 2026, 11:06:23) [GCC 11.4.0]",
  "platform": "Linux-6.6.122+-x86_64-with-glibc2.35",
  "cpu_count": 2,
  "ram_gb": 12.67,
  "cuda_available": true,
  "gpu": "Tesla T4",
  "numpy_version": "2.2.6",
  "torch_version": "2.11.0+cu128",
  "random_seed": 42
}

✅ Environment information saved successfully.
Saved file: /content/AI_Meeting_Intelligence_Evaluation/experimental_environment.json

In [11]:
# ============================================================
# CORRECTED EXPERIMENTAL RESEARCH QUESTIONS
# ============================================================

RESEARCH_QUESTIONS = {
    "RQ1": (
        "How accurately does the AI Meeting Intelligence System identify "
        "confirmed decisions and action items from varied meeting transcripts "
        "when compared with a human-annotated gold standard?"
    ),

    "RQ2": (
        "Does structured prompting improve extraction accuracy and reduce "
        "hallucination compared with generic prompting under identical "
        "model and dataset conditions?"
    ),

    "RQ3": (
        "How do human evaluators rate the accuracy, completeness, clarity "
        "and usefulness of AI-generated meeting summaries and structured outputs?"
    ),

    "RQ4": (
        "How much processing and documentation time can the AI Meeting "
        "Intelligence System save compared with manual preparation of meeting notes?"
    )
}

rq_file = PROJECT_ROOT / "research_questions.json"

with open(rq_file, "w", encoding="utf-8") as f:
    json.dump(RESEARCH_QUESTIONS, f, indent=2)

print("Corrected research questions saved successfully.\n")

for rq, question in RESEARCH_QUESTIONS.items():
    print(f"{rq}: {question}\n")

print("Saved file:", rq_file)

Corrected research questions saved successfully.

RQ1: How accurately does the AI Meeting Intelligence System identify confirmed decisions and action items from varied meeting transcripts when compared with a human-annotated gold standard?

RQ2: Does structured prompting improve extraction accuracy and reduce hallucination compared with generic prompting under identical model and dataset conditions?

RQ3: How do human evaluators rate the accuracy, completeness, clarity and usefulness of AI-generated meeting summaries and structured outputs?

RQ4: How much processing and documentation time can the AI Meeting Intelligence System save compared with manual preparation of meeting notes?

Saved file: /content/AI_Meeting_Intelligence_Evaluation/research_questions.json

In [12]:
# ============================================================
# EXPERIMENTAL EVALUATION PLAN
# ============================================================

EVALUATION_PLAN = {
    "number_of_meetings": 30,

    "prompt_conditions": [
        "generic",
        "structured"
    ],

    "runs_per_prompt": 3,

    "human_annotators": 2,

    "summary_rating_scale": {
        "minimum": 1,
        "maximum": 5
    },

    "summary_dimensions": [
        "accuracy",
        "completeness",
        "clarity",
        "usefulness"
    ],

    "extraction_metrics": [
        "precision",
        "recall",
        "f1_score",
        "hallucination_rate",
        "owner_accuracy",
        "deadline_accuracy"
    ],

    "asr_metrics": [
        "word_error_rate",
        "character_error_rate"
    ],

    "efficiency_metrics": [
        "whisper_processing_time",
        "gemini_processing_time",
        "total_ai_time",
        "manual_note_time",
        "human_review_time",
        "net_time_saved",
        "percentage_time_saved"
    ]
}

evaluation_plan_file = PROJECT_ROOT / "evaluation_plan.json"

with open(evaluation_plan_file, "w", encoding="utf-8") as f:
    json.dump(EVALUATION_PLAN, f, indent=2)

print("Experimental evaluation plan saved successfully.\n")
print(json.dumps(EVALUATION_PLAN, indent=2))

print("\nSaved file:", evaluation_plan_file)

total_llm_runs = (
    EVALUATION_PLAN["number_of_meetings"]
    * len(EVALUATION_PLAN["prompt_conditions"])
    * EVALUATION_PLAN["runs_per_prompt"]
)

print("\nPlanned Gemini experimental runs:", total_llm_runs)

Experimental evaluation plan saved successfully.

{
  "number_of_meetings": 30,
  "prompt_conditions": [
    "generic",
    "structured"
  ],
  "runs_per_prompt": 3,
  "human_annotators": 2,
  "summary_rating_scale": {
    "minimum": 1,
    "maximum": 5
  },
  "summary_dimensions": [
    "accuracy",
    "completeness",
    "clarity",
    "usefulness"
  ],
  "extraction_metrics": [
    "precision",
    "recall",
    "f1_score",
    "hallucination_rate",
    "owner_accuracy",
    "deadline_accuracy"
  ],
  "asr_metrics": [
    "word_error_rate",
    "character_error_rate"
  ],
  "efficiency_metrics": [
    "whisper_processing_time",
    "gemini_processing_time",
    "total_ai_time",
    "manual_note_time",
    "human_review_time",
    "net_time_saved",
    "percentage_time_saved"
  ]
}

Saved file: /content/AI_Meeting_Intelligence_Evaluation/evaluation_plan.json

Planned Gemini experimental runs: 180

In [13]:
# ============================================================
# DATASET MANIFEST
# 30 MEETING CASES WITH VARIED EXPERIMENTAL CONDITIONS
# ============================================================

dataset_records = []

lengths = ["Short", "Medium", "Long"]
audio_qualities = ["Clean", "Moderate Noise", "Noisy"]
speaker_counts = [1, 2, 3, 4]
accent_groups = [
    "British English",
    "American English",
    "South Asian English",
    "African English",
    "Mixed English"
]

meeting_domains = [
    "Project Management",
    "Academic Supervision",
    "Software Development",
    "Business Operations",
    "Team Planning",
    "Client Review"
]

for i in range(1, 31):

    meeting_id = f"M{i:02d}"

    record = {
        "meeting_id": meeting_id,

        # Experimental variation
        "meeting_length": lengths[(i - 1) % len(lengths)],
        "audio_quality": audio_qualities[(i - 1) % len(audio_qualities)],
        "number_of_speakers": speaker_counts[(i - 1) % len(speaker_counts)],
        "accent_group": accent_groups[(i - 1) % len(accent_groups)],
        "meeting_domain": meeting_domains[(i - 1) % len(meeting_domains)],

        # Data source fields
        "input_type": "",
        "audio_filename": "",
        "reference_transcript_filename": "",

        # Ground-truth characteristics
        "number_of_gold_decisions": "",
        "number_of_gold_actions": "",
        "contains_owner": "",
        "contains_deadline": "",

        # Evaluation status
        "audio_available": False,
        "reference_transcript_available": False,
        "annotator_1_complete": False,
        "annotator_2_complete": False,
        "consensus_complete": False,

        # Notes
        "source_notes": ""
    }

    dataset_records.append(record)


dataset_manifest = pd.DataFrame(dataset_records)

manifest_file = DIRS["data"] / "dataset_manifest.csv"

dataset_manifest.to_csv(
    manifest_file,
    index=False
)

print("Dataset manifest created successfully.")
print("Total planned meeting cases:", len(dataset_manifest))
print("\nDataset variation summary:\n")

print(
    dataset_manifest[
        [
            "meeting_length",
            "audio_quality",
            "number_of_speakers",
            "accent_group",
            "meeting_domain"
        ]
    ].describe(include="all")
)

print("\nFirst 10 planned meeting cases:\n")

display(
    dataset_manifest[
        [
            "meeting_id",
            "meeting_length",
            "audio_quality",
            "number_of_speakers",
            "accent_group",
            "meeting_domain"
        ]
    ].head(10)
)

print("\nSaved file:", manifest_file)

Dataset manifest created successfully.
Total planned meeting cases: 30

Dataset variation summary:

       meeting_length audio_quality  number_of_speakers     accent_group  \
count              30            30           30.000000               30
unique              3             3                 NaN                5
top             Short         Clean                 NaN  British English
freq               10            10                 NaN                6
mean              NaN           NaN            2.433333              NaN
std               NaN           NaN            1.135124              NaN
min               NaN           NaN            1.000000              NaN
25%               NaN           NaN            1.250000              NaN
50%               NaN           NaN            2.000000              NaN
75%               NaN           NaN            3.000000              NaN
max               NaN           NaN            4.000000              NaN

            meeting_domain
count                   30
unique                   6
top     Project Management
freq                     5
mean                   NaN
std                    NaN
min                    NaN
25%                    NaN
50%                    NaN
75%                    NaN
max                    NaN

First 10 planned meeting cases:

,meeting_id,meeting_length,audio_quality,number_of_speakers,accent_group,meeting_domain
0,M01,Short,Clean,1,British English,Project Management
1,M02,Medium,Moderate Noise,2,American English,Academic Supervision
2,M03,Long,Noisy,3,South Asian English,Software Development
3,M04,Short,Clean,4,African English,Business Operations
4,M05,Medium,Moderate Noise,1,Mixed English,Team Planning
5,M06,Long,Noisy,2,British English,Client Review
6,M07,Short,Clean,3,American English,Project Management
7,M08,Medium,Moderate Noise,4,South Asian English,Academic Supervision
8,M09,Long,Noisy,1,African English,Software Development
9,M10,Short,Clean,2,Mixed English,Business Operations

Saved file: /content/AI_Meeting_Intelligence_Evaluation/data/dataset_manifest.csv

In [14]:
# ============================================================
# CORRECT DATASET MANIFEST TO AVOID CONFOUNDING
# ============================================================

random.seed(RANDOM_SEED)

meeting_ids = [f"M{i:02d}" for i in range(1, 31)]

# Balanced lists
meeting_lengths = (
    ["Short"] * 10 +
    ["Medium"] * 10 +
    ["Long"] * 10
)

audio_qualities = (
    ["Clean"] * 10 +
    ["Moderate Noise"] * 10 +
    ["Noisy"] * 10
)

accent_groups = (
    ["British English"] * 6 +
    ["American English"] * 6 +
    ["South Asian English"] * 6 +
    ["African English"] * 6 +
    ["Mixed English"] * 6
)

meeting_domains = (
    ["Project Management"] * 5 +
    ["Academic Supervision"] * 5 +
    ["Software Development"] * 5 +
    ["Business Operations"] * 5 +
    ["Team Planning"] * 5 +
    ["Client Review"] * 5
)

speaker_counts = (
    [1] * 8 +
    [2] * 8 +
    [3] * 7 +
    [4] * 7
)

# Shuffle each experimental variable independently
random.shuffle(meeting_lengths)
random.shuffle(audio_qualities)
random.shuffle(accent_groups)
random.shuffle(meeting_domains)
random.shuffle(speaker_counts)

corrected_records = []

for i, meeting_id in enumerate(meeting_ids):

    corrected_records.append({
        "meeting_id": meeting_id,

        "meeting_length": meeting_lengths[i],
        "audio_quality": audio_qualities[i],
        "number_of_speakers": speaker_counts[i],
        "accent_group": accent_groups[i],
        "meeting_domain": meeting_domains[i],

        "input_type": "",
        "audio_filename": "",
        "reference_transcript_filename": "",

        "number_of_gold_decisions": "",
        "number_of_gold_actions": "",
        "contains_owner": "",
        "contains_deadline": "",

        "audio_available": False,
        "reference_transcript_available": False,
        "annotator_1_complete": False,
        "annotator_2_complete": False,
        "consensus_complete": False,

        "source_notes": ""
    })

dataset_manifest = pd.DataFrame(corrected_records)

manifest_file = DIRS["data"] / "dataset_manifest.csv"

dataset_manifest.to_csv(
    manifest_file,
    index=False
)

print("Corrected dataset manifest saved successfully.")
print("Total meetings:", len(dataset_manifest))

print("\nMeeting length counts:")
print(dataset_manifest["meeting_length"].value_counts())

print("\nAudio quality counts:")
print(dataset_manifest["audio_quality"].value_counts())

print("\nAccent counts:")
print(dataset_manifest["accent_group"].value_counts())

print("\nSpeaker-count distribution:")
print(dataset_manifest["number_of_speakers"].value_counts().sort_index())

print("\nCross-tabulation: Meeting Length vs Audio Quality")
print(
    pd.crosstab(
        dataset_manifest["meeting_length"],
        dataset_manifest["audio_quality"]
    )
)

print("\nFirst 10 corrected cases:")
display(
    dataset_manifest[
        [
            "meeting_id",
            "meeting_length",
            "audio_quality",
            "number_of_speakers",
            "accent_group",
            "meeting_domain"
        ]
    ].head(10)
)

print("\nSaved file:", manifest_file)

Corrected dataset manifest saved successfully.
Total meetings: 30

Meeting length counts:
meeting_length
Medium    10
Long      10
Short     10
Name: count, dtype: int64

Audio quality counts:
audio_quality
Moderate Noise    10
Noisy             10
Clean             10
Name: count, dtype: int64

Accent counts:
accent_group
South Asian English    6
Mixed English          6
African English        6
British English        6
American English       6
Name: count, dtype: int64

Speaker-count distribution:
number_of_speakers
1    8
2    8
3    7
4    7
Name: count, dtype: int64

Cross-tabulation: Meeting Length vs Audio Quality
audio_quality   Clean  Moderate Noise  Noisy
meeting_length
Long                3               5      2
Medium              2               3      5
Short               5               2      3

First 10 corrected cases:

,meeting_id,meeting_length,audio_quality,number_of_speakers,accent_group,meeting_domain
0,M01,Medium,Moderate Noise,4,South Asian English,Client Review
1,M02,Medium,Noisy,3,South Asian English,Client Review
2,M03,Medium,Moderate Noise,2,Mixed English,Project Management
3,M04,Long,Moderate Noise,1,African English,Project Management
4,M05,Long,Moderate Noise,3,British English,Software Development
5,M06,Short,Noisy,4,South Asian English,Software Development
6,M07,Short,Moderate Noise,1,American English,Business Operations
7,M08,Medium,Clean,2,South Asian English,Academic Supervision
8,M09,Medium,Noisy,1,Mixed English,Business Operations
9,M10,Medium,Moderate Noise,3,Mixed English,Business Operations

Saved file: /content/AI_Meeting_Intelligence_Evaluation/data/dataset_manifest.csv

In [15]:
# ============================================================
# DATASET EVIDENCE AND COMPLETENESS CHECK
# ============================================================

required_dataset_fields = [
    "meeting_id",
    "meeting_length",
    "audio_quality",
    "number_of_speakers",
    "accent_group",
    "meeting_domain",
    "audio_filename",
    "reference_transcript_filename",
    "audio_available",
    "reference_transcript_available"
]

missing_columns = [
    col for col in required_dataset_fields
    if col not in dataset_manifest.columns
]

if missing_columns:
    print("ERROR: Missing required columns:")
    print(missing_columns)

else:
    print("Dataset structure check passed.")

    dataset_manifest["ready_for_asr_evaluation"] = (
        dataset_manifest["audio_available"].astype(bool)
        &
        dataset_manifest["reference_transcript_available"].astype(bool)
    )

    ready_count = int(
        dataset_manifest["ready_for_asr_evaluation"].sum()
    )

    total_count = len(dataset_manifest)

    print("\nDataset readiness:")
    print("Total planned meetings:", total_count)
    print("Ready for ASR evaluation:", ready_count)
    print("Not yet ready:", total_count - ready_count)

    print("\nCurrent evidence status:")
    display(
        dataset_manifest[
            [
                "meeting_id",
                "audio_filename",
                "reference_transcript_filename",
                "audio_available",
                "reference_transcript_available",
                "ready_for_asr_evaluation"
            ]
        ]
    )

    # Save updated manifest
    manifest_file = DIRS["data"] / "dataset_manifest.csv"

    dataset_manifest.to_csv(
        manifest_file,
        index=False
    )

    print("\nUpdated dataset manifest saved:")
    print(manifest_file)

    if ready_count == 0:
        print(
            "\nIMPORTANT: No meetings are currently marked as ready. "
            "This is expected because actual audio files and human/reference "
            "transcripts have not yet been added."
        )

Dataset structure check passed.

Dataset readiness:
Total planned meetings: 30
Ready for ASR evaluation: 0
Not yet ready: 30

Current evidence status:

,meeting_id,audio_filename,reference_transcript_filename,audio_available,reference_transcript_available,ready_for_asr_evaluation
0,M01,,,False,False,False
1,M02,,,False,False,False
2,M03,,,False,False,False
3,M04,,,False,False,False
4,M05,,,False,False,False
5,M06,,,False,False,False
6,M07,,,False,False,False
7,M08,,,False,False,False
8,M09,,,False,False,False
9,M10,,,False,False,False
10,M11,,,False,False,False
11,M12,,,False,False,False
12,M13,,,False,False,False
13,M14,,,False,False,False
14,M15,,,False,False,False
15,M16,,,False,False,False
16,M17,,,False,False,False
17,M18,,,False,False,False
18,M19,,,False,False,False
19,M20,,,False,False,False
20,M21,,,False,False,False
21,M22,,,False,False,False
22,M23,,,False,False,False
23,M24,,,False,False,False
24,M25,,,False,False,False
25,M26,,,False,False,False
26,M27,,,False,False,False
27,M28,,,False,False,False
28,M29,,,False,False,False
29,M30,,,False,False,False

Updated dataset manifest saved:
/content/AI_Meeting_Intelligence_Evaluation/data/dataset_manifest.csv

IMPORTANT: No meetings are currently marked as ready. This is expected because actual audio files and human/reference transcripts have not yet been added.

In [17]:
# ============================================================
# LOCAL BACKUP OF CURRENT EXPERIMENT FILES
# ============================================================

import shutil
from pathlib import Path

BACKUP_ROOT = Path("/content/AI_Meeting_Intelligence_Backup")

if BACKUP_ROOT.exists():
    shutil.rmtree(BACKUP_ROOT)

shutil.copytree(
    PROJECT_ROOT,
    BACKUP_ROOT
)

print("Local backup created successfully.")
print("Backup location:", BACKUP_ROOT)

print("\nCurrent backup contents:")
for path in sorted(BACKUP_ROOT.rglob("*")):
    if path.is_file():
        print(path)

Local backup created successfully.
Backup location: /content/AI_Meeting_Intelligence_Backup

Current backup contents:
/content/AI_Meeting_Intelligence_Backup/data/dataset_manifest.csv
/content/AI_Meeting_Intelligence_Backup/evaluation_plan.json
/content/AI_Meeting_Intelligence_Backup/experimental_environment.json
/content/AI_Meeting_Intelligence_Backup/research_questions.json

In [18]:
# ============================================================
# MEETING DATA UPLOAD FUNCTION
# ============================================================

from google.colab import files
import shutil
from pathlib import Path

def upload_meeting_files(meeting_id):
    """
    Upload one audio file and one human/reference transcript
    for a specified meeting ID.
    """

    if meeting_id not in dataset_manifest["meeting_id"].values:
        print(f"ERROR: {meeting_id} is not present in the dataset manifest.")
        return

    print(f"Preparing files for {meeting_id}")
    print("\n1. Upload the AUDIO file first.")
    print("Accepted examples: .wav, .mp3, .m4a, .mp4")

    audio_upload = files.upload()

    if len(audio_upload) != 1:
        print("ERROR: Please upload exactly one audio file.")
        return

    audio_name = list(audio_upload.keys())[0]

    audio_destination = (
        DIRS["audio"] /
        f"{meeting_id}_{audio_name}"
    )

    with open(audio_destination, "wb") as f:
        f.write(audio_upload[audio_name])

    print("\nAudio saved:")
    print(audio_destination)

    print("\n2. Now upload the HUMAN/REFERENCE transcript.")
    print("Use a plain .txt transcript if possible.")

    transcript_upload = files.upload()

    if len(transcript_upload) != 1:
        print("ERROR: Please upload exactly one transcript file.")
        return

    transcript_name = list(transcript_upload.keys())[0]

    transcript_destination = (
        DIRS["reference_transcripts"] /
        f"{meeting_id}_{transcript_name}"
    )

    with open(transcript_destination, "wb") as f:
        f.write(transcript_upload[transcript_name])

    # Update manifest
    row_index = dataset_manifest.index[
        dataset_manifest["meeting_id"] == meeting_id
    ][0]

    dataset_manifest.loc[
        row_index,
        "audio_filename"
    ] = audio_destination.name

    dataset_manifest.loc[
        row_index,
        "reference_transcript_filename"
    ] = transcript_destination.name

    dataset_manifest.loc[
        row_index,
        "audio_available"
    ] = True

    dataset_manifest.loc[
        row_index,
        "reference_transcript_available"
    ] = True

    dataset_manifest.loc[
        row_index,
        "ready_for_asr_evaluation"
    ] = True

    dataset_manifest.to_csv(
        DIRS["data"] / "dataset_manifest.csv",
        index=False
    )

    print("\nMeeting files registered successfully.")
    print("Meeting ID:", meeting_id)
    print("Audio:", audio_destination.name)
    print("Transcript:", transcript_destination.name)
    print("Ready for ASR evaluation: True")


print("Meeting upload function created successfully.")
print("Next meeting to prepare: M01")

Meeting upload function created successfully.
Next meeting to prepare: M01

In [19]:
# ============================================================
# UPLOAD FIRST REAL MEETING CASE
# ============================================================

upload_meeting_files("M01")

Preparing files for M01

1. Upload the AUDIO file first.
Accepted examples: .wav, .mp3, .m4a, .mp4

Saving Meeting Transcript.mp3 to Meeting Transcript.mp3

Audio saved:
/content/AI_Meeting_Intelligence_Evaluation/data/audio/M01_Meeting Transcript.mp3

2. Now upload the HUMAN/REFERENCE transcript.
Use a plain .txt transcript if possible.

Saving Meeting Transcript.docx to Meeting Transcript.docx

Meeting files registered successfully.
Meeting ID: M01
Audio: M01_Meeting Transcript.mp3
Transcript: M01_Meeting Transcript.docx
Ready for ASR evaluation: True

In [20]:
# ============================================================
# VERIFY M01 FILES AND LOAD REFERENCE TRANSCRIPT
# ============================================================

from docx import Document

meeting_id = "M01"

row = dataset_manifest[
    dataset_manifest["meeting_id"] == meeting_id
].iloc[0]

audio_path = DIRS["audio"] / row["audio_filename"]
reference_path = (
    DIRS["reference_transcripts"] /
    row["reference_transcript_filename"]
)

print("Meeting ID:", meeting_id)
print("Audio exists:", audio_path.exists())
print("Reference transcript exists:", reference_path.exists())
print("Audio file:", audio_path.name)
print("Reference file:", reference_path.name)

# Load DOCX reference transcript
if reference_path.suffix.lower() == ".docx":

    document = Document(reference_path)

    reference_text = "\n".join(
        paragraph.text
        for paragraph in document.paragraphs
        if paragraph.text.strip()
    )

elif reference_path.suffix.lower() == ".txt":

    reference_text = reference_path.read_text(
        encoding="utf-8"
    )

else:
    raise ValueError(
        f"Unsupported transcript format: {reference_path.suffix}"
    )

print("\nReference transcript loaded successfully.")
print("Reference transcript word count:", len(reference_text.split()))

print("\nFirst 1000 characters:\n")
print(reference_text[:1000])

Meeting ID: M01
Audio exists: True
Reference transcript exists: True
Audio file: M01_Meeting Transcript.mp3
Reference file: M01_Meeting Transcript.docx

Reference transcript loaded successfully.
Reference transcript word count: 745

First 1000 characters:

Meeting Transcript
Meeting Topic: Weekly Project Progress Meeting
Duration: Approximately 5 Minutes
Participants: Sarah, James, Michael, and Aisha
Sarah: Good morning, everyone. Thanks for joining. I know everyone has a fairly busy schedule today, so I’ll try to keep this short. The main purpose of the meeting is just to check where we are with the project, discuss any issues, and agree on what needs to be completed before Friday. Is everyone okay with that?
James: Yeah, that sounds good.
Aisha: Yes, absolutely.
Michael: Fine with me.
Sarah: Great. James, maybe you can start. How are things going with the data collection?
James: Pretty well, actually. We’ve received most of the information we were waiting for. I’d say around eighty percent of the data has now been collected. There are still two departments that haven’t sent their responses, though.
Sarah: Okay. Have you followed up with them?
James: Yes. I emailed both of them yesterday afternoon. One department replied this morning an

In [21]:
# ============================================================
# CREATE CLEAN ASR REFERENCE FOR M01
# Remove document metadata and speaker labels for fair WER/CER
# ============================================================

import re

meeting_id = "M01"

# Start from the reference_text loaded in Step 16
lines = reference_text.splitlines()

clean_lines = []

metadata_prefixes = (
    "Meeting Transcript",
    "Meeting Topic:",
    "Duration:",
    "Participants:"
)

for line in lines:

    line = line.strip()

    if not line:
        continue

    # Remove document metadata/header lines
    if line.startswith(metadata_prefixes):
        continue

    # Remove speaker labels such as:
    # Sarah:
    # James:
    # Michael:
    # Aisha:
    line = re.sub(
        r"^[A-Za-z][A-Za-z .'-]{0,40}:\s*",
        "",
        line
    )

    if line:
        clean_lines.append(line)

clean_reference_text = " ".join(clean_lines)

# Normalize whitespace
clean_reference_text = re.sub(
    r"\s+",
    " ",
    clean_reference_text
).strip()

# Save clean ASR reference
clean_reference_file = (
    DIRS["reference_transcripts"] /
    "M01_ASR_reference_clean.txt"
)

clean_reference_file.write_text(
    clean_reference_text,
    encoding="utf-8"
)

print("Clean ASR reference created successfully.")
print("Original reference word count:", len(reference_text.split()))
print(
    "Clean ASR reference word count:",
    len(clean_reference_text.split())
)

print("\nFirst 1000 characters of CLEAN reference:\n")
print(clean_reference_text[:1000])

print("\nSaved file:")
print(clean_reference_file)

Clean ASR reference created successfully.
Original reference word count: 745
Clean ASR reference word count: 682

First 1000 characters of CLEAN reference:

Good morning, everyone. Thanks for joining. I know everyone has a fairly busy schedule today, so I’ll try to keep this short. The main purpose of the meeting is just to check where we are with the project, discuss any issues, and agree on what needs to be completed before Friday. Is everyone okay with that? Yeah, that sounds good. Yes, absolutely. Fine with me. Great. James, maybe you can start. How are things going with the data collection? Pretty well, actually. We’ve received most of the information we were waiting for. I’d say around eighty percent of the data has now been collected. There are still two departments that haven’t sent their responses, though. Okay. Have you followed up with them? Yes. I emailed both of them yesterday afternoon. One department replied this morning and said they should send everything by tomorrow. I haven’t heard back from the other one yet. Right. Maybe give them until tomorrow morning, and if there’s still no response, send another reminder. Yeah, th

Saved file:
/content/AI_Meeting_Intelligence_Evaluation/data/reference_transcripts/M01_ASR_reference_clean.txt

In [23]:
# ============================================================
# LOAD WHISPER MODEL FOR ASR EVALUATION
# ============================================================

WHISPER_MODEL_NAME = "small.en"

device = "cuda" if torch.cuda.is_available() else "cpu"

print("Loading Whisper model:", WHISPER_MODEL_NAME)
print("Processing device:", device)

whisper_load_start = time.perf_counter()

whisper_model = whisper.load_model(
    WHISPER_MODEL_NAME,
    device=device
)

whisper_load_time = time.perf_counter() - whisper_load_start

print("\nWhisper model loaded successfully.")
print("Model:", WHISPER_MODEL_NAME)
print("Device:", device)
print(
    "GPU:",
    torch.cuda.get_device_name(0)
    if torch.cuda.is_available()
    else "Not available"
)
print(
    "Model loading time:",
    round(whisper_load_time, 3),
    "seconds"
)

Loading Whisper model: small.en
Processing device: cuda

100%|███████████████████████████████████████| 461M/461M [00:08<00:00, 60.4MiB/s]

Whisper model loaded successfully.
Model: small.en
Device: cuda
GPU: Tesla T4
Model loading time: 13.989 seconds

In [24]:
# ============================================================
# TRANSCRIBE M01 WITH WHISPER
# ============================================================

meeting_id = "M01"

row = dataset_manifest[
    dataset_manifest["meeting_id"] == meeting_id
].iloc[0]

audio_path = DIRS["audio"] / row["audio_filename"]

print("Transcribing:", audio_path.name)
print("Whisper model:", WHISPER_MODEL_NAME)
print("Device:", device)

transcription_start = time.perf_counter()

result = whisper_model.transcribe(
    str(audio_path),
    language="en",
    temperature=0.0,
    fp16=torch.cuda.is_available(),
    verbose=False
)

transcription_time = time.perf_counter() - transcription_start

whisper_transcript = result["text"].strip()

# Save Whisper transcript
whisper_output_file = (
    DIRS["system_transcripts"] /
    "M01_whisper_transcript.txt"
)

whisper_output_file.write_text(
    whisper_transcript,
    encoding="utf-8"
)

print("\nWhisper transcription completed successfully.")
print("Processing time:", round(transcription_time, 3), "seconds")
print("Whisper transcript word count:", len(whisper_transcript.split()))

print("\nFirst 1000 characters of Whisper transcript:\n")
print(whisper_transcript[:1000])

print("\nSaved file:")
print(whisper_output_file)

Transcribing: M01_Meeting Transcript.mp3
Whisper model: small.en
Device: cuda

100%|██████████| 36374/36374 [00:20<00:00, 1771.78frames/s]

Whisper transcription completed successfully.
Processing time: 24.352 seconds
Whisper transcript word count: 746

First 1000 characters of Whisper transcript:

Meeting transcript Meeting topic, weekly project progress meeting Duration, approximately 5 minutes Participants, Sarah, James, Michael and Ayesha Sarah, good morning, everyone Thanks for joining I know everyone has a fairly busy schedule today, so I'll try to keep this short The main purpose of the meeting is just to check where we are with the project, discuss any issues, and agree on what needs to be completed before Friday Is everyone OK with that? James, yeah, that sounds good Ayesha, yes, absolutely Michael, fine with me Sarah, great James, maybe you can start How are things going with the data collection? James, pretty well, actually We've received most of the information we were waiting for I'd say around 80% of the data has now been collected There are still two departments that haven't sent their responses, though Sarah, OK Have you followed up with them? James, yes I emailed both of them yesterday afternoon One department replied this morning and said they should send everyt

Saved file:
/content/AI_Meeting_Intelligence_Evaluation/data/system_transcripts/M01_whisper_transcript.txt

In [25]:
# ============================================================
# M01 ASR ACCURACY: WER AND CER
# ============================================================

import re
import unicodedata
from jiwer import wer, cer


def normalize_asr_text(text):
    """
    Normalize reference and Whisper transcript equally
    before calculating WER/CER.
    """

    # Unicode normalization
    text = unicodedata.normalize("NFKC", text)

    # Normalize apostrophes
    text = text.replace("’", "'")
    text = text.replace("‘", "'")

    # Lowercase
    text = text.lower()

    # Normalize percentage symbol
    text = text.replace("%", " percent ")

    # Remove punctuation but preserve letters/numbers/apostrophes
    text = re.sub(
        r"[^a-z0-9'\s]",
        " ",
        text
    )

    # Normalize whitespace
    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text


# IMPORTANT:
# Use FULL reference because the audio itself contains
# headings and speaker names.
reference_normalized = normalize_asr_text(reference_text)
whisper_normalized = normalize_asr_text(whisper_transcript)

m01_wer = wer(
    reference_normalized,
    whisper_normalized
)

m01_cer = cer(
    reference_normalized,
    whisper_normalized
)

print("M01 ASR EVALUATION")
print("=" * 50)

print(
    "Reference words:",
    len(reference_normalized.split())
)

print(
    "Whisper words:",
    len(whisper_normalized.split())
)

print(
    "Word Error Rate (WER):",
    round(m01_wer, 4)
)

print(
    "WER percentage:",
    round(m01_wer * 100, 2),
    "%"
)

print(
    "Character Error Rate (CER):",
    round(m01_cer, 4)
)

print(
    "CER percentage:",
    round(m01_cer * 100, 2),
    "%"
)

print(
    "Approximate Word Accuracy:",
    round((1 - m01_wer) * 100, 2),
    "%"
)

M01 ASR EVALUATION
==================================================
Reference words: 745
Whisper words: 747
Word Error Rate (WER): 0.0282
WER percentage: 2.82 %
Character Error Rate (CER): 0.0089
CER percentage: 0.89 %
Approximate Word Accuracy: 97.18 %

In [26]:
# ============================================================
# SAVE M01 ASR RESULT
# ============================================================

asr_result = {
    "meeting_id": "M01",
    "whisper_model": WHISPER_MODEL_NAME,
    "device": device,
    "gpu": (
        torch.cuda.get_device_name(0)
        if torch.cuda.is_available()
        else "CPU"
    ),
    "reference_word_count": len(reference_normalized.split()),
    "whisper_word_count": len(whisper_normalized.split()),
    "processing_time_seconds": round(transcription_time, 3),
    "wer": round(m01_wer, 4),
    "wer_percent": round(m01_wer * 100, 2),
    "cer": round(m01_cer, 4),
    "cer_percent": round(m01_cer * 100, 2),
    "approx_word_accuracy_percent": round((1 - m01_wer) * 100, 2)
}

asr_results_file = (
    DIRS["asr_results"] /
    "asr_results.csv"
)

if asr_results_file.exists():
    asr_results_df = pd.read_csv(asr_results_file)

    # Remove an existing M01 row to avoid duplicates
    asr_results_df = asr_results_df[
        asr_results_df["meeting_id"] != "M01"
    ]

    asr_results_df = pd.concat(
        [
            asr_results_df,
            pd.DataFrame([asr_result])
        ],
        ignore_index=True
    )

else:
    asr_results_df = pd.DataFrame([asr_result])

asr_results_df.to_csv(
    asr_results_file,
    index=False
)

print("M01 ASR result saved successfully.\n")

display(asr_results_df)

print("\nSaved file:")
print(asr_results_file)

M01 ASR result saved successfully.

,meeting_id,whisper_model,device,gpu,reference_word_count,whisper_word_count,processing_time_seconds,wer,wer_percent,cer,cer_percent,approx_word_accuracy_percent
0,M01,small.en,cuda,Tesla T4,745,747,24.352,0.0282,2.82,0.0089,0.89,97.18

Saved file:
/content/AI_Meeting_Intelligence_Evaluation/evaluation/asr/asr_results.csv

In [27]:
# ============================================================
# GEMINI API SECURE CONFIGURATION
# ============================================================

from getpass import getpass
from google import genai

print("Enter your Gemini API key below.")
print("The key will be hidden while you type/paste it.")

GEMINI_API_KEY = getpass("Gemini API Key: ")

if not GEMINI_API_KEY.strip():
    raise ValueError("No Gemini API key was entered.")

# Create Gemini client
gemini_client = genai.Client(
    api_key=GEMINI_API_KEY
)

print("\nGemini client created successfully.")
print("API key loaded: Yes")
print("API key displayed: No")
print("Ready for API connectivity testing.")

Enter your Gemini API key below.
The key will be hidden while you type/paste it.
Gemini API Key: ··········

Gemini client created successfully.
API key loaded: Yes
API key displayed: No
Ready for API connectivity testing.

In [28]:
# ============================================================
# GEMINI CONNECTIVITY TEST
# DOCUMENT SUCCESS / 403 / OTHER API ERRORS
# ============================================================

from datetime import datetime
import json
import time

GEMINI_TEST_MODEL = "gemini-2.5-flash"

gemini_test_log = {
    "timestamp": datetime.now().isoformat(),
    "model": GEMINI_TEST_MODEL,
    "status": None,
    "http_403_detected": False,
    "response_text": None,
    "error_type": None,
    "error_message": None,
    "latency_seconds": None
}

print("Testing Gemini API connectivity...")
print("Model:", GEMINI_TEST_MODEL)

start_time = time.perf_counter()

try:
    response = gemini_client.models.generate_content(
        model=GEMINI_TEST_MODEL,
        contents="Reply with exactly: GEMINI_API_TEST_SUCCESS"
    )

    latency = time.perf_counter() - start_time

    response_text = response.text.strip()

    gemini_test_log["status"] = "SUCCESS"
    gemini_test_log["response_text"] = response_text
    gemini_test_log["latency_seconds"] = round(latency, 3)

    print("\nGemini API request successful.")
    print("Response:", response_text)
    print("Latency:", round(latency, 3), "seconds")
    print("403 error detected: No")

except Exception as e:
    latency = time.perf_counter() - start_time

    error_message = str(e)

    gemini_test_log["status"] = "FAILED"
    gemini_test_log["error_type"] = type(e).__name__
    gemini_test_log["error_message"] = error_message
    gemini_test_log["latency_seconds"] = round(latency, 3)

    if "403" in error_message or "PERMISSION_DENIED" in error_message.upper():
        gemini_test_log["http_403_detected"] = True

    print("\nGemini API request failed.")
    print("Error type:", type(e).__name__)
    print("Error message:", error_message)
    print(
        "403 error detected:",
        "Yes" if gemini_test_log["http_403_detected"] else "No"
    )

# Save evidence log
gemini_log_file = (
    DIRS["logs"] /
    "gemini_connectivity_test.json"
)

with open(gemini_log_file, "w", encoding="utf-8") as f:
    json.dump(gemini_test_log, f, indent=2)

print("\nConnectivity test log saved:")
print(gemini_log_file)

WARNING:google_genai.models:Direct use of automatic function calling (AFC) in Models.generate_content is not recommended. Instead, we recommend to use AFC in Chat.send_message. Similarly, direct use of AFC in Models.generate_content_stream is not recommended. Instead, we recommend to use AFC in Chat.send_message_stream.

Testing Gemini API connectivity...
Model: gemini-2.5-flash

Gemini API request failed.
Error type: ClientError
Error message: 404 NOT_FOUND. {'error': {'code': 404, 'message': 'This model models/gemini-2.5-flash is no longer available to new users. Please update your code to use models/gemini-3.6-flash for the latest features and improvements. We recommend you to use the Interactions API.', 'status': 'NOT_FOUND'}}
403 error detected: No

Connectivity test log saved:
/content/AI_Meeting_Intelligence_Evaluation/logs/gemini_connectivity_test.json

In [29]:
# ============================================================
# GEMINI CONNECTIVITY RETEST WITH CURRENT STABLE MODEL
# ============================================================

from datetime import datetime
import json
import time

GEMINI_MODEL = "gemini-3.6-flash"

gemini_retest_log = {
    "timestamp": datetime.now().isoformat(),
    "model": GEMINI_MODEL,
    "status": None,
    "http_403_detected": False,
    "http_404_detected": False,
    "response_text": None,
    "error_type": None,
    "error_message": None,
    "latency_seconds": None
}

print("Retesting Gemini API connectivity...")
print("Model:", GEMINI_MODEL)

start_time = time.perf_counter()

try:
    response = gemini_client.models.generate_content(
        model=GEMINI_MODEL,
        contents="Reply with exactly: GEMINI_API_TEST_SUCCESS"
    )

    latency = time.perf_counter() - start_time
    response_text = response.text.strip()

    gemini_retest_log["status"] = "SUCCESS"
    gemini_retest_log["response_text"] = response_text
    gemini_retest_log["latency_seconds"] = round(latency, 3)

    print("\nGemini API request successful.")
    print("Response:", response_text)
    print("Latency:", round(latency, 3), "seconds")
    print("403 error detected: No")
    print("404 error detected: No")

except Exception as e:
    latency = time.perf_counter() - start_time

    error_message = str(e)

    gemini_retest_log["status"] = "FAILED"
    gemini_retest_log["error_type"] = type(e).__name__
    gemini_retest_log["error_message"] = error_message
    gemini_retest_log["latency_seconds"] = round(latency, 3)

    if "403" in error_message or "PERMISSION_DENIED" in error_message.upper():
        gemini_retest_log["http_403_detected"] = True

    if "404" in error_message or "NOT_FOUND" in error_message.upper():
        gemini_retest_log["http_404_detected"] = True

    print("\nGemini API request failed.")
    print("Error type:", type(e).__name__)
    print("Error message:", error_message)
    print(
        "403 error detected:",
        "Yes" if gemini_retest_log["http_403_detected"] else "No"
    )
    print(
        "404 error detected:",
        "Yes" if gemini_retest_log["http_404_detected"] else "No"
    )

# Save retest evidence
gemini_retest_file = (
    DIRS["logs"] /
    "gemini_connectivity_retest.json"
)

with open(gemini_retest_file, "w", encoding="utf-8") as f:
    json.dump(gemini_retest_log, f, indent=2)

print("\nRetest log saved:")
print(gemini_retest_file)

Retesting Gemini API connectivity...
Model: gemini-3.6-flash

Gemini API request successful.
Response: GEMINI_API_TEST_SUCCESS
Latency: 46.788 seconds
403 error detected: No
404 error detected: No

Retest log saved:
/content/AI_Meeting_Intelligence_Evaluation/logs/gemini_connectivity_retest.json

In [30]:
# ============================================================
# GEMINI STABILITY TEST - 3 CONSECUTIVE SUCCESSFUL RUNS
# ============================================================

import time
import json
import pandas as pd
from datetime import datetime

GEMINI_STABILITY_RUNS = 3

stability_results = []

print("Gemini stability test")
print("Model:", GEMINI_MODEL)
print("Number of runs:", GEMINI_STABILITY_RUNS)
print("=" * 55)

for run_number in range(1, GEMINI_STABILITY_RUNS + 1):

    print(f"\nRunning API test {run_number}/{GEMINI_STABILITY_RUNS}...")

    start_time = time.perf_counter()

    try:
        response = gemini_client.models.generate_content(
            model=GEMINI_MODEL,
            contents=(
                f"This is Gemini API stability test run {run_number}. "
                "Reply with exactly: GEMINI_STABLE_SUCCESS"
            )
        )

        latency = time.perf_counter() - start_time
        response_text = response.text.strip()

        success = (
            response_text == "GEMINI_STABLE_SUCCESS"
        )

        stability_results.append({
            "run": run_number,
            "timestamp": datetime.now().isoformat(),
            "model": GEMINI_MODEL,
            "status": "SUCCESS" if success else "UNEXPECTED_RESPONSE",
            "response": response_text,
            "latency_seconds": round(latency, 3),
            "http_403": False,
            "error": ""
        })

        print("Status:", "SUCCESS" if success else "UNEXPECTED RESPONSE")
        print("Response:", response_text)
        print("Latency:", round(latency, 3), "seconds")

    except Exception as e:

        latency = time.perf_counter() - start_time
        error_message = str(e)

        stability_results.append({
            "run": run_number,
            "timestamp": datetime.now().isoformat(),
            "model": GEMINI_MODEL,
            "status": "FAILED",
            "response": "",
            "latency_seconds": round(latency, 3),
            "http_403": (
                "403" in error_message
                or "PERMISSION_DENIED" in error_message.upper()
            ),
            "error": error_message
        })

        print("Status: FAILED")
        print("Error:", error_message)


# Convert to DataFrame
gemini_stability_df = pd.DataFrame(stability_results)

# Save CSV evidence
stability_csv = (
    DIRS["logs"] /
    "gemini_stability_test.csv"
)

gemini_stability_df.to_csv(
    stability_csv,
    index=False
)

print("\n" + "=" * 55)
print("STABILITY TEST SUMMARY")
print("=" * 55)

display(gemini_stability_df)

successful_runs = (
    gemini_stability_df["status"] == "SUCCESS"
).sum()

print(
    "\nSuccessful runs:",
    f"{successful_runs}/{GEMINI_STABILITY_RUNS}"
)

print(
    "403 errors:",
    int(gemini_stability_df["http_403"].sum())
)

print(
    "Mean latency:",
    round(
        gemini_stability_df["latency_seconds"].mean(),
        3
    ),
    "seconds"
)

print(
    "Latency standard deviation:",
    round(
        gemini_stability_df["latency_seconds"].std(ddof=1),
        3
    ),
    "seconds"
)

print("\nSaved file:")
print(stability_csv)

Gemini stability test
Model: gemini-3.6-flash
Number of runs: 3
=======================================================

Running API test 1/3...
Status: FAILED
Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-3.6-flash\nPlease retry in 47.02587033s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.6-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '47s'}]}}

Running API test 2/3...
Status: FAILED
Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-3.6-flash\nPlease retry in 46.87726444s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.6-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '46s'}]}}

Running API test 3/3...
Status: FAILED
Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-3.6-flash\nPlease retry in 46.72254973s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.6-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '46s'}]}}

=======================================================
STABILITY TEST SUMMARY
=======================================================

,run,timestamp,model,status,response,latency_seconds,http_403,error
0,1,2026-09-01T13:46:12.980770,gemini-3.6-flash,FAILED,,0.301,False,429 RESOURCE_EXHAUSTED. {'error': {'code': 429...
1,2,2026-09-01T13:46:13.130630,gemini-3.6-flash,FAILED,,0.148,False,429 RESOURCE_EXHAUSTED. {'error': {'code': 429...
2,3,2026-09-01T13:46:13.284506,gemini-3.6-flash,FAILED,,0.154,False,429 RESOURCE_EXHAUSTED. {'error': {'code': 429...

Successful runs: 0/3
403 errors: 0
Mean latency: 0.201 seconds
Latency standard deviation: 0.087 seconds

Saved file:
/content/AI_Meeting_Intelligence_Evaluation/logs/gemini_stability_test.csv

In [31]:
# ============================================================
# DOCUMENT GEMINI API ERROR RESOLUTION AND QUOTA LIMITATION
# ============================================================

gemini_api_status = {
    "original_problem": "Gemini API 403 error reported during earlier development",

    "current_api_key_status": "VALID",

    "obsolete_model_test": {
        "model": "gemini-2.5-flash",
        "result": "FAILED",
        "error_code": 404,
        "interpretation": (
            "Model unavailable to new users. "
            "This was a model availability issue, not an API-key permission error."
        )
    },

    "corrected_model_test": {
        "model": "gemini-3.6-flash",
        "result": "SUCCESS",
        "response": "GEMINI_API_TEST_SUCCESS",
        "latency_seconds": 46.788,
        "http_403": False
    },

    "stability_test": {
        "planned_runs": 3,
        "successful_runs": 0,
        "failed_runs": 3,
        "error_code": 429,
        "error_type": "RESOURCE_EXHAUSTED",
        "http_403_errors": 0,
        "interpretation": (
            "The repeated-run test was blocked by the Gemini API "
            "free-tier quota/rate limit. The failures therefore do not "
            "demonstrate model instability or authentication failure."
        )
    },

    "overall_conclusion": (
        "The previous Gemini 403 permission issue is not present in the "
        "current implementation. A successful request was completed using "
        "gemini-3.6-flash. Further repeated-run evaluation is currently "
        "limited by API quota availability."
    )
}

gemini_status_file = (
    DIRS["logs"] /
    "gemini_api_resolution_summary.json"
)

with open(
    gemini_status_file,
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        gemini_api_status,
        f,
        indent=2
    )

print("GEMINI API RESOLUTION SUMMARY")
print("=" * 60)

print("API key status: VALID")
print("Previous 403 currently observed: NO")
print("Successful Gemini request: YES")
print("Working model: gemini-3.6-flash")
print("Successful test latency: 46.788 seconds")
print("Repeated-run result: BLOCKED BY API QUOTA (429)")
print("403 errors during stability test: 0")

print("\nConclusion:")
print(
    gemini_api_status["overall_conclusion"]
)

print("\nSaved evidence file:")
print(gemini_status_file)

GEMINI API RESOLUTION SUMMARY
============================================================
API key status: VALID
Previous 403 currently observed: NO
Successful Gemini request: YES
Working model: gemini-3.6-flash
Successful test latency: 46.788 seconds
Repeated-run result: BLOCKED BY API QUOTA (429)
403 errors during stability test: 0

Conclusion:
The previous Gemini 403 permission issue is not present in the current implementation. A successful request was completed using gemini-3.6-flash. Further repeated-run evaluation is currently limited by API quota availability.

Saved evidence file:
/content/AI_Meeting_Intelligence_Evaluation/logs/gemini_api_resolution_summary.json

In [32]:
# ============================================================
# DEFINE GENERIC AND STRUCTURED PROMPTS
# ============================================================

GENERIC_PROMPT = """
Read the following meeting transcript and produce useful meeting notes.

Identify:
- a short meeting summary
- key topics
- decisions
- action items
- owners
- deadlines
- unresolved issues

Return the result clearly and concisely.

MEETING TRANSCRIPT:
{transcript}
"""


STRUCTURED_PROMPT = """
You are analysing a meeting transcript.

Your task is to extract only information that is supported by the transcript.

Follow these rules strictly:

1. A DECISION must only be recorded if participants clearly agreed,
   confirmed, approved, selected, or decided something.

2. Do NOT treat:
   - suggestions
   - possibilities
   - opinions
   - rejected proposals
   - unanswered questions
   as confirmed decisions.

3. An ACTION ITEM must describe a specific task that somebody is expected
   to perform.

4. If an action owner is not explicitly stated, return null.

5. If a deadline is not explicitly stated, return null.

6. Do not invent missing names, dates, deadlines, tasks, decisions,
   responsibilities, or facts.

7. For every decision and action item, provide supporting evidence from
   the transcript.

8. Separate unresolved issues from confirmed decisions.

9. If information is ambiguous, mark it as ambiguous rather than guessing.

Return the following categories:

- meeting_title
- summary
- key_topics
- decisions
- action_items
- unresolved_issues
- ambiguities

Each decision should contain:
- decision
- evidence

Each action item should contain:
- action
- owner
- deadline
- evidence

MEETING TRANSCRIPT:
{transcript}
"""


print("Generic prompt created successfully.")
print("Structured prompt created successfully.")

print("\nGeneric prompt length:")
print(len(GENERIC_PROMPT), "characters")

print("\nStructured prompt length:")
print(len(STRUCTURED_PROMPT), "characters")

print("\nPrompt comparison ready for controlled evaluation.")

Generic prompt created successfully.
Structured prompt created successfully.

Generic prompt length:
267 characters

Structured prompt length:
1249 characters

Prompt comparison ready for controlled evaluation.

In [33]:
# ============================================================
# COMMON OUTPUT SCHEMA FOR BOTH PROMPT CONDITIONS
# ============================================================

from pydantic import BaseModel, Field
from typing import List, Optional


class Decision(BaseModel):
    decision: str
    evidence: Optional[str] = None


class ActionItem(BaseModel):
    action: str
    owner: Optional[str] = None
    deadline: Optional[str] = None
    evidence: Optional[str] = None


class MeetingIntelligence(BaseModel):
    meeting_title: str
    summary: str
    key_topics: List[str]

    decisions: List[Decision] = Field(
        default_factory=list
    )

    action_items: List[ActionItem] = Field(
        default_factory=list
    )

    unresolved_issues: List[str] = Field(
        default_factory=list
    )

    ambiguities: List[str] = Field(
        default_factory=list
    )


print("Common MeetingIntelligence schema created successfully.")

print("\nRequired comparison fields:")
print("- meeting_title")
print("- summary")
print("- key_topics")
print("- decisions")
print("- action_items")
print("- unresolved_issues")
print("- ambiguities")

print("\nDecision fields:")
print("- decision")
print("- evidence")

print("\nAction-item fields:")
print("- action")
print("- owner")
print("- deadline")
print("- evidence")

print("\nSchema ready for generic vs structured comparison.")

Common MeetingIntelligence schema created successfully.

Required comparison fields:
- meeting_title
- summary
- key_topics
- decisions
- action_items
- unresolved_issues
- ambiguities

Decision fields:
- decision
- evidence

Action-item fields:
- action
- owner
- deadline
- evidence

Schema ready for generic vs structured comparison.

In [34]:
# ============================================================
# CONTROLLED GEMINI EXPERIMENT FUNCTION
# Generic vs Structured Prompt
# ============================================================

import json
import time
from datetime import datetime

GEMINI_TEMPERATURE = 0.2


def run_gemini_experiment(
    transcript,
    prompt_type,
    meeting_id,
    run_number=1
):
    """
    Run one controlled Gemini extraction experiment.

    Conditions kept constant:
    - Same Gemini model
    - Same temperature
    - Same transcript
    - Same output schema

    Only the prompt instructions differ.
    """

    if prompt_type not in ["generic", "structured"]:
        raise ValueError(
            "prompt_type must be 'generic' or 'structured'"
        )

    if prompt_type == "generic":
        prompt = GENERIC_PROMPT.format(
            transcript=transcript
        )
    else:
        prompt = STRUCTURED_PROMPT.format(
            transcript=transcript
        )

    print(
        f"Running {prompt_type} prompt | "
        f"Meeting: {meeting_id} | "
        f"Run: {run_number}"
    )

    start_time = time.perf_counter()

    try:

        response = gemini_client.models.generate_content(
            model=GEMINI_MODEL,
            contents=prompt,
            config={
                "temperature": GEMINI_TEMPERATURE,

                "response_format": {
                    "text": {
                        "mime_type": "application/json",
                        "schema": MeetingIntelligence.model_json_schema()
                    }
                }
            }
        )

        latency = time.perf_counter() - start_time

        # Validate returned JSON using Pydantic
        parsed_output = MeetingIntelligence.model_validate_json(
            response.text
        )

        experiment_record = {
            "meeting_id": meeting_id,
            "prompt_type": prompt_type,
            "run_number": run_number,
            "model": GEMINI_MODEL,
            "temperature": GEMINI_TEMPERATURE,
            "status": "SUCCESS",
            "latency_seconds": round(latency, 3),
            "timestamp": datetime.now().isoformat(),
            "error": ""
        }

        print("Status: SUCCESS")
        print(
            "Latency:",
            round(latency, 3),
            "seconds"
        )

        return parsed_output, experiment_record

    except Exception as e:

        latency = time.perf_counter() - start_time

        experiment_record = {
            "meeting_id": meeting_id,
            "prompt_type": prompt_type,
            "run_number": run_number,
            "model": GEMINI_MODEL,
            "temperature": GEMINI_TEMPERATURE,
            "status": "FAILED",
            "latency_seconds": round(latency, 3),
            "timestamp": datetime.now().isoformat(),
            "error": str(e)
        }

        print("Status: FAILED")
        print("Error:", str(e))

        return None, experiment_record


print("Controlled Gemini experiment function created successfully.")
print("Model:", GEMINI_MODEL)
print("Temperature:", GEMINI_TEMPERATURE)
print("Prompt conditions: generic vs structured")
print("Common output schema: MeetingIntelligence")
print("Function has NOT been executed yet.")

Controlled Gemini experiment function created successfully.
Model: gemini-3.6-flash
Temperature: 0.2
Prompt conditions: generic vs structured
Common output schema: MeetingIntelligence
Function has NOT been executed yet.

In [35]:
# ============================================================
# UPDATED CONTROLLED GEMINI EXPERIMENT FUNCTION
# Current Google GenAI structured-output syntax
# ============================================================

import time
from datetime import datetime
from google.genai import types

GEMINI_TEMPERATURE = 0.2


def run_gemini_experiment(
    transcript,
    prompt_type,
    meeting_id,
    run_number=1
):
    """
    Run one controlled Gemini extraction experiment.

    Constant conditions:
    - Same Gemini model
    - Same temperature
    - Same transcript
    - Same Pydantic output schema

    Experimental variable:
    - Generic vs structured prompt
    """

    if prompt_type not in ["generic", "structured"]:
        raise ValueError(
            "prompt_type must be 'generic' or 'structured'"
        )

    if prompt_type == "generic":
        prompt = GENERIC_PROMPT.format(
            transcript=transcript
        )

    else:
        prompt = STRUCTURED_PROMPT.format(
            transcript=transcript
        )

    print(
        f"Running {prompt_type} prompt | "
        f"Meeting: {meeting_id} | "
        f"Run: {run_number}"
    )

    start_time = time.perf_counter()

    try:

        response = gemini_client.models.generate_content(
            model=GEMINI_MODEL,
            contents=prompt,

            config=types.GenerateContentConfig(
                temperature=GEMINI_TEMPERATURE,
                response_mime_type="application/json",
                response_schema=MeetingIntelligence
            )
        )

        latency = time.perf_counter() - start_time

        # Validate/parse structured response
        if getattr(response, "parsed", None) is not None:
            parsed_output = response.parsed
        else:
            parsed_output = (
                MeetingIntelligence.model_validate_json(
                    response.text
                )
            )

        experiment_record = {
            "meeting_id": meeting_id,
            "prompt_type": prompt_type,
            "run_number": run_number,
            "model": GEMINI_MODEL,
            "temperature": GEMINI_TEMPERATURE,
            "status": "SUCCESS",
            "latency_seconds": round(latency, 3),
            "timestamp": datetime.now().isoformat(),
            "http_403": False,
            "http_429": False,
            "error": ""
        }

        print("Status: SUCCESS")
        print(
            "Latency:",
            round(latency, 3),
            "seconds"
        )

        return parsed_output, experiment_record

    except Exception as e:

        latency = time.perf_counter() - start_time

        error_message = str(e)

        experiment_record = {
            "meeting_id": meeting_id,
            "prompt_type": prompt_type,
            "run_number": run_number,
            "model": GEMINI_MODEL,
            "temperature": GEMINI_TEMPERATURE,
            "status": "FAILED",
            "latency_seconds": round(latency, 3),
            "timestamp": datetime.now().isoformat(),

            "http_403": (
                "403" in error_message
                or "PERMISSION_DENIED"
                in error_message.upper()
            ),

            "http_429": (
                "429" in error_message
                or "RESOURCE_EXHAUSTED"
                in error_message.upper()
            ),

            "error": error_message
        }

        print("Status: FAILED")
        print("Error:", error_message)

        return None, experiment_record


print("Updated Gemini experiment function created successfully.")
print("Model:", GEMINI_MODEL)
print("Temperature:", GEMINI_TEMPERATURE)
print("Structured output schema: MeetingIntelligence")
print("403 and 429 errors will be recorded separately.")
print("No Gemini request has been made in this cell.")

Updated Gemini experiment function created successfully.
Model: gemini-3.6-flash
Temperature: 0.2
Structured output schema: MeetingIntelligence
403 and 429 errors will be recorded separately.
No Gemini request has been made in this cell.

In [36]:
# ============================================================
# CREATE GOLD-STANDARD ANNOTATION TEMPLATES FOR M01
# TWO INDEPENDENT HUMAN ANNOTATORS
# ============================================================

import pandas as pd

meeting_id = "M01"

annotation_columns = [
    "meeting_id",
    "annotator_id",
    "item_type",
    "item_number",
    "item_text",
    "owner",
    "deadline",
    "evidence_quote",
    "confidence",
    "notes"
]

template_rows = []

# Allow space for up to 10 decisions
for i in range(1, 11):
    template_rows.append({
        "meeting_id": meeting_id,
        "annotator_id": "",
        "item_type": "decision",
        "item_number": i,
        "item_text": "",
        "owner": "",
        "deadline": "",
        "evidence_quote": "",
        "confidence": "",
        "notes": ""
    })

# Allow space for up to 10 action items
for i in range(1, 11):
    template_rows.append({
        "meeting_id": meeting_id,
        "annotator_id": "",
        "item_type": "action_item",
        "item_number": i,
        "item_text": "",
        "owner": "",
        "deadline": "",
        "evidence_quote": "",
        "confidence": "",
        "notes": ""
    })

annotation_template = pd.DataFrame(
    template_rows,
    columns=annotation_columns
)

# Annotator 1
annotator1_df = annotation_template.copy()
annotator1_df["annotator_id"] = "A1"

annotator1_file = (
    DIRS["annotator_1"] /
    "M01_annotator1.csv"
)

annotator1_df.to_csv(
    annotator1_file,
    index=False
)

# Annotator 2
annotator2_df = annotation_template.copy()
annotator2_df["annotator_id"] = "A2"

annotator2_file = (
    DIRS["annotator_2"] /
    "M01_annotator2.csv"
)

annotator2_df.to_csv(
    annotator2_file,
    index=False
)

print("Gold-standard annotation templates created successfully.")

print("\nAnnotator 1 file:")
print(annotator1_file)

print("\nAnnotator 2 file:")
print(annotator2_file)

print("\nTemplate preview:")
display(annotation_template.head(12))

print("\nIMPORTANT ANNOTATION RULES:")
print("1. Annotators must work independently.")
print("2. Record only confirmed decisions.")
print("3. Do not treat suggestions or possibilities as decisions.")
print("4. Record action items only when a task is actually expected.")
print("5. Record owner only when stated or clearly accepted.")
print("6. Record deadline only when stated.")
print("7. Copy supporting evidence from the transcript.")
print("8. Leave unused rows blank.")

Gold-standard annotation templates created successfully.

Annotator 1 file:
/content/AI_Meeting_Intelligence_Evaluation/gold_standard/annotator_1/M01_annotator1.csv

Annotator 2 file:
/content/AI_Meeting_Intelligence_Evaluation/gold_standard/annotator_2/M01_annotator2.csv

Template preview:

,meeting_id,annotator_id,item_type,item_number,item_text,owner,deadline,evidence_quote,confidence,notes
0,M01,,decision,1,,,,,,
1,M01,,decision,2,,,,,,
2,M01,,decision,3,,,,,,
3,M01,,decision,4,,,,,,
4,M01,,decision,5,,,,,,
5,M01,,decision,6,,,,,,
6,M01,,decision,7,,,,,,
7,M01,,decision,8,,,,,,
8,M01,,decision,9,,,,,,
9,M01,,decision,10,,,,,,
10,M01,,action_item,1,,,,,,
11,M01,,action_item,2,,,,,,

IMPORTANT ANNOTATION RULES:
1. Annotators must work independently.
2. Record only confirmed decisions.
3. Do not treat suggestions or possibilities as decisions.
4. Record action items only when a task is actually expected.
5. Record owner only when stated or clearly accepted.
6. Record deadline only when stated.
7. Copy supporting evidence from the transcript.
8. Leave unused rows blank.

In [37]:
# ============================================================
# CREATE HUMAN ANNOTATION WORKBOOKS FOR M01
# ============================================================

import pandas as pd
from pathlib import Path

meeting_id = "M01"

# ------------------------------------------------------------
# Prepare transcript sheet
# ------------------------------------------------------------

transcript_lines = [
    line.strip()
    for line in reference_text.splitlines()
    if line.strip()
]

transcript_df = pd.DataFrame({
    "line_number": range(1, len(transcript_lines) + 1),
    "transcript_text": transcript_lines
})


# ------------------------------------------------------------
# Annotation instructions
# ------------------------------------------------------------

instructions_df = pd.DataFrame({
    "Instruction": [
        "Read the complete meeting transcript before annotating.",
        "Work independently and do not consult the other annotator.",
        "Record only confirmed decisions.",
        "Do not classify suggestions, possibilities, opinions or rejected proposals as decisions.",
        "Record an action item only when a specific task is expected to be completed.",
        "Record the owner only if the person is explicitly assigned or clearly accepts responsibility.",
        "Record the deadline only if it is explicitly stated.",
        "Copy a supporting evidence quotation from the transcript.",
        "Use one row for each decision or action item.",
        "Leave unused rows blank.",
        "Confidence should be entered from 1 to 5, where 5 means very certain."
    ]
})


def create_annotation_workbook(
    annotator_id,
    output_folder
):

    annotation_df = annotation_template.copy()

    annotation_df["annotator_id"] = annotator_id

    output_file = (
        output_folder /
        f"M01_{annotator_id}_Gold_Standard_Annotation.xlsx"
    )

    with pd.ExcelWriter(
        output_file,
        engine="openpyxl"
    ) as writer:

        instructions_df.to_excel(
            writer,
            sheet_name="Instructions",
            index=False
        )

        transcript_df.to_excel(
            writer,
            sheet_name="Transcript",
            index=False
        )

        annotation_df.to_excel(
            writer,
            sheet_name="Annotations",
            index=False
        )

    return output_file


annotator1_workbook = create_annotation_workbook(
    "A1",
    DIRS["annotator_1"]
)

annotator2_workbook = create_annotation_workbook(
    "A2",
    DIRS["annotator_2"]
)


print("Human annotation workbooks created successfully.")

print("\nAnnotator 1 workbook:")
print(annotator1_workbook)

print("\nAnnotator 2 workbook:")
print(annotator2_workbook)

print("\nTranscript lines included:", len(transcript_df))

print("\nWorkbook sheets:")
print("1. Instructions")
print("2. Transcript")
print("3. Annotations")

print(
    "\nIMPORTANT: A1 and A2 must complete their workbooks independently."
)

Human annotation workbooks created successfully.

Annotator 1 workbook:
/content/AI_Meeting_Intelligence_Evaluation/gold_standard/annotator_1/M01_A1_Gold_Standard_Annotation.xlsx

Annotator 2 workbook:
/content/AI_Meeting_Intelligence_Evaluation/gold_standard/annotator_2/M01_A2_Gold_Standard_Annotation.xlsx

Transcript lines included: 50

Workbook sheets:
1. Instructions
2. Transcript
3. Annotations

IMPORTANT: A1 and A2 must complete their workbooks independently.

In [38]:
# ============================================================
# PACKAGE AND DOWNLOAD M01 HUMAN ANNOTATION WORKBOOKS
# ============================================================

import zipfile
from google.colab import files

annotation_package = (
    PROJECT_ROOT /
    "M01_Human_Annotation_Package.zip"
)

with zipfile.ZipFile(
    annotation_package,
    "w",
    zipfile.ZIP_DEFLATED
) as zipf:

    zipf.write(
        annotator1_workbook,
        arcname="M01_A1_Gold_Standard_Annotation.xlsx"
    )

    zipf.write(
        annotator2_workbook,
        arcname="M01_A2_Gold_Standard_Annotation.xlsx"
    )

print("M01 annotation package created successfully.")
print("Package:", annotation_package)

print("\nFiles included:")
print("1. M01_A1_Gold_Standard_Annotation.xlsx")
print("2. M01_A2_Gold_Standard_Annotation.xlsx")

print(
    "\nIMPORTANT: Give A1 and A2 to two different human annotators. "
    "They must complete them independently."
)

files.download(str(annotation_package))

M01 annotation package created successfully.
Package: /content/AI_Meeting_Intelligence_Evaluation/M01_Human_Annotation_Package.zip

Files included:
1. M01_A1_Gold_Standard_Annotation.xlsx
2. M01_A2_Gold_Standard_Annotation.xlsx

IMPORTANT: Give A1 and A2 to two different human annotators. They must complete them independently.

In [39]:
# ============================================================
# IMPORT COMPLETED HUMAN ANNOTATION WORKBOOK
# ============================================================

from google.colab import files
import pandas as pd
from pathlib import Path


def import_completed_annotation(annotator_id):
    """
    Import a completed M01 human annotation workbook.

    annotator_id must be:
    A1 or A2
    """

    if annotator_id not in ["A1", "A2"]:
        raise ValueError(
            "annotator_id must be 'A1' or 'A2'"
        )

    print(
        f"Ready to import completed annotation workbook for {annotator_id}."
    )

    uploaded = files.upload()

    if len(uploaded) != 1:
        print(
            "ERROR: Please upload exactly one completed Excel workbook."
        )
        return None

    uploaded_name = list(uploaded.keys())[0]

    if not uploaded_name.lower().endswith(".xlsx"):
        print(
            "ERROR: The completed annotation file must be an .xlsx workbook."
        )
        return None

    # Read annotation sheet
    completed_df = pd.read_excel(
        uploaded_name,
        sheet_name="Annotations"
    )

    required_columns = [
        "meeting_id",
        "annotator_id",
        "item_type",
        "item_number",
        "item_text",
        "owner",
        "deadline",
        "evidence_quote",
        "confidence",
        "notes"
    ]

    missing_columns = [
        col
        for col in required_columns
        if col not in completed_df.columns
    ]

    if missing_columns:
        print("ERROR: Required columns are missing:")
        print(missing_columns)
        return None

    # Keep only rows containing an actual annotation
    completed_items = completed_df[
        completed_df["item_text"].notna()
        &
        (
            completed_df["item_text"]
            .astype(str)
            .str.strip()
            != ""
        )
    ].copy()

    # Correct annotator identifier
    completed_items["annotator_id"] = annotator_id

    # Save completed annotation data
    if annotator_id == "A1":
        destination_folder = DIRS["annotator_1"]
    else:
        destination_folder = DIRS["annotator_2"]

    output_file = (
        destination_folder /
        f"M01_{annotator_id}_completed.csv"
    )

    completed_items.to_csv(
        output_file,
        index=False
    )

    print("\nCompleted annotation imported successfully.")
    print("Annotator:", annotator_id)
    print("Number of labelled items:", len(completed_items))

    print("\nDecision count:")
    print(
        (
            completed_items["item_type"]
            == "decision"
        ).sum()
    )

    print("\nAction-item count:")
    print(
        (
            completed_items["item_type"]
            == "action_item"
        ).sum()
    )

    print("\nSaved file:")
    print(output_file)

    return completed_items


print("Completed-annotation import function created successfully.")
print("Supported annotators: A1 and A2")
print("No annotation file has been uploaded yet.")

Completed-annotation import function created successfully.
Supported annotators: A1 and A2
No annotation file has been uploaded yet.

In [40]:
# ============================================================
# HUMAN ANNOTATOR AGREEMENT AND CONSENSUS FUNCTION
# ============================================================

from difflib import SequenceMatcher
import pandas as pd


def text_similarity(text1, text2):
    """
    Calculate simple text similarity between two annotations.
    Returns a score between 0 and 1.
    """

    text1 = str(text1).lower().strip()
    text2 = str(text2).lower().strip()

    return SequenceMatcher(
        None,
        text1,
        text2
    ).ratio()


def compare_annotators(
    annotator1_data,
    annotator2_data,
    similarity_threshold=0.70
):
    """
    Compare A1 and A2 decisions/action items.

    Items with similarity >= threshold are considered
    provisional matches for later human consensus review.
    """

    comparison_rows = []

    for item_type in ["decision", "action_item"]:

        a1_items = annotator1_data[
            annotator1_data["item_type"] == item_type
        ]

        a2_items = annotator2_data[
            annotator2_data["item_type"] == item_type
        ]

        matched_a2 = set()

        for _, row1 in a1_items.iterrows():

            best_match = None
            best_similarity = 0
            best_index = None

            for index2, row2 in a2_items.iterrows():

                if index2 in matched_a2:
                    continue

                similarity = text_similarity(
                    row1["item_text"],
                    row2["item_text"]
                )

                if similarity > best_similarity:
                    best_similarity = similarity
                    best_match = row2
                    best_index = index2

            if (
                best_match is not None
                and best_similarity >= similarity_threshold
            ):

                matched_a2.add(best_index)

                comparison_rows.append({
                    "item_type": item_type,
                    "annotator1_text": row1["item_text"],
                    "annotator2_text": best_match["item_text"],
                    "text_similarity": round(best_similarity, 3),
                    "provisional_agreement": True,
                    "consensus_text": "",
                    "consensus_owner": "",
                    "consensus_deadline": "",
                    "consensus_evidence": ""
                })

            else:

                comparison_rows.append({
                    "item_type": item_type,
                    "annotator1_text": row1["item_text"],
                    "annotator2_text": "",
                    "text_similarity": round(best_similarity, 3),
                    "provisional_agreement": False,
                    "consensus_text": "",
                    "consensus_owner": "",
                    "consensus_deadline": "",
                    "consensus_evidence": ""
                })

        # Add unmatched A2 items
        for index2, row2 in a2_items.iterrows():

            if index2 not in matched_a2:

                comparison_rows.append({
                    "item_type": item_type,
                    "annotator1_text": "",
                    "annotator2_text": row2["item_text"],
                    "text_similarity": 0.0,
                    "provisional_agreement": False,
                    "consensus_text": "",
                    "consensus_owner": "",
                    "consensus_deadline": "",
                    "consensus_evidence": ""
                })

    comparison_df = pd.DataFrame(comparison_rows)

    if len(comparison_df) > 0:

        agreement_rate = (
            comparison_df["provisional_agreement"].mean()
        )

        print("Annotator comparison completed.")
        print(
            "Provisional agreement rate:",
            round(agreement_rate * 100, 2),
            "%"
        )

    else:
        print("No annotations available for comparison.")

    return comparison_df


print("Annotator comparison function created successfully.")
print("Similarity threshold: 0.70")
print("A1 and A2 files are NOT compared yet.")
print("Consensus must still be confirmed by a human reviewer.")

Annotator comparison function created successfully.
Similarity threshold: 0.70
A1 and A2 files are NOT compared yet.
Consensus must still be confirmed by a human reviewer.

In [41]:
# ============================================================
# HUMAN EVALUATION RATING TEMPLATE
# Accuracy, Completeness, Clarity, Usefulness
# ============================================================

import pandas as pd

HUMAN_RATING_DIMENSIONS = [
    "accuracy",
    "completeness",
    "clarity",
    "usefulness"
]

HUMAN_RATING_SCALE = {
    1: "Very Poor",
    2: "Poor",
    3: "Acceptable",
    4: "Good",
    5: "Excellent"
}

human_evaluation_rows = []

# Two evaluators
for evaluator_id in ["H1", "H2"]:

    # Generic and structured conditions
    for prompt_type in ["generic", "structured"]:

        human_evaluation_rows.append({
            "meeting_id": "M01",
            "evaluator_id": evaluator_id,
            "prompt_type": prompt_type,
            "accuracy": "",
            "completeness": "",
            "clarity": "",
            "usefulness": "",
            "overall_comments": ""
        })

human_evaluation_template = pd.DataFrame(
    human_evaluation_rows
)

human_evaluation_file = (
    DIRS["human_results"] /
    "M01_human_evaluation_template.csv"
)

human_evaluation_template.to_csv(
    human_evaluation_file,
    index=False
)

print("Human evaluation template created successfully.")

print("\nEvaluation dimensions:")
for dimension in HUMAN_RATING_DIMENSIONS:
    print("-", dimension)

print("\nRating scale:")
for score, meaning in HUMAN_RATING_SCALE.items():
    print(f"{score} = {meaning}")

print("\nPlanned evaluators: H1 and H2")
print("Prompt conditions: Generic and Structured")

print("\nTemplate preview:")
display(human_evaluation_template)

print("\nSaved file:")
print(human_evaluation_file)

Human evaluation template created successfully.

Evaluation dimensions:
- accuracy
- completeness
- clarity
- usefulness

Rating scale:
1 = Very Poor
2 = Poor
3 = Acceptable
4 = Good
5 = Excellent

Planned evaluators: H1 and H2
Prompt conditions: Generic and Structured

Template preview:

,meeting_id,evaluator_id,prompt_type,accuracy,completeness,clarity,usefulness,overall_comments
0,M01,H1,generic,,,,,
1,M01,H1,structured,,,,,
2,M01,H2,generic,,,,,
3,M01,H2,structured,,,,,

Saved file:
/content/AI_Meeting_Intelligence_Evaluation/evaluation/human/M01_human_evaluation_template.csv

In [42]:
# ============================================================
# TIME-SAVING EVALUATION TEMPLATE
# Manual Note-Taking vs AI-Assisted Processing
# ============================================================

import pandas as pd

time_saving_template = pd.DataFrame([
    {
        "meeting_id": "M01",
        "human_participant_id": "T1",
        "manual_note_preparation_seconds": "",
        "ai_transcription_seconds": round(transcription_time, 3),
        "ai_llm_processing_seconds": "",
        "human_review_seconds": "",
        "total_ai_assisted_seconds": "",
        "net_time_saved_seconds": "",
        "percentage_time_saved": "",
        "notes": ""
    },
    {
        "meeting_id": "M01",
        "human_participant_id": "T2",
        "manual_note_preparation_seconds": "",
        "ai_transcription_seconds": round(transcription_time, 3),
        "ai_llm_processing_seconds": "",
        "human_review_seconds": "",
        "total_ai_assisted_seconds": "",
        "net_time_saved_seconds": "",
        "percentage_time_saved": "",
        "notes": ""
    }
])

time_saving_file = (
    DIRS["time_results"] /
    "M01_time_saving_template.csv"
)

time_saving_template.to_csv(
    time_saving_file,
    index=False
)

print("Time-saving evaluation template created successfully.")

print("\nCurrent measured Whisper transcription time:")
print(round(transcription_time, 3), "seconds")

print("\nPlanned human participants:")
print("- T1")
print("- T2")

print("\nRequired measurements:")
print("1. Manual preparation time")
print("2. AI transcription time")
print("3. Gemini processing time")
print("4. Human review/correction time")
print("5. Total AI-assisted time")
print("6. Net time saved")
print("7. Percentage time saved")

print("\nTemplate preview:")
display(time_saving_template)

print("\nSaved file:")
print(time_saving_file)

Time-saving evaluation template created successfully.

Current measured Whisper transcription time:
24.352 seconds

Planned human participants:
- T1
- T2

Required measurements:
1. Manual preparation time
2. AI transcription time
3. Gemini processing time
4. Human review/correction time
5. Total AI-assisted time
6. Net time saved
7. Percentage time saved

Template preview:

,meeting_id,human_participant_id,manual_note_preparation_seconds,ai_transcription_seconds,ai_llm_processing_seconds,human_review_seconds,total_ai_assisted_seconds,net_time_saved_seconds,percentage_time_saved,notes
0,M01,T1,,24.352,,,,,,
1,M01,T2,,24.352,,,,,,

Saved file:
/content/AI_Meeting_Intelligence_Evaluation/evaluation/time_saving/M01_time_saving_template.csv

In [43]:
# ============================================================
# DESIGNED vs IMPLEMENTED vs TESTED vs DEMONSTRATED MATRIX
# ============================================================

import pandas as pd

implementation_matrix = pd.DataFrame([
    {
        "system_component": "Audio file input",
        "designed": "Yes",
        "implemented": "Yes",
        "tested": "Yes",
        "successfully_demonstrated": "Yes",
        "current_evidence": "M01 MP3 uploaded and processed successfully",
        "current_limitation": "Only M01 has been experimentally processed so far"
    },

    {
        "system_component": "Whisper speech transcription",
        "designed": "Yes",
        "implemented": "Yes",
        "tested": "Yes",
        "successfully_demonstrated": "Yes",
        "current_evidence": (
            "M01 transcribed using Whisper small.en on Tesla T4; "
            "WER = 2.82%; CER = 0.89%"
        ),
        "current_limitation": (
            "Accuracy must still be evaluated across the remaining dataset"
        )
    },

    {
        "system_component": "Reference transcript comparison",
        "designed": "Yes",
        "implemented": "Yes",
        "tested": "Yes",
        "successfully_demonstrated": "Yes",
        "current_evidence": (
            "M01 human/reference transcript compared with Whisper output"
        ),
        "current_limitation": (
            "Only one completed ASR comparison currently available"
        )
    },

    {
        "system_component": "Generic prompting",
        "designed": "Yes",
        "implemented": "Yes",
        "tested": "No",
        "successfully_demonstrated": "No",
        "current_evidence": "Generic prompt and common schema implemented",
        "current_limitation": (
            "Controlled Gemini experiment has not yet been completed"
        )
    },

    {
        "system_component": "Structured prompting",
        "designed": "Yes",
        "implemented": "Yes",
        "tested": "Partially",
        "successfully_demonstrated": "Partially",
        "current_evidence": (
            "Prompt implemented; Gemini connectivity successfully demonstrated"
        ),
        "current_limitation": (
            "Full dataset extraction evaluation not yet completed"
        )
    },

    {
        "system_component": "Gemini API",
        "designed": "Yes",
        "implemented": "Yes",
        "tested": "Yes",
        "successfully_demonstrated": "Yes",
        "current_evidence": (
            "Successful gemini-3.6-flash API request; "
            "previous 403 not reproduced"
        ),
        "current_limitation": (
            "Repeated testing currently affected by free-tier 429 quota"
        )
    },

    {
        "system_component": "Pydantic structured validation",
        "designed": "Yes",
        "implemented": "Yes",
        "tested": "Partially",
        "successfully_demonstrated": "Partially",
        "current_evidence": (
            "MeetingIntelligence schema defined for controlled experiments"
        ),
        "current_limitation": (
            "Must be evaluated on completed generic and structured outputs"
        )
    },

    {
        "system_component": "Gold-standard evaluation",
        "designed": "Yes",
        "implemented": "Yes",
        "tested": "Not yet",
        "successfully_demonstrated": "No",
        "current_evidence": (
            "Independent A1 and A2 annotation workbooks created"
        ),
        "current_limitation": (
            "Completed human annotations are still required"
        )
    },

    {
        "system_component": "Precision, Recall and F1 evaluation",
        "designed": "Yes",
        "implemented": "In progress",
        "tested": "No",
        "successfully_demonstrated": "No",
        "current_evidence": (
            "Evaluation framework and gold-standard workflow prepared"
        ),
        "current_limitation": (
            "Requires consensus gold standard and Gemini predictions"
        )
    },

    {
        "system_component": "Human output evaluation",
        "designed": "Yes",
        "implemented": "Yes",
        "tested": "No",
        "successfully_demonstrated": "No",
        "current_evidence": (
            "Accuracy, completeness, clarity and usefulness template created"
        ),
        "current_limitation": (
            "Human ratings have not yet been collected"
        )
    },

    {
        "system_component": "Time-saving evaluation",
        "designed": "Yes",
        "implemented": "Yes",
        "tested": "Partially",
        "successfully_demonstrated": "No",
        "current_evidence": (
            "Whisper time measured at 24.352 seconds; "
            "manual/LLM/review timing template created"
        ),
        "current_limitation": (
            "Manual note preparation and review times still need measurement"
        )
    }
])

implementation_matrix_file = (
    DIRS["tables"] /
    "designed_implemented_tested_demonstrated.csv"
)

implementation_matrix.to_csv(
    implementation_matrix_file,
    index=False
)

print(
    "Designed/Implemented/Tested/Demonstrated matrix created successfully."
)

print("\nCurrent system evidence matrix:\n")

display(implementation_matrix)

print("\nSaved file:")
print(implementation_matrix_file)

print(
    "\nIMPORTANT: This table records the CURRENT evidence only. "
    "Statuses will be updated as additional experiments are completed."
)

Designed/Implemented/Tested/Demonstrated matrix created successfully.

Current system evidence matrix:

,system_component,designed,implemented,tested,successfully_demonstrated,current_evidence,current_limitation
0,Audio file input,Yes,Yes,Yes,Yes,M01 MP3 uploaded and processed successfully,Only M01 has been experimentally processed so far
1,Whisper speech transcription,Yes,Yes,Yes,Yes,M01 transcribed using Whisper small.en on Tesl...,Accuracy must still be evaluated across the re...
2,Reference transcript comparison,Yes,Yes,Yes,Yes,M01 human/reference transcript compared with W...,Only one completed ASR comparison currently av...
3,Generic prompting,Yes,Yes,No,No,Generic prompt and common schema implemented,Controlled Gemini experiment has not yet been ...
4,Structured prompting,Yes,Yes,Partially,Partially,Prompt implemented; Gemini connectivity succes...,Full dataset extraction evaluation not yet com...
5,Gemini API,Yes,Yes,Yes,Yes,Successful gemini-3.6-flash API request; previ...,Repeated testing currently affected by free-ti...
6,Pydantic structured validation,Yes,Yes,Partially,Partially,MeetingIntelligence schema defined for control...,Must be evaluated on completed generic and str...
7,Gold-standard evaluation,Yes,Yes,Not yet,No,Independent A1 and A2 annotation workbooks cre...,Completed human annotations are still required
8,"Precision, Recall and F1 evaluation",Yes,In progress,No,No,Evaluation framework and gold-standard workflo...,Requires consensus gold standard and Gemini pr...
9,Human output evaluation,Yes,Yes,No,No,"Accuracy, completeness, clarity and usefulness...",Human ratings have not yet been collected
10,Time-saving evaluation,Yes,Yes,Partially,No,Whisper time measured at 24.352 seconds; manua...,Manual note preparation and review times still...

Saved file:
/content/AI_Meeting_Intelligence_Evaluation/results/tables/designed_implemented_tested_demonstrated.csv

IMPORTANT: This table records the CURRENT evidence only. Statuses will be updated as additional experiments are completed.

In [44]:
# ============================================================
# EXTRACTION ACCURACY METRIC CALCULATOR
# Precision, Recall, F1, Hallucination,
# Owner Accuracy and Deadline Accuracy
# ============================================================

import pandas as pd


def calculate_extraction_metrics(
    meeting_id,
    prompt_type,
    run_number,
    item_type,
    true_positives,
    false_positives,
    false_negatives,
    owner_correct=0,
    owner_evaluable=0,
    deadline_correct=0,
    deadline_evaluable=0
):
    """
    Calculate extraction performance against the
    human-consensus gold standard.

    TP = AI item correctly matches gold standard
    FP = AI generated unsupported/incorrect item
    FN = Gold-standard item missed by AI
    """

    # --------------------------------------------------------
    # Precision
    # --------------------------------------------------------

    if (true_positives + false_positives) > 0:
        precision = (
            true_positives /
            (true_positives + false_positives)
        )
    else:
        precision = 0.0

    # --------------------------------------------------------
    # Recall
    # --------------------------------------------------------

    if (true_positives + false_negatives) > 0:
        recall = (
            true_positives /
            (true_positives + false_negatives)
        )
    else:
        recall = 0.0

    # --------------------------------------------------------
    # F1 Score
    # --------------------------------------------------------

    if (precision + recall) > 0:
        f1 = (
            2 * precision * recall /
            (precision + recall)
        )
    else:
        f1 = 0.0

    # --------------------------------------------------------
    # Hallucination Rate
    # FP / all AI-generated items
    # --------------------------------------------------------

    generated_items = (
        true_positives +
        false_positives
    )

    if generated_items > 0:
        hallucination_rate = (
            false_positives /
            generated_items
        )
    else:
        hallucination_rate = 0.0

    # --------------------------------------------------------
    # Owner Accuracy
    # --------------------------------------------------------

    if owner_evaluable > 0:
        owner_accuracy = (
            owner_correct /
            owner_evaluable
        )
    else:
        owner_accuracy = None

    # --------------------------------------------------------
    # Deadline Accuracy
    # --------------------------------------------------------

    if deadline_evaluable > 0:
        deadline_accuracy = (
            deadline_correct /
            deadline_evaluable
        )
    else:
        deadline_accuracy = None

    result = {
        "meeting_id": meeting_id,
        "prompt_type": prompt_type,
        "run_number": run_number,
        "item_type": item_type,

        "true_positives": true_positives,
        "false_positives": false_positives,
        "false_negatives": false_negatives,

        "precision": round(precision, 4),
        "recall": round(recall, 4),
        "f1_score": round(f1, 4),

        "hallucination_rate": round(
            hallucination_rate,
            4
        ),

        "owner_correct": owner_correct,
        "owner_evaluable": owner_evaluable,

        "owner_accuracy": (
            round(owner_accuracy, 4)
            if owner_accuracy is not None
            else None
        ),

        "deadline_correct": deadline_correct,
        "deadline_evaluable": deadline_evaluable,

        "deadline_accuracy": (
            round(deadline_accuracy, 4)
            if deadline_accuracy is not None
            else None
        )
    }

    return result


print("Extraction metric calculator created successfully.")

print("\nMetrics supported:")
print("- Precision")
print("- Recall")
print("- F1 score")
print("- Hallucination rate")
print("- Owner accuracy")
print("- Deadline accuracy")

print(
    "\nIMPORTANT: TP, FP and FN must be determined "
    "against the human-consensus gold standard."
)

print(
    "No experimental metric values have been calculated yet."
)

Extraction metric calculator created successfully.

Metrics supported:
- Precision
- Recall
- F1 score
- Hallucination rate
- Owner accuracy
- Deadline accuracy

IMPORTANT: TP, FP and FN must be determined against the human-consensus gold standard.
No experimental metric values have been calculated yet.

In [46]:
# ============================================================
# ADD MISSING COMMERCIAL COMPARISON DIRECTORY
# ============================================================

DIRS["commercial_comparison"] = (
    PROJECT_ROOT /
    "evaluation" /
    "commercial_tools"
)

DIRS["commercial_comparison"].mkdir(
    parents=True,
    exist_ok=True
)

print("Commercial comparison directory added successfully.")
print("Directory:")
print(DIRS["commercial_comparison"])
print("Exists:", DIRS["commercial_comparison"].exists())

Commercial comparison directory added successfully.
Directory:
/content/AI_Meeting_Intelligence_Evaluation/evaluation/commercial_tools
Exists: True

In [47]:
# ============================================================
# COMMERCIAL MEETING TOOL COMPARISON FRAMEWORK
# ============================================================

import pandas as pd

commercial_tools_comparison = pd.DataFrame([
    {
        "tool": "AI Meeting Intelligence System (AIMIS)",
        "transcription": "",
        "meeting_summary": "",
        "decision_extraction": "",
        "action_item_extraction": "",
        "owner_extraction": "",
        "deadline_extraction": "",
        "evidence_quotes": "",
        "structured_json_output": "",
        "human_review_support": "",
        "custom_prompt_control": "",
        "local_audio_processing": "",
        "privacy_considerations": "",
        "deployment_control": "",
        "cost_model": "",
        "main_strengths": "",
        "main_limitations": "",
        "design_influence_on_aimis": ""
    },
    {
        "tool": "Otter.ai",
        "transcription": "",
        "meeting_summary": "",
        "decision_extraction": "",
        "action_item_extraction": "",
        "owner_extraction": "",
        "deadline_extraction": "",
        "evidence_quotes": "",
        "structured_json_output": "",
        "human_review_support": "",
        "custom_prompt_control": "",
        "local_audio_processing": "",
        "privacy_considerations": "",
        "deployment_control": "",
        "cost_model": "",
        "main_strengths": "",
        "main_limitations": "",
        "design_influence_on_aimis": ""
    },
    {
        "tool": "Fireflies.ai",
        "transcription": "",
        "meeting_summary": "",
        "decision_extraction": "",
        "action_item_extraction": "",
        "owner_extraction": "",
        "deadline_extraction": "",
        "evidence_quotes": "",
        "structured_json_output": "",
        "human_review_support": "",
        "custom_prompt_control": "",
        "local_audio_processing": "",
        "privacy_considerations": "",
        "deployment_control": "",
        "cost_model": "",
        "main_strengths": "",
        "main_limitations": "",
        "design_influence_on_aimis": ""
    },
    {
        "tool": "Zoom AI Companion",
        "transcription": "",
        "meeting_summary": "",
        "decision_extraction": "",
        "action_item_extraction": "",
        "owner_extraction": "",
        "deadline_extraction": "",
        "evidence_quotes": "",
        "structured_json_output": "",
        "human_review_support": "",
        "custom_prompt_control": "",
        "local_audio_processing": "",
        "privacy_considerations": "",
        "deployment_control": "",
        "cost_model": "",
        "main_strengths": "",
        "main_limitations": "",
        "design_influence_on_aimis": ""
    },
    {
        "tool": "Microsoft Copilot",
        "transcription": "",
        "meeting_summary": "",
        "decision_extraction": "",
        "action_item_extraction": "",
        "owner_extraction": "",
        "deadline_extraction": "",
        "evidence_quotes": "",
        "structured_json_output": "",
        "human_review_support": "",
        "custom_prompt_control": "",
        "local_audio_processing": "",
        "privacy_considerations": "",
        "deployment_control": "",
        "cost_model": "",
        "main_strengths": "",
        "main_limitations": "",
        "design_influence_on_aimis": ""
    }
])

commercial_tools_file = (
    DIRS["commercial_comparison"] /
    "commercial_meeting_tools_comparison.csv"
)

commercial_tools_comparison.to_csv(
    commercial_tools_file,
    index=False
)

print("Commercial meeting-tool comparison framework created successfully.")

print("\nTools included:")
for tool in commercial_tools_comparison["tool"]:
    print("-", tool)

print("\nTemplate preview:")
display(commercial_tools_comparison)

print("\nSaved file:")
print(commercial_tools_file)

print(
    "\nIMPORTANT: The cells are intentionally blank. "
    "Current capabilities will be filled only after checking reliable sources."
)

Commercial meeting-tool comparison framework created successfully.

Tools included:
- AI Meeting Intelligence System (AIMIS)
- Otter.ai
- Fireflies.ai
- Zoom AI Companion
- Microsoft Copilot

Template preview:

,tool,transcription,meeting_summary,decision_extraction,action_item_extraction,owner_extraction,deadline_extraction,evidence_quotes,structured_json_output,human_review_support,custom_prompt_control,local_audio_processing,privacy_considerations,deployment_control,cost_model,main_strengths,main_limitations,design_influence_on_aimis
0,AI Meeting Intelligence System (AIMIS),,,,,,,,,,,,,,,,,
1,Otter.ai,,,,,,,,,,,,,,,,,
2,Fireflies.ai,,,,,,,,,,,,,,,,,
3,Zoom AI Companion,,,,,,,,,,,,,,,,,
4,Microsoft Copilot,,,,,,,,,,,,,,,,,

Saved file:
/content/AI_Meeting_Intelligence_Evaluation/evaluation/commercial_tools/commercial_meeting_tools_comparison.csv

IMPORTANT: The cells are intentionally blank. Current capabilities will be filled only after checking reliable sources.

In [48]:
# ============================================================
# POPULATE VERIFIED COMMERCIAL TOOL COMPARISON
# Information checked against official product/support sources
# ============================================================

commercial_tools_comparison = pd.DataFrame([
    {
        "tool": "AI Meeting Intelligence System (AIMIS)",
        "transcription": "Yes - Whisper",
        "meeting_summary": "Yes",
        "decision_extraction": "Yes - explicit structured field",
        "action_item_extraction": "Yes - explicit structured field",
        "owner_extraction": "Yes - null allowed if unsupported",
        "deadline_extraction": "Yes - null allowed if unsupported",
        "evidence_quotes": "Yes - designed as evidence field",
        "structured_json_output": "Yes - Pydantic validated JSON",
        "human_review_support": "Yes - transcript and output review",
        "custom_prompt_control": "Yes - researcher controlled",
        "local_audio_processing": (
            "Yes/Controlled - Whisper can process audio "
            "without a commercial transcription service"
        ),
        "privacy_considerations": (
            "Audio transcription can remain under researcher control; "
            "LLM transcript processing uses Gemini API"
        ),
        "deployment_control": "High - Python/Colab/Streamlit controlled",
        "cost_model": (
            "Open-source Whisper plus Gemini API usage/quota"
        ),
        "main_strengths": (
            "Transparent schema, evidence fields, controllable prompts, "
            "gold-standard evaluation design"
        ),
        "main_limitations": (
            "Prototype; limited completed dataset; Gemini quota dependency"
        ),
        "design_influence_on_aimis": (
            "Reference system being evaluated"
        ),
        "verification_basis": (
            "Implemented AIMIS artefact and current experimental notebook"
        )
    },

    {
        "tool": "Otter.ai",
        "transcription": "Yes",
        "meeting_summary": "Yes",
        "decision_extraction": "Yes - available in Insights/templates",
        "action_item_extraction": "Yes",
        "owner_extraction": (
            "Yes - action items can be assigned to participants"
        ),
        "deadline_extraction": (
            "Partial - due-date workflows are supported, "
            "but not documented as a universal explicit extraction field"
        ),
        "evidence_quotes": (
            "Partial - meeting transcript/context is retained, "
            "but per-item evidence quotation is not a standard required field"
        ),
        "structured_json_output": (
            "Partial - integrations/webhooks expose structured "
            "conversation information"
        ),
        "human_review_support": "Yes - summaries/transcripts can be reviewed",
        "custom_prompt_control": (
            "Yes - custom prompts and customizable meeting templates"
        ),
        "local_audio_processing": "No - primarily cloud/SaaS processing",
        "privacy_considerations": (
            "Enterprise security, governance and compliance controls available"
        ),
        "deployment_control": "Low - vendor-hosted SaaS",
        "cost_model": "Free and paid subscription tiers/features",
        "main_strengths": (
            "Mature transcription, summaries, decisions, action items, "
            "templates and workflow integrations"
        ),
        "main_limitations": (
            "Less researcher control over underlying extraction model "
            "and evaluation logic than AIMIS"
        ),
        "design_influence_on_aimis": (
            "Motivated explicit structured outputs while AIMIS adds "
            "transparent evidence and experimental evaluation"
        ),
        "verification_basis": (
            "Official Otter product and Help Center documentation"
        )
    },

    {
        "tool": "Fireflies.ai",
        "transcription": "Yes",
        "meeting_summary": "Yes",
        "decision_extraction": (
            "Yes - decisions can appear in AI meeting summaries"
        ),
        "action_item_extraction": "Yes",
        "owner_extraction": (
            "Yes - action items can be associated with participants"
        ),
        "deadline_extraction": (
            "Not clearly documented as a mandatory structured field"
        ),
        "evidence_quotes": (
            "Partial - full transcript, timestamps and speaker labels "
            "are available; explicit evidence per extracted item is not required"
        ),
        "structured_json_output": (
            "Partial - transcript/summary downloads include JSON options"
        ),
        "human_review_support": (
            "Yes - users can review, edit, share and manage meeting notes"
        ),
        "custom_prompt_control": (
            "Yes - customizable summaries/templates and AI prompts"
        ),
        "local_audio_processing": "No - primarily vendor cloud processing",
        "privacy_considerations": (
            "Official materials state security/compliance controls "
            "including encryption and enterprise protections"
        ),
        "deployment_control": "Low - vendor-hosted SaaS",
        "cost_model": "Free and paid subscription tiers/features",
        "main_strengths": (
            "Transcription, speaker recognition, summaries, action items, "
            "custom templates and integrations"
        ),
        "main_limitations": (
            "Underlying extraction process is less experimentally transparent "
            "than a researcher-controlled pipeline"
        ),
        "design_influence_on_aimis": (
            "Encouraged action-oriented meeting outputs; AIMIS additionally "
            "requires explicit evidence and controlled evaluation"
        ),
        "verification_basis": (
            "Official Fireflies product and Help Center documentation"
        )
    },

    {
        "tool": "Zoom AI (formerly AI Companion)",
        "transcription": "Yes - Zoom speech-to-text/transcript features",
        "meeting_summary": "Yes",
        "decision_extraction": (
            "Partial - decisions can be represented in summaries/templates, "
            "but are not always a dedicated universal output field"
        ),
        "action_item_extraction": (
            "Yes - meeting-summary templates support next steps/action items"
        ),
        "owner_extraction": (
            "Not clearly documented as a universal structured field"
        ),
        "deadline_extraction": (
            "Not clearly documented as a universal structured field"
        ),
        "evidence_quotes": (
            "Not a standard required per-decision/action evidence field"
        ),
        "structured_json_output": (
            "Not a standard end-user meeting-summary output"
        ),
        "human_review_support": (
            "Yes - generated summaries can be reviewed and edited"
        ),
        "custom_prompt_control": (
            "Partial - configurable meeting-summary templates are available"
        ),
        "local_audio_processing": "No - Zoom platform processing",
        "privacy_considerations": (
            "AI processing governed through Zoom account/admin settings "
            "and documented data-handling controls"
        ),
        "deployment_control": "Low - Zoom Workplace platform",
        "cost_model": "Account/plan and feature dependent",
        "main_strengths": (
            "Integrated directly into Zoom meetings with summaries, "
            "next steps and customizable templates"
        ),
        "main_limitations": (
            "Less control over the underlying model and no required "
            "evidence-linked structured decision/action schema"
        ),
        "design_influence_on_aimis": (
            "Motivated convenient meeting summaries while AIMIS focuses "
            "on transparent extraction and evidence-linked outputs"
        ),
        "verification_basis": (
            "Official Zoom Support documentation, checked September 2026"
        )
    },

    {
        "tool": "Microsoft Copilot in Teams",
        "transcription": (
            "Teams supports meeting transcription; transcript enables "
            "post-meeting Copilot analysis"
        ),
        "meeting_summary": "Yes",
        "decision_extraction": (
            "Yes/Partial - Copilot can identify key decisions from meeting context"
        ),
        "action_item_extraction": (
            "Yes - Copilot suggests and summarizes action items"
        ),
        "owner_extraction": (
            "Partial - recap can identify assigned action items"
        ),
        "deadline_extraction": (
            "Not clearly documented as a universal explicit extraction field"
        ),
        "evidence_quotes": (
            "Partial - Copilot uses meeting transcript/chat context, "
            "but AIMIS-style mandatory evidence quotations are not standard"
        ),
        "structured_json_output": (
            "Not a standard end-user meeting-recap output"
        ),
        "human_review_support": (
            "Yes - users can inspect transcript, recap and Copilot output"
        ),
        "custom_prompt_control": (
            "Yes - users can ask custom questions/prompts about meetings"
        ),
        "local_audio_processing": "No - Microsoft cloud/platform processing",
        "privacy_considerations": (
            "Enterprise Microsoft 365 governance and meeting policies apply"
        ),
        "deployment_control": "Low - Microsoft Teams/Microsoft 365 platform",
        "cost_model": "License/subscription dependent",
        "main_strengths": (
            "Strong Teams integration, recap, contextual Q&A "
            "and action-item support"
        ),
        "main_limitations": (
            "Requires Microsoft ecosystem/licensing and offers less "
            "researcher control over extraction/evaluation internals"
        ),
        "design_influence_on_aimis": (
            "Motivated interactive follow-up and action-oriented summaries; "
            "AIMIS emphasizes transparent schema validation and metrics"
        ),
        "verification_basis": (
            "Official Microsoft Teams/Copilot support documentation"
        )
    }
])

commercial_tools_file = (
    DIRS["commercial_comparison"] /
    "commercial_meeting_tools_comparison_verified.csv"
)

commercial_tools_comparison.to_csv(
    commercial_tools_file,
    index=False
)

print("Verified commercial-tool comparison created successfully.")

print("\nTools compared:", len(commercial_tools_comparison))

print("\nComparison table:")
display(commercial_tools_comparison)

print("\nSaved file:")
print(commercial_tools_file)

print(
    "\nNOTE: 'Partial' or 'Not clearly documented' is used "
    "where official documentation does not support a stronger claim."
)

Verified commercial-tool comparison created successfully.

Tools compared: 5

Comparison table:

,tool,transcription,meeting_summary,decision_extraction,action_item_extraction,owner_extraction,deadline_extraction,evidence_quotes,structured_json_output,human_review_support,custom_prompt_control,local_audio_processing,privacy_considerations,deployment_control,cost_model,main_strengths,main_limitations,design_influence_on_aimis,verification_basis
0,AI Meeting Intelligence System (AIMIS),Yes - Whisper,Yes,Yes - explicit structured field,Yes - explicit structured field,Yes - null allowed if unsupported,Yes - null allowed if unsupported,Yes - designed as evidence field,Yes - Pydantic validated JSON,Yes - transcript and output review,Yes - researcher controlled,Yes/Controlled - Whisper can process audio wit...,Audio transcription can remain under researche...,High - Python/Colab/Streamlit controlled,Open-source Whisper plus Gemini API usage/quota,"Transparent schema, evidence fields, controlla...",Prototype; limited completed dataset; Gemini q...,Reference system being evaluated,Implemented AIMIS artefact and current experim...
1,Otter.ai,Yes,Yes,Yes - available in Insights/templates,Yes,Yes - action items can be assigned to particip...,"Partial - due-date workflows are supported, bu...",Partial - meeting transcript/context is retain...,Partial - integrations/webhooks expose structu...,Yes - summaries/transcripts can be reviewed,Yes - custom prompts and customizable meeting ...,No - primarily cloud/SaaS processing,"Enterprise security, governance and compliance...",Low - vendor-hosted SaaS,Free and paid subscription tiers/features,"Mature transcription, summaries, decisions, ac...",Less researcher control over underlying extrac...,Motivated explicit structured outputs while AI...,Official Otter product and Help Center documen...
2,Fireflies.ai,Yes,Yes,Yes - decisions can appear in AI meeting summa...,Yes,Yes - action items can be associated with part...,Not clearly documented as a mandatory structur...,"Partial - full transcript, timestamps and spea...",Partial - transcript/summary downloads include...,"Yes - users can review, edit, share and manage...",Yes - customizable summaries/templates and AI ...,No - primarily vendor cloud processing,Official materials state security/compliance c...,Low - vendor-hosted SaaS,Free and paid subscription tiers/features,"Transcription, speaker recognition, summaries,...",Underlying extraction process is less experime...,Encouraged action-oriented meeting outputs; AI...,Official Fireflies product and Help Center doc...
3,Zoom AI (formerly AI Companion),Yes - Zoom speech-to-text/transcript features,Yes,Partial - decisions can be represented in summ...,Yes - meeting-summary templates support next s...,Not clearly documented as a universal structur...,Not clearly documented as a universal structur...,Not a standard required per-decision/action ev...,Not a standard end-user meeting-summary output,Yes - generated summaries can be reviewed and ...,Partial - configurable meeting-summary templat...,No - Zoom platform processing,AI processing governed through Zoom account/ad...,Low - Zoom Workplace platform,Account/plan and feature dependent,Integrated directly into Zoom meetings with su...,Less control over the underlying model and no ...,Motivated convenient meeting summaries while A...,"Official Zoom Support documentation, checked S..."
4,Microsoft Copilot in Teams,Teams supports meeting transcription; transcri...,Yes,Yes/Partial - Copilot can identify key decisio...,Yes - Copilot suggests and summarizes action i...,Partial - recap can identify assigned action i...,Not clearly documented as a universal explicit...,Partial - Copilot uses meeting transcript/chat...,Not a standard end-user meeting-recap output,"Yes - users can inspect transcript, recap and ...",Yes - users can ask custom questions/prompts a...,No - Microsoft cloud/platform processing,Enterprise Microsoft 365 governance and meetin...,Low - Microsoft Teams/Microsoft 365 platform,License/subscription dependent,"Strong Teams integration, recap, contextual Q&...",Requires Microsoft ecosystem/licensing and off...,Motivated interactive follow-up and action-ori...,Official Microsoft Teams/Copilot support docum...

Saved file:
/content/AI_Meeting_Intelligence_Evaluation/evaluation/commercial_tools/commercial_meeting_tools_comparison_verified.csv

NOTE: 'Partial' or 'Not clearly documented' is used where official documentation does not support a stronger claim.

In [49]:
# ============================================================
# ASR TECHNOLOGY COMPARISON
# Whisper vs Google, Azure, AssemblyAI and Vosk
# ============================================================

import pandas as pd

asr_comparison = pd.DataFrame([
    {
        "technology": "OpenAI Whisper small.en",
        "type": "Open-source local ASR",
        "accuracy_consideration": (
            "Whisper was trained for robust speech recognition across "
            "different accents, noise conditions and speech domains. "
            "M01 experimental WER = 2.82%."
        ),
        "cost": (
            "No per-minute software/API fee for local execution; "
            "requires local or cloud compute resources."
        ),
        "privacy": (
            "High control because audio can be transcribed locally "
            "without sending the original recording to an ASR provider."
        ),
        "deployment": (
            "Runs locally in Python/Colab; GPU acceleration supported."
        ),
        "speaker_diarization": (
            "Not built into standard Whisper pipeline."
        ),
        "custom_vocabulary": (
            "Limited compared with dedicated enterprise ASR services."
        ),
        "internet_required_for_inference": "No, once model is available locally",
        "main_strength": (
            "Researcher control, local processing, strong robustness "
            "and no recurring transcription API charge."
        ),
        "main_limitation": (
            "Compute requirements and lack of native diarization."
        ),
        "suitability_for_aimis": "High",
        "selection_reason": (
            "Selected because AIMIS required a reproducible Python-based "
            "ASR component with local processing, privacy control and "
            "reasonable accuracy without dependence on a paid transcription API."
        ),
        "evidence_type": (
            "Official Whisper documentation + current AIMIS experiment"
        )
    },

    {
        "technology": "Google Cloud Speech-to-Text",
        "type": "Managed cloud ASR",
        "accuracy_consideration": (
            "Commercial speech-recognition models including Chirp and "
            "models designed for different audio scenarios."
        ),
        "cost": (
            "Standard Speech-to-Text V2 recognition currently listed "
            "at approximately $0.016 per audio minute before volume discounts."
        ),
        "privacy": (
            "Audio is processed through Google Cloud services; "
            "regional/data-residency controls are available for supported configurations."
        ),
        "deployment": (
            "Cloud API; requires Google Cloud project, credentials and service access."
        ),
        "speaker_diarization": "Supported in relevant configurations",
        "custom_vocabulary": "Supports adaptation/configuration features",
        "internet_required_for_inference": "Generally Yes",
        "main_strength": (
            "Managed infrastructure, scalability and enterprise cloud features."
        ),
        "main_limitation": (
            "Ongoing usage cost and greater platform dependence."
        ),
        "suitability_for_aimis": "Moderate",
        "selection_reason": (
            "Not selected because the MSc prototype prioritized local "
            "audio control, reproducibility and minimal recurring API cost."
        ),
        "evidence_type": "Official Google Cloud documentation"
    },

    {
        "technology": "Azure AI Speech",
        "type": "Managed cloud / container ASR",
        "accuracy_consideration": (
            "Provides standard and custom speech transcription with "
            "enterprise speech-processing features."
        ),
        "cost": (
            "Free F0 tier currently includes a limited number of "
            "speech-to-text hours; paid usage is billed by processed audio."
        ),
        "privacy": (
            "Cloud processing by default; container deployment provides "
            "greater infrastructure control. Disconnected deployment requires approval."
        ),
        "deployment": (
            "Azure cloud API or supported Speech containers."
        ),
        "speaker_diarization": "Supported",
        "custom_vocabulary": "Custom Speech capabilities available",
        "internet_required_for_inference": (
            "Usually Yes; special disconnected container options exist"
        ),
        "main_strength": (
            "Enterprise deployment, customization and Microsoft ecosystem integration."
        ),
        "main_limitation": (
            "Azure account/configuration complexity, usage cost and "
            "container licensing/billing requirements."
        ),
        "suitability_for_aimis": "Moderate",
        "selection_reason": (
            "Not selected because AIMIS required a simpler research "
            "prototype with fewer cloud-platform dependencies."
        ),
        "evidence_type": "Official Microsoft Azure documentation"
    },

    {
        "technology": "AssemblyAI",
        "type": "Managed specialist speech API",
        "accuracy_consideration": (
            "Modern speech-recognition models with optional meeting-oriented "
            "features such as speaker diarization."
        ),
        "cost": (
            "Pay-as-you-go. Current asynchronous Universal-3.5 Pro "
            "pricing is approximately $0.21 per audio hour, with some "
            "additional features charged separately."
        ),
        "privacy": (
            "Audio is submitted to a managed external API; "
            "enterprise privacy/data-residency options are available."
        ),
        "deployment": "Cloud API",
        "speaker_diarization": "Supported as an optional feature",
        "custom_vocabulary": "Keyterm/customization features available",
        "internet_required_for_inference": "Yes",
        "main_strength": (
            "Simple developer API, diarization and speech-specific features."
        ),
        "main_limitation": (
            "External-service dependency and recurring usage cost."
        ),
        "suitability_for_aimis": "Moderate",
        "selection_reason": (
            "Not selected because the project emphasized locally controlled "
            "audio transcription and reduced dependency on paid external APIs."
        ),
        "evidence_type": "Official AssemblyAI documentation"
    },

    {
        "technology": "Vosk",
        "type": "Open-source offline ASR",
        "accuracy_consideration": (
            "Provides multiple language models with published benchmark "
            "results, but accuracy depends strongly on the selected model and domain."
        ),
        "cost": (
            "No per-minute managed-API fee when run locally."
        ),
        "privacy": (
            "High privacy control because recognition can operate fully offline."
        ),
        "deployment": (
            "Local/offline deployment including desktop, mobile and "
            "lightweight devices."
        ),
        "speaker_diarization": (
            "Speaker identification capabilities are available."
        ),
        "custom_vocabulary": (
            "Supports vocabulary reconfiguration with suitable models."
        ),
        "internet_required_for_inference": "No",
        "main_strength": (
            "Lightweight offline operation and low hardware requirements."
        ),
        "main_limitation": (
            "Model accuracy and language/model quality can vary substantially; "
            "older Python packaging may also create compatibility constraints."
        ),
        "suitability_for_aimis": "Moderate",
        "selection_reason": (
            "Whisper was preferred because the project prioritized "
            "robust general-purpose English meeting transcription over "
            "very lightweight offline deployment."
        ),
        "evidence_type": "Official Vosk documentation"
    }
])

# Add missing directory if necessary
DIRS["technology_comparison"] = (
    PROJECT_ROOT /
    "evaluation" /
    "technology_selection"
)

DIRS["technology_comparison"].mkdir(
    parents=True,
    exist_ok=True
)

asr_comparison_file = (
    DIRS["technology_comparison"] /
    "asr_technology_comparison.csv"
)

asr_comparison.to_csv(
    asr_comparison_file,
    index=False
)

print("ASR technology comparison created successfully.")

print("\nTechnologies compared:")
for technology in asr_comparison["technology"]:
    print("-", technology)

print("\nSelected ASR for AIMIS:")
print("OpenAI Whisper small.en")

print("\nSelection criteria:")
print("- Accuracy/robustness")
print("- Cost")
print("- Privacy")
print("- Deployment control")
print("- Python integration")
print("- External API dependence")
print("- Hardware requirements")
print("- Speaker diarization")

print("\nComparison table:")
display(asr_comparison)

print("\nSaved file:")
print(asr_comparison_file)

print(
    "\nIMPORTANT: M01 WER is an AIMIS experimental result. "
    "The other products have not yet been empirically tested on M01, "
    "so this table must not claim that Whisper is more accurate than them."
)

ASR technology comparison created successfully.

Technologies compared:
- OpenAI Whisper small.en
- Google Cloud Speech-to-Text
- Azure AI Speech
- AssemblyAI
- Vosk

Selected ASR for AIMIS:
OpenAI Whisper small.en

Selection criteria:
- Accuracy/robustness
- Cost
- Privacy
- Deployment control
- Python integration
- External API dependence
- Hardware requirements
- Speaker diarization

Comparison table:

,technology,type,accuracy_consideration,cost,privacy,deployment,speaker_diarization,custom_vocabulary,internet_required_for_inference,main_strength,main_limitation,suitability_for_aimis,selection_reason,evidence_type
0,OpenAI Whisper small.en,Open-source local ASR,Whisper was trained for robust speech recognit...,No per-minute software/API fee for local execu...,High control because audio can be transcribed ...,Runs locally in Python/Colab; GPU acceleration...,Not built into standard Whisper pipeline.,Limited compared with dedicated enterprise ASR...,"No, once model is available locally","Researcher control, local processing, strong r...",Compute requirements and lack of native diariz...,High,Selected because AIMIS required a reproducible...,Official Whisper documentation + current AIMIS...
1,Google Cloud Speech-to-Text,Managed cloud ASR,Commercial speech-recognition models including...,Standard Speech-to-Text V2 recognition current...,Audio is processed through Google Cloud servic...,"Cloud API; requires Google Cloud project, cred...",Supported in relevant configurations,Supports adaptation/configuration features,Generally Yes,"Managed infrastructure, scalability and enterp...",Ongoing usage cost and greater platform depend...,Moderate,Not selected because the MSc prototype priorit...,Official Google Cloud documentation
2,Azure AI Speech,Managed cloud / container ASR,Provides standard and custom speech transcript...,Free F0 tier currently includes a limited numb...,Cloud processing by default; container deploym...,Azure cloud API or supported Speech containers.,Supported,Custom Speech capabilities available,Usually Yes; special disconnected container op...,"Enterprise deployment, customization and Micro...","Azure account/configuration complexity, usage ...",Moderate,Not selected because AIMIS required a simpler ...,Official Microsoft Azure documentation
3,AssemblyAI,Managed specialist speech API,Modern speech-recognition models with optional...,Pay-as-you-go. Current asynchronous Universal-...,Audio is submitted to a managed external API; ...,Cloud API,Supported as an optional feature,Keyterm/customization features available,Yes,"Simple developer API, diarization and speech-s...",External-service dependency and recurring usag...,Moderate,Not selected because the project emphasized lo...,Official AssemblyAI documentation
4,Vosk,Open-source offline ASR,Provides multiple language models with publish...,No per-minute managed-API fee when run locally.,High privacy control because recognition can o...,"Local/offline deployment including desktop, mo...",Speaker identification capabilities are availa...,Supports vocabulary reconfiguration with suita...,No,Lightweight offline operation and low hardware...,Model accuracy and language/model quality can ...,Moderate,Whisper was preferred because the project prio...,Official Vosk documentation

Saved file:
/content/AI_Meeting_Intelligence_Evaluation/evaluation/technology_selection/asr_technology_comparison.csv

IMPORTANT: M01 WER is an AIMIS experimental result. The other products have not yet been empirically tested on M01, so this table must not claim that Whisper is more accurate than them.

In [50]:
# ============================================================
# LLM TECHNOLOGY COMPARISON
# Gemini vs GPT-4o, Claude 3, Llama 3 and Mistral
# ============================================================

import pandas as pd

llm_comparison = pd.DataFrame([
    {
        "model": "Gemini 3.6 Flash",
        "provider": "Google",
        "deployment_type": "Cloud API",
        "structured_output_support": "Yes",
        "context_suitability": (
            "Designed for large-context and high-throughput tasks"
        ),
        "accuracy_consideration": (
            "Suitable for structured extraction, but AIMIS accuracy "
            "must be established empirically against the gold standard."
        ),
        "latency_consideration": (
            "Flash family is optimized for speed; actual AIMIS latency "
            "must be measured experimentally."
        ),
        "cost_consideration": (
            "Free-tier access available with quotas; paid usage is "
            "token-based."
        ),
        "privacy": (
            "Transcript is sent to an external Google API."
        ),
        "local_deployment": "No",
        "api_dependency": "Yes",
        "main_strength": (
            "Structured output support, large-context capability, "
            "low-cost Flash positioning and simple Python integration."
        ),
        "main_limitation": (
            "Cloud dependency, quota/rate limits and external processing."
        ),
        "suitability_for_aimis": "High",
        "selection_reason": (
            "Selected for the prototype because it provides structured "
            "JSON/Pydantic output, handles long text, integrates easily "
            "with Python and offered accessible API usage for MSc development."
        ),
        "empirically_tested_in_aimis": "Yes - connectivity demonstrated; full evaluation pending"
    },

    {
        "model": "GPT-4o",
        "provider": "OpenAI",
        "deployment_type": "Cloud API",
        "structured_output_support": "Yes",
        "context_suitability": "128K context window",
        "accuracy_consideration": (
            "Strong general-purpose model, but it has not been tested "
            "on the AIMIS gold-standard dataset."
        ),
        "latency_consideration": (
            "Designed as a fast multimodal general-purpose model; "
            "AIMIS-specific latency not measured."
        ),
        "cost_consideration": (
            "Current API documentation lists approximately "
            "$2.50 per 1M input tokens and $10 per 1M output tokens."
        ),
        "privacy": (
            "Transcript would be processed through an external OpenAI API."
        ),
        "local_deployment": "No",
        "api_dependency": "Yes",
        "main_strength": (
            "Strong instruction following and native structured outputs."
        ),
        "main_limitation": (
            "Paid API dependency and no local deployment."
        ),
        "suitability_for_aimis": "High",
        "selection_reason": (
            "A viable alternative, but was not selected because the "
            "project was already integrated with Gemini and aimed to "
            "minimize additional API cost and implementation complexity."
        ),
        "empirically_tested_in_aimis": "No"
    },

    {
        "model": "Claude 3 Family",
        "provider": "Anthropic",
        "deployment_type": "Cloud API",
        "structured_output_support": (
            "Yes - capable of following JSON-style structured instructions"
        ),
        "context_suitability": "Up to approximately 200K for Claude 3 models",
        "accuracy_consideration": (
            "Strong reasoning and instruction-following capabilities, "
            "but not empirically evaluated on AIMIS meetings."
        ),
        "latency_consideration": (
            "Varies by Claude model; AIMIS-specific latency not measured."
        ),
        "cost_consideration": (
            "Pricing varies substantially across Claude 3 models; "
            "higher-capability models are comparatively expensive."
        ),
        "privacy": (
            "Transcript would be processed through an external Anthropic API."
        ),
        "local_deployment": "No",
        "api_dependency": "Yes",
        "main_strength": (
            "Long-context processing and strong instruction adherence."
        ),
        "main_limitation": (
            "Cloud/API dependency and potentially higher cost."
        ),
        "suitability_for_aimis": "High",
        "selection_reason": (
            "A strong alternative, but Gemini was preferred for the "
            "prototype due to existing integration, structured-output "
            "support and accessible Flash-tier usage."
        ),
        "empirically_tested_in_aimis": "No"
    },

    {
        "model": "Llama 3",
        "provider": "Meta",
        "deployment_type": "Open-weight / self-hosted or third-party cloud",
        "structured_output_support": (
            "Possible through prompting/frameworks, but not inherently "
            "equivalent to a managed schema-constrained API."
        ),
        "context_suitability": (
            "Depends on the specific Llama 3 variant and serving platform."
        ),
        "accuracy_consideration": (
            "Potentially strong when appropriately deployed, but no "
            "AIMIS-specific accuracy experiment has been conducted."
        ),
        "latency_consideration": (
            "Highly dependent on model size and local GPU hardware."
        ),
        "cost_consideration": (
            "No per-token vendor API fee when self-hosted, but requires "
            "compute infrastructure."
        ),
        "privacy": (
            "Potentially high privacy if deployed fully on local infrastructure."
        ),
        "local_deployment": "Yes",
        "api_dependency": "No if self-hosted",
        "main_strength": (
            "Local control, privacy and reduced vendor lock-in."
        ),
        "main_limitation": (
            "Significant memory/GPU requirements and more deployment complexity."
        ),
        "suitability_for_aimis": "Moderate",
        "selection_reason": (
            "Not selected because the available Colab/Streamlit environment "
            "favoured a managed API over hosting a larger LLM reliably."
        ),
        "empirically_tested_in_aimis": "No"
    },

    {
        "model": "Mistral",
        "provider": "Mistral AI",
        "deployment_type": "Cloud API and open-weight options",
        "structured_output_support": (
            "Supported through API/model workflows depending on model"
        ),
        "context_suitability": (
            "Depends on selected Mistral model."
        ),
        "accuracy_consideration": (
            "Several capable general-purpose models are available, "
            "but none have been evaluated on AIMIS gold-standard data."
        ),
        "latency_consideration": (
            "Smaller Mistral models may offer efficient inference; "
            "actual latency depends on deployment/model."
        ),
        "cost_consideration": (
            "Current API pricing varies by model; some open-weight "
            "models may also be self-hosted."
        ),
        "privacy": (
            "Can offer greater control when an open-weight model is "
            "self-hosted; API use involves external processing."
        ),
        "local_deployment": "Yes for suitable open-weight models",
        "api_dependency": "Optional",
        "main_strength": (
            "Flexible API or self-hosted deployment choices."
        ),
        "main_limitation": (
            "Additional deployment/configuration complexity for local use."
        ),
        "suitability_for_aimis": "Moderate to High",
        "selection_reason": (
            "Not selected because Gemini offered a simpler existing "
            "structured-output workflow for the implemented MSc prototype."
        ),
        "empirically_tested_in_aimis": "No"
    }
])

llm_comparison_file = (
    DIRS["technology_comparison"] /
    "llm_technology_comparison.csv"
)

llm_comparison.to_csv(
    llm_comparison_file,
    index=False
)

print("LLM technology comparison created successfully.")

print("\nModels compared:")
for model in llm_comparison["model"]:
    print("-", model)

print("\nSelected LLM for AIMIS:")
print("Gemini 3.6 Flash")

print("\nSelection dimensions:")
print("- Structured output")
print("- Accuracy considerations")
print("- Cost")
print("- Latency")
print("- Privacy")
print("- Local deployment")
print("- API dependency")
print("- Deployment constraints")

print("\nComparison table:")
display(llm_comparison)

print("\nSaved file:")
print(llm_comparison_file)

print(
    "\nIMPORTANT: This is a technology-selection comparison, "
    "not an empirical accuracy ranking. Only Gemini has currently "
    "been executed in AIMIS."
)

LLM technology comparison created successfully.

Models compared:
- Gemini 3.6 Flash
- GPT-4o
- Claude 3 Family
- Llama 3
- Mistral

Selected LLM for AIMIS:
Gemini 3.6 Flash

Selection dimensions:
- Structured output
- Accuracy considerations
- Cost
- Latency
- Privacy
- Local deployment
- API dependency
- Deployment constraints

Comparison table:

,model,provider,deployment_type,structured_output_support,context_suitability,accuracy_consideration,latency_consideration,cost_consideration,privacy,local_deployment,api_dependency,main_strength,main_limitation,suitability_for_aimis,selection_reason,empirically_tested_in_aimis
0,Gemini 3.6 Flash,Google,Cloud API,Yes,Designed for large-context and high-throughput...,"Suitable for structured extraction, but AIMIS ...",Flash family is optimized for speed; actual AI...,Free-tier access available with quotas; paid u...,Transcript is sent to an external Google API.,No,Yes,"Structured output support, large-context capab...","Cloud dependency, quota/rate limits and extern...",High,Selected for the prototype because it provides...,Yes - connectivity demonstrated; full evaluati...
1,GPT-4o,OpenAI,Cloud API,Yes,128K context window,"Strong general-purpose model, but it has not b...",Designed as a fast multimodal general-purpose ...,Current API documentation lists approximately ...,Transcript would be processed through an exter...,No,Yes,Strong instruction following and native struct...,Paid API dependency and no local deployment.,High,"A viable alternative, but was not selected bec...",No
2,Claude 3 Family,Anthropic,Cloud API,Yes - capable of following JSON-style structur...,Up to approximately 200K for Claude 3 models,Strong reasoning and instruction-following cap...,Varies by Claude model; AIMIS-specific latency...,Pricing varies substantially across Claude 3 m...,Transcript would be processed through an exter...,No,Yes,Long-context processing and strong instruction...,Cloud/API dependency and potentially higher cost.,High,"A strong alternative, but Gemini was preferred...",No
3,Llama 3,Meta,Open-weight / self-hosted or third-party cloud,"Possible through prompting/frameworks, but not...",Depends on the specific Llama 3 variant and se...,Potentially strong when appropriately deployed...,Highly dependent on model size and local GPU h...,"No per-token vendor API fee when self-hosted, ...",Potentially high privacy if deployed fully on ...,Yes,No if self-hosted,"Local control, privacy and reduced vendor lock...",Significant memory/GPU requirements and more d...,Moderate,Not selected because the available Colab/Strea...,No
4,Mistral,Mistral AI,Cloud API and open-weight options,Supported through API/model workflows dependin...,Depends on selected Mistral model.,Several capable general-purpose models are ava...,Smaller Mistral models may offer efficient inf...,Current API pricing varies by model; some open...,Can offer greater control when an open-weight ...,Yes for suitable open-weight models,Optional,Flexible API or self-hosted deployment choices.,Additional deployment/configuration complexity...,Moderate to High,Not selected because Gemini offered a simpler ...,No

Saved file:
/content/AI_Meeting_Intelligence_Evaluation/evaluation/technology_selection/llm_technology_comparison.csv

IMPORTANT: This is a technology-selection comparison, not an empirical accuracy ranking. Only Gemini has currently been executed in AIMIS.

In [51]:
# ============================================================
# SAVE GEMINI EXPERIMENT OUTPUTS AND RUN METADATA
# ============================================================

import json
import pandas as pd
from pathlib import Path


def save_gemini_experiment_result(
    parsed_output,
    experiment_record
):
    """
    Save one Gemini experimental run.

    Saves:
    1. Run metadata to CSV
    2. Successful structured output to JSON
    3. Failed-run information without inventing output
    """

    meeting_id = experiment_record["meeting_id"]
    prompt_type = experiment_record["prompt_type"]
    run_number = experiment_record["run_number"]

    # --------------------------------------------------------
    # Select output directory
    # --------------------------------------------------------

    if prompt_type == "generic":
        output_directory = DIRS["generic_outputs"]

    elif prompt_type == "structured":
        output_directory = DIRS["structured_outputs"]

    else:
        raise ValueError(
            "Unknown prompt type."
        )

    # --------------------------------------------------------
    # Save experiment metadata
    # --------------------------------------------------------

    metadata_file = (
        DIRS["extraction_results"] /
        "gemini_experiment_runs.csv"
    )

    new_record_df = pd.DataFrame(
        [experiment_record]
    )

    if metadata_file.exists():

        existing_df = pd.read_csv(
            metadata_file
        )

        # Prevent accidental duplicate record
        existing_df = existing_df[
            ~(
                (existing_df["meeting_id"] == meeting_id)
                &
                (existing_df["prompt_type"] == prompt_type)
                &
                (existing_df["run_number"] == run_number)
            )
        ]

        metadata_df = pd.concat(
            [
                existing_df,
                new_record_df
            ],
            ignore_index=True
        )

    else:

        metadata_df = new_record_df


    metadata_df.to_csv(
        metadata_file,
        index=False
    )

    # --------------------------------------------------------
    # Save successful structured output
    # --------------------------------------------------------

    if (
        experiment_record["status"] == "SUCCESS"
        and parsed_output is not None
    ):

        output_file = (
            output_directory /
            f"{meeting_id}_{prompt_type}_run{run_number}.json"
        )

        if hasattr(parsed_output, "model_dump"):
            output_data = parsed_output.model_dump()
        else:
            output_data = parsed_output

        with open(
            output_file,
            "w",
            encoding="utf-8"
        ) as f:

            json.dump(
                output_data,
                f,
                indent=2,
                ensure_ascii=False
            )

        print("Gemini output saved successfully.")
        print("Output file:")
        print(output_file)

    else:

        print(
            "Run was not successful, so no AI output JSON was created."
        )

        output_file = None

    print("\nRun metadata saved:")
    print(metadata_file)

    return output_file


print("Gemini experiment result saver created successfully.")

print("\nIt will record:")
print("- Meeting ID")
print("- Prompt type")
print("- Run number")
print("- Gemini model")
print("- Temperature")
print("- Success/failure status")
print("- Processing latency")
print("- Timestamp")
print("- HTTP 403 status")
print("- HTTP 429 quota status")
print("- Error message")
print("- Successful structured JSON output")

print("\nNo Gemini request has been made in this cell.")

Gemini experiment result saver created successfully.

It will record:
- Meeting ID
- Prompt type
- Run number
- Gemini model
- Temperature
- Success/failure status
- Processing latency
- Timestamp
- HTTP 403 status
- HTTP 429 quota status
- Error message
- Successful structured JSON output

No Gemini request has been made in this cell.

In [52]:
# ============================================================
# CREATE FIXED REVIEWED TRANSCRIPT FOR PROMPT EXPERIMENTS
# M01
# ============================================================

import re

meeting_id = "M01"

# Start from the original human/reference transcript
lines = reference_text.splitlines()

reviewed_lines = []

metadata_prefixes = (
    "Meeting Transcript",
    "Meeting Topic:",
    "Duration:",
    "Participants:"
)

for line in lines:

    line = line.strip()

    if not line:
        continue

    # Remove document-only metadata
    if line.startswith(metadata_prefixes):
        continue

    # IMPORTANT:
    # Keep speaker labels such as Sarah:, James:, etc.
    # because they are needed for owner/action extraction.
    reviewed_lines.append(line)


reviewed_transcript = "\n".join(reviewed_lines)

# Normalize excessive whitespace only
reviewed_transcript = re.sub(
    r"[ \t]+",
    " ",
    reviewed_transcript
).strip()


# Save the exact transcript that BOTH prompt conditions will use
reviewed_transcript_file = (
    DIRS["reference_transcripts"] /
    "M01_reviewed_experiment_transcript.txt"
)

reviewed_transcript_file.write_text(
    reviewed_transcript,
    encoding="utf-8"
)


print("M01 reviewed experimental transcript created successfully.")

print("\nWord count:")
print(len(reviewed_transcript.split()))

print("\nFirst 1200 characters:\n")
print(reviewed_transcript[:1200])

print("\nSaved file:")
print(reviewed_transcript_file)

print("\nCONTROLLED EXPERIMENT RULE:")
print(
    "Generic and structured prompts will both receive "
    "this exact same transcript."
)

print(
    "This prevents transcript differences from affecting "
    "the prompt-comparison results."
)

M01 reviewed experimental transcript created successfully.

Word count:
727

First 1200 characters:

Sarah: Good morning, everyone. Thanks for joining. I know everyone has a fairly busy schedule today, so I’ll try to keep this short. The main purpose of the meeting is just to check where we are with the project, discuss any issues, and agree on what needs to be completed before Friday. Is everyone okay with that?
James: Yeah, that sounds good.
Aisha: Yes, absolutely.
Michael: Fine with me.
Sarah: Great. James, maybe you can start. How are things going with the data collection?
James: Pretty well, actually. We’ve received most of the information we were waiting for. I’d say around eighty percent of the data has now been collected. There are still two departments that haven’t sent their responses, though.
Sarah: Okay. Have you followed up with them?
James: Yes. I emailed both of them yesterday afternoon. One department replied this morning and said they should send everything by tomorrow. I haven’t heard back from the other one yet.
Sarah: Right. Maybe give them until tomorrow morning, and if there’s still no response, send another reminder.
James: Yeah, that’s what I was thinking.
Sarah: Perfect. Aisha, how about the analysis side?
Aisha: The initial analysis is going well. I start

Saved file:
/content/AI_Meeting_Intelligence_Evaluation/data/reference_transcripts/M01_reviewed_experiment_transcript.txt

CONTROLLED EXPERIMENT RULE:
Generic and structured prompts will both receive this exact same transcript.
This prevents transcript differences from affecting the prompt-comparison results.

In [53]:
# ============================================================
# M01 CONTROLLED EXPERIMENT
# GENERIC PROMPT — RUN 1
# ============================================================

generic_output_run1, generic_record_run1 = run_gemini_experiment(
    transcript=reviewed_transcript,
    prompt_type="generic",
    meeting_id="M01",
    run_number=1
)

print("\n==============================")
print("GENERIC PROMPT — M01 RUN 1")
print("==============================")

print("\nRun status:")
print(generic_record_run1["status"])

print("\nModel:")
print(generic_record_run1["model"])

print("\nTemperature:")
print(generic_record_run1["temperature"])

print("\nLatency:")
print(generic_record_run1["latency_seconds"], "seconds")

print("\nHTTP 403:")
print(generic_record_run1["http_403"])

print("\nHTTP 429:")
print(generic_record_run1["http_429"])

if generic_record_run1["error"]:
    print("\nError:")
    print(generic_record_run1["error"])


# ------------------------------------------------------------
# Save result and metadata
# ------------------------------------------------------------

generic_run1_file = save_gemini_experiment_result(
    generic_output_run1,
    generic_record_run1
)


# ------------------------------------------------------------
# Display successful structured output
# ------------------------------------------------------------

if (
    generic_record_run1["status"] == "SUCCESS"
    and generic_output_run1 is not None
):

    print("\nStructured Gemini output:\n")

    if hasattr(generic_output_run1, "model_dump"):
        display(generic_output_run1.model_dump())
    else:
        display(generic_output_run1)

else:

    print(
        "\nNo experimental output was scored because "
        "the API request was unsuccessful."
    )

Running generic prompt | Meeting: M01 | Run: 1
Status: FAILED
Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-3.6-flash\nPlease retry in 25.38101508s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.6-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '25s'}]}}

==============================
GENERIC PROMPT — M01 RUN 1
==============================

Run status:
FAILED

Model:
gemini-3.6-flash

Temperature:
0.2

Latency:
0.37 seconds

HTTP 403:
False

HTTP 429:
True

Error:
429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-3.6-flash\nPlease retry in 25.38101508s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.6-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '25s'}]}}
Run was not successful, so no AI output JSON was created.

Run metadata saved:
/content/AI_Meeting_Intelligence_Evaluation/evaluation/extraction/gemini_experiment_runs.csv

No experimental output was scored because the API request was unsuccessful.

In [54]:
# ============================================================
# CHECK AVAILABLE GEMINI MODELS
# No experimental meeting request is made here
# ============================================================

available_models = []

try:
    for model in gemini_client.models.list():

        model_name = getattr(model, "name", "")
        display_name = getattr(model, "display_name", "")
        supported_actions = getattr(
            model,
            "supported_actions",
            None
        )

        # Keep Gemini-family models only
        if "gemini" in str(model_name).lower():

            available_models.append({
                "model_name": model_name,
                "display_name": display_name,
                "supported_actions": supported_actions
            })

    print("Gemini model discovery completed successfully.")

    print("\nNumber of Gemini-family models found:")
    print(len(available_models))

    print("\nAvailable Gemini models:\n")

    for i, model_info in enumerate(
        available_models,
        start=1
    ):
        print(
            f"{i}. {model_info['model_name']}"
        )

        if model_info["display_name"]:
            print(
                "   Display name:",
                model_info["display_name"]
            )

        if model_info["supported_actions"]:
            print(
                "   Supported actions:",
                model_info["supported_actions"]
            )

        print()

except Exception as e:

    print("Model discovery failed.")
    print("Error:")
    print(e)


print(
    "\nIMPORTANT: No generic or structured "
    "meeting experiment was executed in this cell."
)

Gemini model discovery completed successfully.

Number of Gemini-family models found:
39

Available Gemini models:

1. models/gemini-2.5-flash
   Display name: Gemini 2.5 Flash
   Supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

2. models/gemini-2.5-pro
   Display name: Gemini 2.5 Pro
   Supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

3. models/gemini-2.5-flash-preview-tts
   Display name: Gemini 2.5 Flash Preview TTS
   Supported actions: ['countTokens', 'generateContent']

4. models/gemini-2.5-pro-preview-tts
   Display name: Gemini 2.5 Pro Preview TTS
   Supported actions: ['countTokens', 'generateContent', 'batchGenerateContent']

5. models/gemini-flash-latest
   Display name: Gemini Flash Latest
   Supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

6. models/gemini-flash-lite-latest
   Display name: Gemini Flash-Lite Latest
   Supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

7. models/gemini-pro-latest
   Display name: Gemini Pro Latest
   Supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

8. models/gemini-2.5-flash-lite
   Display name: Gemini 2.5 Flash-Lite
   Supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

9. models/gemini-2.5-flash-image
   Display name: Nano Banana
   Supported actions: ['generateContent', 'countTokens', 'batchGenerateContent']

10. models/gemini-3-flash-preview
   Display name: Gemini 3 Flash Preview
   Supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

11. models/gemini-3.1-pro-preview
   Display name: Gemini 3.1 Pro Preview
   Supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

12. models/gemini-3.1-pro-preview-customtools
   Display name: Gemini 3.1 Pro Preview Custom Tools
   Supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

13. models/gemini-3.1-flash-lite-preview
   Display name: Gemini 3.1 Flash Lite Preview
   Supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

14. models/gemini-3.1-flash-lite
   Display name: Gemini 3.1 Flash Lite
   Supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

15. models/gemini-3-pro-image-preview
   Display name: Nano Banana Pro
   Supported actions: ['generateContent', 'countTokens', 'batchGenerateContent']

16. models/gemini-3-pro-image
   Display name: Nano Banana Pro
   Supported actions: ['generateContent', 'countTokens', 'batchGenerateContent']

17. models/gemini-3.1-flash-image-preview
   Display name: Nano Banana 2
   Supported actions: ['generateContent', 'countTokens', 'batchGenerateContent']

18. models/gemini-3.1-flash-image
   Display name: Nano Banana 2
   Supported actions: ['generateContent', 'countTokens', 'batchGenerateContent']

19. models/gemini-3.1-flash-lite-image
   Display name: Nano Banana 2 Lite
   Supported actions: ['generateContent', 'countTokens', 'batchGenerateContent']

20. models/gemini-3.5-flash
   Display name: Gemini 3.5 Flash
   Supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

21. models/gemini-3.5-flash-lite
   Display name: Gemini 3.5 Flash Lite
   Supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

22. models/gemini-omni-flash-preview
   Display name: Gemini Omni Flash Preview
   Supported actions: ['generateContent', 'countTokens']

23. models/gemini-omni-1.1-flash
   Display name: Gemini Omni 1.1 Flash
   Supported actions: ['generateContent', 'countTokens']

24. models/gemini-3.5-transcribe
   Display name: Gemini 3.5 Transcribe
   Supported actions: ['generateContent', 'countTokens']

25. models/gemini-3.6-flash
   Display name: Gemini 3.6 Flash
   Supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

26. models/gemini-3.7-flash
   Display name: Gemini 3.7 Flash
   Supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

27. models/gemini-3.1-flash-tts-preview
   Display name: Gemini 3.1 Flash TTS Preview
   Supported actions: ['generateContent', 'countTokens', 'batchGenerateContent']

28. models/gemini-robotics-er-2-preview
   Display name: Gemini Robotics-ER 2 Preview
   Supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

29. models/gemini-2.5-computer-use-preview-10-2025
   Display name: Gemini 2.5 Computer Use Preview 10-2025
   Supported actions: ['generateContent', 'countTokens']

30. models/gemini-embedding-001
   Display name: Gemini Embedding 001
   Supported actions: ['embedContent', 'countTextTokens', 'countTokens', 'asyncBatchEmbedContent']

31. models/gemini-embedding-2-preview
   Display name: Gemini Embedding 2 Preview
   Supported actions: ['embedContent', 'countTextTokens', 'countTokens', 'asyncBatchEmbedContent']

32. models/gemini-embedding-2
   Display name: Gemini Embedding 2
   Supported actions: ['embedContent', 'countTextTokens', 'countTokens', 'asyncBatchEmbedContent']

33. models/gemini-3.5-transcribe-live
   Display name: Gemini 3.5 Transcribe Live
   Supported actions: ['bidiGenerateContent']

34. models/gemini-2.5-flash-native-audio-latest
   Display name: Gemini 2.5 Flash Native Audio Latest
   Supported actions: ['countTokens', 'bidiGenerateContent']

35. models/gemini-2.5-flash-native-audio-preview-09-2025
   Display name: Gemini 2.5 Flash Native Audio Preview 09-2025
   Supported actions: ['countTokens', 'bidiGenerateContent']

36. models/gemini-2.5-flash-native-audio-preview-12-2025
   Display name: Gemini 2.5 Flash Native Audio Preview 12-2025
   Supported actions: ['countTokens', 'bidiGenerateContent']

37. models/gemini-3.1-flash-live-preview
   Display name: Gemini 3.1 Flash Live Preview
   Supported actions: ['bidiGenerateContent']

38. models/gemini-robotics-er-2-streaming-preview
   Display name: Gemini Robotics-ER 2 Streaming Preview
   Supported actions: ['bidiGenerateContent']

39. models/gemini-3.5-live-translate-preview
   Display name: Gemini 3.5 Live Translate Preview
   Supported actions: ['bidiGenerateContent']


IMPORTANT: No generic or structured meeting experiment was executed in this cell.

In [55]:
# ============================================================
# GEMINI 3.5 FLASH-LITE ACCESS / QUOTA TEST
# This is NOT a meeting experiment
# ============================================================

import time
from datetime import datetime
import json

CANDIDATE_GEMINI_MODEL = "gemini-3.5-flash-lite"

candidate_test = {
    "model": CANDIDATE_GEMINI_MODEL,
    "timestamp": datetime.now().isoformat(),
    "status": "NOT_RUN",
    "latency_seconds": None,
    "http_403": False,
    "http_429": False,
    "error": None,
    "response": None
}

print("Testing candidate Gemini model:")
print(CANDIDATE_GEMINI_MODEL)

print(
    "\nThis is only a minimal connectivity/quota test, "
    "not an experimental meeting run."
)

start_time = time.perf_counter()

try:

    response = gemini_client.models.generate_content(
        model=CANDIDATE_GEMINI_MODEL,
        contents=(
            "Return exactly this text and nothing else: "
            "GEMINI_35_FLASH_LITE_TEST_SUCCESS"
        )
    )

    latency = time.perf_counter() - start_time

    candidate_test["status"] = "SUCCESS"
    candidate_test["latency_seconds"] = round(latency, 3)
    candidate_test["response"] = response.text.strip()

except Exception as e:

    latency = time.perf_counter() - start_time
    error_text = str(e)

    candidate_test["status"] = "FAILED"
    candidate_test["latency_seconds"] = round(latency, 3)
    candidate_test["error"] = error_text
    candidate_test["http_403"] = (
        "403" in error_text
    )
    candidate_test["http_429"] = (
        "429" in error_text
        or "RESOURCE_EXHAUSTED" in error_text
    )


print("\n==============================")
print("CANDIDATE MODEL TEST RESULT")
print("==============================")

print("Model:")
print(candidate_test["model"])

print("\nStatus:")
print(candidate_test["status"])

print("\nLatency:")
print(candidate_test["latency_seconds"], "seconds")

print("\nHTTP 403:")
print(candidate_test["http_403"])

print("\nHTTP 429:")
print(candidate_test["http_429"])

if candidate_test["response"]:
    print("\nResponse:")
    print(candidate_test["response"])

if candidate_test["error"]:
    print("\nError:")
    print(candidate_test["error"])


# Save test evidence
candidate_test_file = (
    DIRS["logs"] /
    "gemini_35_flash_lite_access_test.json"
)

with open(
    candidate_test_file,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        candidate_test,
        f,
        indent=2,
        ensure_ascii=False
    )

print("\nSaved test log:")
print(candidate_test_file)

print(
    "\nIMPORTANT: GEMINI_MODEL has NOT been changed "
    "by this cell."
)

Testing candidate Gemini model:
gemini-3.5-flash-lite

This is only a minimal connectivity/quota test, not an experimental meeting run.

==============================
CANDIDATE MODEL TEST RESULT
==============================
Model:
gemini-3.5-flash-lite

Status:
SUCCESS

Latency:
0.982 seconds

HTTP 403:
False

HTTP 429:
False

Response:
GEMINI_35_FLASH_LITE_TEST_SUCCESS

Saved test log:
/content/AI_Meeting_Intelligence_Evaluation/logs/gemini_35_flash_lite_access_test.json

IMPORTANT: GEMINI_MODEL has NOT been changed by this cell.

In [56]:
# ============================================================
# LOCK GEMINI MODEL FOR CONTROLLED EXPERIMENTS
# ============================================================

import json
from datetime import datetime

# ------------------------------------------------------------
# Fixed model for ALL subsequent prompt experiments
# ------------------------------------------------------------

GEMINI_MODEL = "gemini-3.5-flash-lite"
GEMINI_TEMPERATURE = 0.2

model_selection_record = {
    "experiment_model": GEMINI_MODEL,
    "temperature": GEMINI_TEMPERATURE,
    "selection_timestamp": datetime.now().isoformat(),
    "previous_model": "gemini-3.6-flash",
    "previous_model_issue": (
        "HTTP 429 RESOURCE_EXHAUSTED during repeated experimental access "
        "under the available free-tier quota."
    ),
    "candidate_access_test": "SUCCESS",
    "candidate_test_latency_seconds": 0.982,
    "candidate_http_403": False,
    "candidate_http_429": False,
    "selection_reason": (
        "Gemini 3.5 Flash-Lite successfully passed the API access test "
        "and will therefore be used consistently for both generic and "
        "structured prompting conditions. Using one fixed model, "
        "temperature, transcript and output schema ensures that prompt "
        "design is the principal experimental variable."
    ),
    "experimental_control": {
        "same_model_for_both_prompts": True,
        "same_temperature_for_both_prompts": True,
        "same_transcript_for_both_prompts": True,
        "same_response_schema_for_both_prompts": True
    }
}

model_selection_file = (
    DIRS["logs"] /
    "gemini_experimental_model_selection.json"
)

with open(
    model_selection_file,
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        model_selection_record,
        f,
        indent=2,
        ensure_ascii=False
    )


print("Experimental Gemini model locked successfully.")

print("\nModel:")
print(GEMINI_MODEL)

print("\nTemperature:")
print(GEMINI_TEMPERATURE)

print("\nExperimental controls:")
print("- Same Gemini model: Yes")
print("- Same temperature: Yes")
print("- Same transcript: Yes")
print("- Same output schema: Yes")
print("- Experimental variable: Prompt design")

print("\nPrevious Gemini 3.6 Flash issue:")
print("429 quota limitation - documented separately")

print("\nSaved configuration:")
print(model_selection_file)

print(
    "\nIMPORTANT: All subsequent generic and structured "
    "prompt experiments must use this fixed configuration."
)

Experimental Gemini model locked successfully.

Model:
gemini-3.5-flash-lite

Temperature:
0.2

Experimental controls:
- Same Gemini model: Yes
- Same temperature: Yes
- Same transcript: Yes
- Same output schema: Yes
- Experimental variable: Prompt design

Previous Gemini 3.6 Flash issue:
429 quota limitation - documented separately

Saved configuration:
/content/AI_Meeting_Intelligence_Evaluation/logs/gemini_experimental_model_selection.json

IMPORTANT: All subsequent generic and structured prompt experiments must use this fixed configuration.

In [57]:
# ============================================================
# M01 CONTROLLED EXPERIMENT
# GENERIC PROMPT — RUN 1
# LOCKED MODEL: gemini-3.5-flash-lite
# ============================================================

generic_output_run1, generic_record_run1 = run_gemini_experiment(
    transcript=reviewed_transcript,
    prompt_type="generic",
    meeting_id="M01",
    run_number=1
)

print("\n==============================")
print("GENERIC PROMPT — M01 RUN 1")
print("==============================")

print("\nStatus:")
print(generic_record_run1["status"])

print("\nModel:")
print(generic_record_run1["model"])

print("\nTemperature:")
print(generic_record_run1["temperature"])

print("\nLatency:")
print(generic_record_run1["latency_seconds"], "seconds")

print("\nHTTP 403:")
print(generic_record_run1["http_403"])

print("\nHTTP 429:")
print(generic_record_run1["http_429"])

if generic_record_run1["error"]:
    print("\nError:")
    print(generic_record_run1["error"])


# ------------------------------------------------------------
# Save experimental result
# ------------------------------------------------------------

generic_run1_file = save_gemini_experiment_result(
    generic_output_run1,
    generic_record_run1
)


# ------------------------------------------------------------
# Display successful output
# ------------------------------------------------------------

if (
    generic_record_run1["status"] == "SUCCESS"
    and generic_output_run1 is not None
):

    print("\nStructured output:\n")

    if hasattr(generic_output_run1, "model_dump"):
        generic_output_dict = generic_output_run1.model_dump()
    else:
        generic_output_dict = generic_output_run1

    display(generic_output_dict)

    print("\nExtracted counts:")
    print(
        "Decisions:",
        len(generic_output_dict.get("decisions", []))
    )
    print(
        "Action items:",
        len(generic_output_dict.get("action_items", []))
    )
    print(
        "Unresolved issues:",
        len(generic_output_dict.get("unresolved_issues", []))
    )
    print(
        "Ambiguities:",
        len(generic_output_dict.get("ambiguities", []))
    )

else:

    print(
        "\nNo output will be evaluated because "
        "the Gemini request was unsuccessful."
    )

Running generic prompt | Meeting: M01 | Run: 1
Status: SUCCESS
Latency: 2.846 seconds

==============================
GENERIC PROMPT — M01 RUN 1
==============================

Status:
SUCCESS

Model:
gemini-3.5-flash-lite

Temperature:
0.2

Latency:
2.846 seconds

HTTP 403:
False

HTTP 429:
False
Gemini output saved successfully.
Output file:
/content/AI_Meeting_Intelligence_Evaluation/outputs/generic/M01_generic_run1.json

Run metadata saved:
/content/AI_Meeting_Intelligence_Evaluation/evaluation/extraction/gemini_experiment_runs.csv

Structured output:

{'meeting_title': 'Project Status Check-in',
 'summary': 'The team met to review project progress, discuss missing data and incomplete responses, address terminology inconsistencies in the report, and agree on tasks to be completed before Friday.',
 'key_topics': ['Data collection status',
  'Analysis and missing values',
  'Report drafting and terminology',
  'Handling delayed department responses'],
 'decisions': [{'decision': "Use the term 'employee participation' consistently throughout the report.",
   'evidence': "Sarah: Agreed. Let’s keep 'employee participation' throughout the report."},
  {'decision': 'Flag incomplete responses for now and decide later whether to exclude them or treat them differently once the full dataset is ready.',
   'evidence': 'Sarah: For now, just flag them. Once we have the complete dataset, we can decide whether to exclude those responses or treat the missing values differently.'},
  {'decision': "Wait until tomorrow afternoon for the remaining department's response; if they do not respond, proceed with available data and document the limitation.",
   'evidence': 'Sarah: Let’s wait until tomorrow. If they still haven’t responded by the afternoon, we’ll proceed with what we have and document that limitation.'}],
 'action_items': [{'action': 'Follow up on the outstanding department responses if they do not reply by tomorrow morning.',
   'owner': 'James',
   'deadline': 'Tomorrow morning/afternoon',
   'evidence': 'Sarah: Maybe give them until tomorrow morning, and if there’s still no response, send another reminder.'},
  {'action': 'Continue cleaning and analyzing existing data and flag the incomplete responses.',
   'owner': 'Aisha',
   'deadline': None,
   'evidence': 'Sarah: Aisha will continue cleaning and analyzing the existing data, but she’ll flag the incomplete responses for now.'},
  {'action': "Continue working on the report and update terms to consistently use 'employee participation'.",
   'owner': 'Michael',
   'deadline': None,
   'evidence': 'Sarah: Michael will continue working on the report and make sure we consistently use the term “employee participation.”'},
  {'action': 'Send an updated draft of the report.',
   'owner': 'Michael',
   'deadline': 'Tomorrow afternoon',
   'evidence': 'Michael: I should be able to send you an updated draft tomorrow afternoon.'},
  {'action': 'Review the updated report draft.',
   'owner': 'Sarah',
   'deadline': 'Tomorrow evening',
   'evidence': 'Sarah: I’ll also review the report tomorrow evening once Michael sends the updated version.'}],
 'unresolved_issues': ['One department has not yet sent their data responses.',
  'Six responses with missing values need a final decision on whether to be excluded or treated differently.'],
 'ambiguities': []}

Extracted counts:
Decisions: 3
Action items: 5
Unresolved issues: 2
Ambiguities: 0

In [58]:
# ============================================================
# M01 CONTROLLED EXPERIMENT
# STRUCTURED PROMPT — RUN 1
# LOCKED MODEL: gemini-3.5-flash-lite
# ============================================================

structured_output_run1, structured_record_run1 = run_gemini_experiment(
    transcript=reviewed_transcript,
    prompt_type="structured",
    meeting_id="M01",
    run_number=1
)

print("\n==============================")
print("STRUCTURED PROMPT — M01 RUN 1")
print("==============================")

print("\nStatus:")
print(structured_record_run1["status"])

print("\nModel:")
print(structured_record_run1["model"])

print("\nTemperature:")
print(structured_record_run1["temperature"])

print("\nLatency:")
print(structured_record_run1["latency_seconds"], "seconds")

print("\nHTTP 403:")
print(structured_record_run1["http_403"])

print("\nHTTP 429:")
print(structured_record_run1["http_429"])

if structured_record_run1["error"]:
    print("\nError:")
    print(structured_record_run1["error"])


# ------------------------------------------------------------
# Save experimental result
# ------------------------------------------------------------

structured_run1_file = save_gemini_experiment_result(
    structured_output_run1,
    structured_record_run1
)


# ------------------------------------------------------------
# Display successful output
# ------------------------------------------------------------

if (
    structured_record_run1["status"] == "SUCCESS"
    and structured_output_run1 is not None
):

    print("\nStructured output:\n")

    if hasattr(structured_output_run1, "model_dump"):
        structured_output_dict = structured_output_run1.model_dump()
    else:
        structured_output_dict = structured_output_run1

    display(structured_output_dict)

    print("\nExtracted counts:")
    print(
        "Decisions:",
        len(structured_output_dict.get("decisions", []))
    )
    print(
        "Action items:",
        len(structured_output_dict.get("action_items", []))
    )
    print(
        "Unresolved issues:",
        len(structured_output_dict.get("unresolved_issues", []))
    )
    print(
        "Ambiguities:",
        len(structured_output_dict.get("ambiguities", []))
    )

else:

    print(
        "\nNo output will be evaluated because "
        "the Gemini request was unsuccessful."
    )

Running structured prompt | Meeting: M01 | Run: 1
Status: SUCCESS
Latency: 2.879 seconds

==============================
STRUCTURED PROMPT — M01 RUN 1
==============================

Status:
SUCCESS

Model:
gemini-3.5-flash-lite

Temperature:
0.2

Latency:
2.879 seconds

HTTP 403:
False

HTTP 429:
False
Gemini output saved successfully.
Output file:
/content/AI_Meeting_Intelligence_Evaluation/outputs/structured/M01_structured_run1.json

Run metadata saved:
/content/AI_Meeting_Intelligence_Evaluation/evaluation/extraction/gemini_experiment_runs.csv

Structured output:

{'meeting_title': 'Project Status and Review Meeting',
 'summary': 'The team met to review project progress, discuss data collection and analysis status, address terminology inconsistencies in the report, and plan tasks to be completed before Friday.',
 'key_topics': ['Project status check',
  'Data collection progress and missing responses',
  'Data analysis and missing values',
  'Report drafting and terminology consistency',
  'Deadlines and next steps before Friday'],
 'decisions': [{'decision': 'Use the term "employee participation" consistently throughout the report.',
   'evidence': 'Sarah: Agreed. Let’s keep “employee participation” throughout the report. Michael, can you change the other references to match? / Michael: Yeah, no problem.'},
  {'decision': 'Flag the incomplete responses for now, and decide later whether to exclude them or treat missing values differently once the complete dataset is available.',
   'evidence': 'Sarah: For now, just flag them. Once we have the complete dataset, we can decide whether to exclude those responses or treat the missing values differently. / Aisha: Sure. I’ll do that.'},
  {'decision': "Wait until tomorrow afternoon for the remaining department's response; if they still haven't responded, proceed with what is available and document the limitation.",
   'evidence': 'Sarah: Let’s wait until tomorrow. If they still haven’t responded by the afternoon, we’ll proceed with what we have and document that limitation.'}],
 'action_items': [{'action': 'Give the remaining department until tomorrow morning, and if there is still no response, send another reminder.',
   'owner': 'James',
   'deadline': None,
   'evidence': 'Sarah: Maybe give them until tomorrow morning, and if there’s still no response, send another reminder. / James: Yeah, that’s what I was thinking.'},
  {'action': 'Continue cleaning and analyzing the existing data, and flag the incomplete responses for now.',
   'owner': 'Aisha',
   'deadline': None,
   'evidence': 'Sarah: ...Aisha will continue cleaning and analyzing the existing data, but she’ll flag the incomplete responses for now. / Aisha: Sounds good.'},
  {'action': 'Continue working on the report and make sure the term "employee participation" is used consistently.',
   'owner': 'Michael',
   'deadline': None,
   'evidence': 'Sarah: ...Michael will continue working on the report and make sure we consistently use the term “employee participation.” / Michael: Got it.'},
  {'action': 'Send an updated draft of the report.',
   'owner': 'Michael',
   'deadline': 'tomorrow afternoon',
   'evidence': 'Michael: I should be able to send you an updated draft tomorrow afternoon.'},
  {'action': 'Review the updated report version.',
   'owner': 'Sarah',
   'deadline': 'tomorrow evening',
   'evidence': 'Sarah: I’ll also review the report tomorrow evening once Michael sends the updated version.'}],
 'unresolved_issues': ['Whether to exclude responses with missing values or treat the missing values differently.',
  'Whether the remaining department will submit their data.'],
 'ambiguities': []}

Extracted counts:
Decisions: 3
Action items: 5
Unresolved issues: 2
Ambiguities: 0

In [59]:
# ============================================================
# M01 REPEATABILITY EXPERIMENT
# GENERIC + STRUCTURED
# RUNS 2 AND 3
# ============================================================

import time
import pandas as pd

repeatability_results = []

for run_number in [2, 3]:

    for prompt_type in ["generic", "structured"]:

        print("\n" + "=" * 65)
        print(
            f"M01 | {prompt_type.upper()} PROMPT | RUN {run_number}"
        )
        print("=" * 65)

        output, record = run_gemini_experiment(
            transcript=reviewed_transcript,
            prompt_type=prompt_type,
            meeting_id="M01",
            run_number=run_number
        )

        # Save run metadata + JSON
        save_gemini_experiment_result(
            output,
            record
        )

        # ---------------------------------------------
        # Summarise successful output
        # ---------------------------------------------

        if (
            record["status"] == "SUCCESS"
            and output is not None
        ):

            if hasattr(output, "model_dump"):
                output_dict = output.model_dump()
            else:
                output_dict = output

            decision_count = len(
                output_dict.get("decisions", [])
            )

            action_count = len(
                output_dict.get("action_items", [])
            )

            unresolved_count = len(
                output_dict.get(
                    "unresolved_issues",
                    []
                )
            )

            ambiguity_count = len(
                output_dict.get(
                    "ambiguities",
                    []
                )
            )

        else:

            decision_count = None
            action_count = None
            unresolved_count = None
            ambiguity_count = None

        repeatability_results.append({
            "meeting_id": "M01",
            "prompt_type": prompt_type,
            "run_number": run_number,
            "status": record["status"],
            "latency_seconds": record[
                "latency_seconds"
            ],
            "decision_count": decision_count,
            "action_item_count": action_count,
            "unresolved_issue_count": unresolved_count,
            "ambiguity_count": ambiguity_count,
            "http_403": record["http_403"],
            "http_429": record["http_429"]
        })

        print("\nResult summary:")
        print("Status:", record["status"])
        print(
            "Latency:",
            record["latency_seconds"],
            "seconds"
        )
        print("HTTP 403:", record["http_403"])
        print("HTTP 429:", record["http_429"])

        if decision_count is not None:
            print(
                "Decisions:",
                decision_count
            )
            print(
                "Action items:",
                action_count
            )
            print(
                "Unresolved issues:",
                unresolved_count
            )
            print(
                "Ambiguities:",
                ambiguity_count
            )

        if record["error"]:
            print("\nError:")
            print(record["error"])

        # Small gap between API calls
        time.sleep(1.5)


# ============================================================
# ADD RUN 1 RESULTS TO REPEATABILITY SUMMARY
# ============================================================

for prompt_type, output_obj, record_obj in [
    (
        "generic",
        generic_output_run1,
        generic_record_run1
    ),
    (
        "structured",
        structured_output_run1,
        structured_record_run1
    )
]:

    if hasattr(output_obj, "model_dump"):
        output_dict = output_obj.model_dump()
    else:
        output_dict = output_obj

    repeatability_results.append({
        "meeting_id": "M01",
        "prompt_type": prompt_type,
        "run_number": 1,
        "status": record_obj["status"],
        "latency_seconds": record_obj[
            "latency_seconds"
        ],
        "decision_count": len(
            output_dict.get("decisions", [])
        ),
        "action_item_count": len(
            output_dict.get("action_items", [])
        ),
        "unresolved_issue_count": len(
            output_dict.get(
                "unresolved_issues",
                []
            )
        ),
        "ambiguity_count": len(
            output_dict.get(
                "ambiguities",
                []
            )
        ),
        "http_403": record_obj["http_403"],
        "http_429": record_obj["http_429"]
    })


# ============================================================
# CREATE REPEATABILITY SUMMARY
# ============================================================

repeatability_df = pd.DataFrame(
    repeatability_results
)

repeatability_df = repeatability_df.sort_values(
    ["prompt_type", "run_number"]
).reset_index(drop=True)


repeatability_file = (
    DIRS["repeatability"] /
    "M01_prompt_repeatability_summary.csv"
)

repeatability_df.to_csv(
    repeatability_file,
    index=False
)


print("\n\n" + "=" * 65)
print("M01 REPEATABILITY SUMMARY")
print("=" * 65)

display(repeatability_df)


# ============================================================
# BASIC LATENCY + COUNT STABILITY
# ============================================================

successful_runs = repeatability_df[
    repeatability_df["status"] == "SUCCESS"
]

if not successful_runs.empty:

    stability_summary = (
        successful_runs
        .groupby("prompt_type")
        .agg(
            successful_runs=(
                "run_number",
                "count"
            ),
            mean_latency_seconds=(
                "latency_seconds",
                "mean"
            ),
            sd_latency_seconds=(
                "latency_seconds",
                "std"
            ),
            mean_decisions=(
                "decision_count",
                "mean"
            ),
            sd_decisions=(
                "decision_count",
                "std"
            ),
            mean_action_items=(
                "action_item_count",
                "mean"
            ),
            sd_action_items=(
                "action_item_count",
                "std"
            )
        )
        .round(3)
    )

    print("\nStability summary:")
    display(stability_summary)


print("\nSaved file:")
print(repeatability_file)

print(
    "\nIMPORTANT: Similar item counts do not prove that "
    "the extracted content is identical or accurate. "
    "Content-level stability and gold-standard accuracy "
    "will be calculated separately."
)

=================================================================
M01 | GENERIC PROMPT | RUN 2
=================================================================
Running generic prompt | Meeting: M01 | Run: 2
Status: SUCCESS
Latency: 2.956 seconds
Gemini output saved successfully.
Output file:
/content/AI_Meeting_Intelligence_Evaluation/outputs/generic/M01_generic_run2.json

Run metadata saved:
/content/AI_Meeting_Intelligence_Evaluation/evaluation/extraction/gemini_experiment_runs.csv

Result summary:
Status: SUCCESS
Latency: 2.956 seconds
HTTP 403: False
HTTP 429: False
Decisions: 3
Action items: 5
Unresolved issues: 1
Ambiguities: 0

=================================================================
M01 | STRUCTURED PROMPT | RUN 2
=================================================================
Running structured prompt | Meeting: M01 | Run: 2
Status: SUCCESS
Latency: 2.975 seconds
Gemini output saved successfully.
Output file:
/content/AI_Meeting_Intelligence_Evaluation/outputs/structured/M01_structured_run2.json

Run metadata saved:
/content/AI_Meeting_Intelligence_Evaluation/evaluation/extraction/gemini_experiment_runs.csv

Result summary:
Status: SUCCESS
Latency: 2.975 seconds
HTTP 403: False
HTTP 429: False
Decisions: 3
Action items: 5
Unresolved issues: 1
Ambiguities: 0

=================================================================
M01 | GENERIC PROMPT | RUN 3
=================================================================
Running generic prompt | Meeting: M01 | Run: 3
Status: SUCCESS
Latency: 2.722 seconds
Gemini output saved successfully.
Output file:
/content/AI_Meeting_Intelligence_Evaluation/outputs/generic/M01_generic_run3.json

Run metadata saved:
/content/AI_Meeting_Intelligence_Evaluation/evaluation/extraction/gemini_experiment_runs.csv

Result summary:
Status: SUCCESS
Latency: 2.722 seconds
HTTP 403: False
HTTP 429: False
Decisions: 3
Action items: 5
Unresolved issues: 1
Ambiguities: 0

=================================================================
M01 | STRUCTURED PROMPT | RUN 3
=================================================================
Running structured prompt | Meeting: M01 | Run: 3
Status: SUCCESS
Latency: 2.493 seconds
Gemini output saved successfully.
Output file:
/content/AI_Meeting_Intelligence_Evaluation/outputs/structured/M01_structured_run3.json

Run metadata saved:
/content/AI_Meeting_Intelligence_Evaluation/evaluation/extraction/gemini_experiment_runs.csv

Result summary:
Status: SUCCESS
Latency: 2.493 seconds
HTTP 403: False
HTTP 429: False
Decisions: 1
Action items: 5
Unresolved issues: 2
Ambiguities: 0


=================================================================
M01 REPEATABILITY SUMMARY
=================================================================

,meeting_id,prompt_type,run_number,status,latency_seconds,decision_count,action_item_count,unresolved_issue_count,ambiguity_count,http_403,http_429
0,M01,generic,1,SUCCESS,2.846,3,5,2,0,False,False
1,M01,generic,2,SUCCESS,2.956,3,5,1,0,False,False
2,M01,generic,3,SUCCESS,2.722,3,5,1,0,False,False
3,M01,structured,1,SUCCESS,2.879,3,5,2,0,False,False
4,M01,structured,2,SUCCESS,2.975,3,5,1,0,False,False
5,M01,structured,3,SUCCESS,2.493,1,5,2,0,False,False

Stability summary:

,successful_runs,mean_latency_seconds,sd_latency_seconds,mean_decisions,sd_decisions,mean_action_items,sd_action_items
prompt_type,,,,,,,
generic,3,2.841,0.117,3.000,0.000,5.0,0.0
structured,3,2.782,0.255,2.333,1.155,5.0,0.0

Saved file:
/content/AI_Meeting_Intelligence_Evaluation/outputs/repeatability/M01_prompt_repeatability_summary.csv

IMPORTANT: Similar item counts do not prove that the extracted content is identical or accurate. Content-level stability and gold-standard accuracy will be calculated separately.

In [60]:
# ============================================================
# CONTENT-LEVEL REPEATABILITY ANALYSIS
# Compare extracted decisions and action items across runs
# ============================================================

import json
import re
import pandas as pd
import numpy as np
from rapidfuzz.fuzz import token_set_ratio


# ------------------------------------------------------------
# Text normalization
# ------------------------------------------------------------

def normalize_repeatability_text(text):

    if text is None:
        return ""

    text = str(text).lower().strip()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    )

    return text.strip()


# ------------------------------------------------------------
# Load one saved Gemini run
# ------------------------------------------------------------

def load_saved_run(
    meeting_id,
    prompt_type,
    run_number
):

    if prompt_type == "generic":
        directory = DIRS["generic_outputs"]

    elif prompt_type == "structured":
        directory = DIRS["structured_outputs"]

    else:
        raise ValueError(
            "prompt_type must be generic or structured"
        )

    file_path = (
        directory /
        f"{meeting_id}_{prompt_type}_run{run_number}.json"
    )

    with open(
        file_path,
        "r",
        encoding="utf-8"
    ) as f:
        return json.load(f)


# ------------------------------------------------------------
# Extract item text
# ------------------------------------------------------------

def get_item_texts(
    output_dict,
    item_type
):

    if item_type == "decisions":

        return [
            item["decision"]
            for item in output_dict.get(
                "decisions",
                []
            )
        ]

    elif item_type == "action_items":

        return [
            item["action"]
            for item in output_dict.get(
                "action_items",
                []
            )
        ]

    else:
        raise ValueError(
            "Unknown item type"
        )


# ------------------------------------------------------------
# One-to-one matching between two runs
# ------------------------------------------------------------

def compare_run_items(
    items_a,
    items_b,
    similarity_threshold=70
):

    candidates = []

    for i, text_a in enumerate(items_a):

        for j, text_b in enumerate(items_b):

            similarity = token_set_ratio(
                normalize_repeatability_text(
                    text_a
                ),
                normalize_repeatability_text(
                    text_b
                )
            )

            candidates.append({
                "index_a": i,
                "index_b": j,
                "text_a": text_a,
                "text_b": text_b,
                "similarity": similarity
            })


    # Highest similarity first
    candidates = sorted(
        candidates,
        key=lambda x: x["similarity"],
        reverse=True
    )


    used_a = set()
    used_b = set()
    matches = []


    for candidate in candidates:

        if (
            candidate["index_a"]
            not in used_a
            and
            candidate["index_b"]
            not in used_b
            and
            candidate["similarity"]
            >= similarity_threshold
        ):

            matches.append(candidate)

            used_a.add(
                candidate["index_a"]
            )

            used_b.add(
                candidate["index_b"]
            )


    matched_count = len(matches)

    # Stability precision/recall-like overlap
    # based on two generated sets
    denominator = (
        len(items_a) +
        len(items_b)
    )

    if denominator > 0:

        overlap_f1 = (
            2 * matched_count /
            denominator
        )

    else:
        overlap_f1 = 1.0


    if matched_count > 0:

        mean_similarity = np.mean([
            match["similarity"]
            for match in matches
        ])

    else:
        mean_similarity = 0.0


    return {
        "items_run_a": len(items_a),
        "items_run_b": len(items_b),
        "matched_items": matched_count,
        "overlap_f1": round(
            overlap_f1,
            4
        ),
        "mean_matched_similarity": round(
            mean_similarity / 100,
            4
        )
    }


# ============================================================
# PAIRWISE COMPARISON
# ============================================================

pairwise_rows = []

run_pairs = [
    (1, 2),
    (1, 3),
    (2, 3)
]


for prompt_type in [
    "generic",
    "structured"
]:

    outputs = {
        run: load_saved_run(
            "M01",
            prompt_type,
            run
        )
        for run in [1, 2, 3]
    }


    for item_type in [
        "decisions",
        "action_items"
    ]:

        for run_a, run_b in run_pairs:

            items_a = get_item_texts(
                outputs[run_a],
                item_type
            )

            items_b = get_item_texts(
                outputs[run_b],
                item_type
            )

            comparison = compare_run_items(
                items_a,
                items_b,
                similarity_threshold=70
            )

            pairwise_rows.append({
                "meeting_id": "M01",
                "prompt_type": prompt_type,
                "item_type": item_type,
                "run_a": run_a,
                "run_b": run_b,
                **comparison
            })


content_repeatability_df = pd.DataFrame(
    pairwise_rows
)


# ------------------------------------------------------------
# Summary by prompt and item type
# ------------------------------------------------------------

content_stability_summary = (
    content_repeatability_df
    .groupby([
        "prompt_type",
        "item_type"
    ])
    .agg(
        mean_overlap_f1=(
            "overlap_f1",
            "mean"
        ),
        sd_overlap_f1=(
            "overlap_f1",
            "std"
        ),
        mean_text_similarity=(
            "mean_matched_similarity",
            "mean"
        ),
        minimum_overlap_f1=(
            "overlap_f1",
            "min"
        )
    )
    .round(4)
    .reset_index()
)


# ------------------------------------------------------------
# Save results
# ------------------------------------------------------------

pairwise_file = (
    DIRS["repeatability"] /
    "M01_content_repeatability_pairwise.csv"
)

summary_file = (
    DIRS["repeatability"] /
    "M01_content_stability_summary.csv"
)


content_repeatability_df.to_csv(
    pairwise_file,
    index=False
)

content_stability_summary.to_csv(
    summary_file,
    index=False
)


print(
    "Content-level repeatability analysis completed successfully."
)

print(
    "\nSimilarity threshold: 70/100"
)

print(
    "\nPAIRWISE RUN COMPARISON:"
)

display(
    content_repeatability_df
)


print(
    "\nCONTENT STABILITY SUMMARY:"
)

display(
    content_stability_summary
)


print("\nSaved files:")
print(pairwise_file)
print(summary_file)


print(
    "\nINTERPRETATION WARNING:"
)

print(
    "Overlap F1 measures consistency between repeated AI runs."
)

print(
    "It does NOT measure correctness against the human gold standard."
)

print(
    "A system can be consistently wrong, so accuracy will be evaluated separately."
)

Content-level repeatability analysis completed successfully.

Similarity threshold: 70/100

PAIRWISE RUN COMPARISON:

,meeting_id,prompt_type,item_type,run_a,run_b,items_run_a,items_run_b,matched_items,overlap_f1,mean_matched_similarity
0,M01,generic,decisions,1,2,3,3,3,1.0,0.9617
1,M01,generic,decisions,1,3,3,3,3,1.0,0.9543
2,M01,generic,decisions,2,3,3,3,3,1.0,0.9339
3,M01,generic,action_items,1,2,5,5,5,1.0,0.9695
4,M01,generic,action_items,1,3,5,5,5,1.0,0.9262
5,M01,generic,action_items,2,3,5,5,5,1.0,0.9375
6,M01,structured,decisions,1,2,3,3,3,1.0,0.9866
7,M01,structured,decisions,1,3,3,1,1,0.5,1.0000
8,M01,structured,decisions,2,3,3,1,1,0.5,1.0000
9,M01,structured,action_items,1,2,5,5,4,0.8,0.9806
10,M01,structured,action_items,1,3,5,5,4,0.8,0.9806
11,M01,structured,action_items,2,3,5,5,5,1.0,0.9229

CONTENT STABILITY SUMMARY:

,prompt_type,item_type,mean_overlap_f1,sd_overlap_f1,mean_text_similarity,minimum_overlap_f1
0,generic,action_items,1.0000,0.0000,0.9444,1.0
1,generic,decisions,1.0000,0.0000,0.9500,1.0
2,structured,action_items,0.8667,0.1155,0.9614,0.8
3,structured,decisions,0.6667,0.2887,0.9955,0.5

Saved files:
/content/AI_Meeting_Intelligence_Evaluation/outputs/repeatability/M01_content_repeatability_pairwise.csv
/content/AI_Meeting_Intelligence_Evaluation/outputs/repeatability/M01_content_stability_summary.csv

INTERPRETATION WARNING:
Overlap F1 measures consistency between repeated AI runs.
It does NOT measure correctness against the human gold standard.
A system can be consistently wrong, so accuracy will be evaluated separately.

In [61]:
# ============================================================
# BLINDED HUMAN EVALUATION PACKAGE
# M01 - GENERIC vs STRUCTURED - RUN 1
# ============================================================

import json
import random
from pathlib import Path
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment


# ------------------------------------------------------------
# Load Run 1 outputs
# ------------------------------------------------------------

generic_run1_path = (
    DIRS["generic_outputs"] /
    "M01_generic_run1.json"
)

structured_run1_path = (
    DIRS["structured_outputs"] /
    "M01_structured_run1.json"
)

with open(
    generic_run1_path,
    "r",
    encoding="utf-8"
) as f:
    generic_run1_data = json.load(f)

with open(
    structured_run1_path,
    "r",
    encoding="utf-8"
) as f:
    structured_run1_data = json.load(f)


# ------------------------------------------------------------
# Convert structured JSON to readable text
# ------------------------------------------------------------

def format_meeting_output(data):

    sections = []

    sections.append(
        f"MEETING TITLE\n{data.get('meeting_title', '')}"
    )

    sections.append(
        f"SUMMARY\n{data.get('summary', '')}"
    )

    topics = "\n".join(
        f"- {x}"
        for x in data.get("key_topics", [])
    )

    sections.append(
        f"KEY TOPICS\n{topics}"
    )

    decisions = []

    for i, item in enumerate(
        data.get("decisions", []),
        start=1
    ):
        decisions.append(
            f"{i}. {item.get('decision', '')}\n"
            f"Evidence: {item.get('evidence', '')}"
        )

    sections.append(
        "DECISIONS\n" +
        "\n\n".join(decisions)
    )

    actions = []

    for i, item in enumerate(
        data.get("action_items", []),
        start=1
    ):
        actions.append(
            f"{i}. {item.get('action', '')}\n"
            f"Owner: {item.get('owner', '')}\n"
            f"Deadline: {item.get('deadline', '')}\n"
            f"Evidence: {item.get('evidence', '')}"
        )

    sections.append(
        "ACTION ITEMS\n" +
        "\n\n".join(actions)
    )

    unresolved = "\n".join(
        f"- {x}"
        for x in data.get(
            "unresolved_issues",
            []
        )
    )

    sections.append(
        f"UNRESOLVED ISSUES\n{unresolved}"
    )

    ambiguities = "\n".join(
        f"- {x}"
        for x in data.get(
            "ambiguities",
            []
        )
    )

    sections.append(
        f"AMBIGUITIES\n{ambiguities}"
    )

    return "\n\n".join(sections)


generic_readable = format_meeting_output(
    generic_run1_data
)

structured_readable = format_meeting_output(
    structured_run1_data
)


# ------------------------------------------------------------
# Randomized blinded assignment
# Different order for H1 and H2
# ------------------------------------------------------------

random.seed(42)

evaluator_mappings = {}

for evaluator_id in ["H1", "H2"]:

    conditions = [
        ("generic", generic_readable),
        ("structured", structured_readable)
    ]

    random.shuffle(conditions)

    evaluator_mappings[evaluator_id] = {
        "Output A": conditions[0][0],
        "Output B": conditions[1][0]
    }

    output_contents = {
        "Output A": conditions[0][1],
        "Output B": conditions[1][1]
    }


    # --------------------------------------------------------
    # Create workbook
    # --------------------------------------------------------

    wb = Workbook()

    ws_instruction = wb.active
    ws_instruction.title = "Instructions"

    instructions = [
        "M01 Blinded Human Evaluation",
        "",
        "Purpose:",
        "Evaluate two AI-generated meeting outputs without knowing which prompt produced them.",
        "",
        "Read the original meeting transcript first.",
        "Then evaluate Output A and Output B independently.",
        "",
        "Rating Scale:",
        "1 = Very Poor",
        "2 = Poor",
        "3 = Acceptable",
        "4 = Good",
        "5 = Excellent",
        "",
        "Evaluation Dimensions:",
        "Accuracy = factual correctness relative to the transcript.",
        "Completeness = coverage of important meeting information.",
        "Clarity = how clear and understandable the output is.",
        "Usefulness = practical usefulness as meeting documentation.",
        "",
        "Do not compare the outputs while assigning the first rating.",
        "Judge each output against the transcript.",
        "Do not attempt to identify which prompting method was used."
    ]

    for row_num, text in enumerate(
        instructions,
        start=1
    ):
        ws_instruction.cell(
            row=row_num,
            column=1,
            value=text
        )


    # --------------------------------------------------------
    # Transcript sheet
    # --------------------------------------------------------

    ws_transcript = wb.create_sheet(
        "Transcript"
    )

    ws_transcript["A1"] = (
        "Original Human-Reviewed Meeting Transcript"
    )

    ws_transcript["A1"].font = Font(
        bold=True
    )

    transcript_lines = (
        reviewed_transcript.splitlines()
    )

    for row_num, line in enumerate(
        transcript_lines,
        start=3
    ):
        ws_transcript.cell(
            row=row_num,
            column=1,
            value=line
        )


    # --------------------------------------------------------
    # Output A
    # --------------------------------------------------------

    ws_a = wb.create_sheet(
        "Output A"
    )

    ws_a["A1"] = "AI Meeting Output A"
    ws_a["A1"].font = Font(
        bold=True
    )

    ws_a["A3"] = output_contents[
        "Output A"
    ]

    ws_a["A3"].alignment = Alignment(
        wrap_text=True,
        vertical="top"
    )


    # --------------------------------------------------------
    # Output B
    # --------------------------------------------------------

    ws_b = wb.create_sheet(
        "Output B"
    )

    ws_b["A1"] = "AI Meeting Output B"
    ws_b["A1"].font = Font(
        bold=True
    )

    ws_b["A3"] = output_contents[
        "Output B"
    ]

    ws_b["A3"].alignment = Alignment(
        wrap_text=True,
        vertical="top"
    )


    # --------------------------------------------------------
    # Rating sheet
    # --------------------------------------------------------

    ws_rating = wb.create_sheet(
        "Ratings"
    )

    headers = [
        "meeting_id",
        "evaluator_id",
        "blind_output_id",
        "accuracy",
        "completeness",
        "clarity",
        "usefulness",
        "overall_comments"
    ]

    for col_num, header in enumerate(
        headers,
        start=1
    ):
        ws_rating.cell(
            row=1,
            column=col_num,
            value=header
        )

        ws_rating.cell(
            row=1,
            column=col_num
        ).font = Font(
            bold=True
        )


    for row_num, blind_id in enumerate(
        ["Output A", "Output B"],
        start=2
    ):

        values = [
            "M01",
            evaluator_id,
            blind_id,
            "",
            "",
            "",
            "",
            ""
        ]

        for col_num, value in enumerate(
            values,
            start=1
        ):
            ws_rating.cell(
                row=row_num,
                column=col_num,
                value=value
            )


    # Column widths
    for ws in wb.worksheets:
        ws.column_dimensions["A"].width = 45

    ws_rating.column_dimensions["H"].width = 50


    evaluation_file = (
        DIRS["human_results"] /
        f"M01_{evaluator_id}_Blinded_Human_Evaluation.xlsx"
    )

    wb.save(
        evaluation_file
    )

    print(
        f"{evaluator_id} workbook created:"
    )
    print(evaluation_file)


# ------------------------------------------------------------
# Save hidden condition mapping
# Evaluators should NOT receive this file
# ------------------------------------------------------------

mapping_file = (
    DIRS["logs"] /
    "M01_blinded_human_evaluation_mapping.json"
)

with open(
    mapping_file,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        evaluator_mappings,
        f,
        indent=2
    )


print("\nBlinded human evaluation package created successfully.")

print("\nEvaluators:")
print("- H1")
print("- H2")

print("\nEach evaluator will rate:")
print("- Output A")
print("- Output B")

print("\nDimensions:")
print("- Accuracy")
print("- Completeness")
print("- Clarity")
print("- Usefulness")

print("\nRating scale:")
print("1 = Very Poor")
print("2 = Poor")
print("3 = Acceptable")
print("4 = Good")
print("5 = Excellent")

print("\nCondition mapping saved privately:")
print(mapping_file)

print(
    "\nIMPORTANT: Do NOT give the mapping file to H1 or H2."
)

print(
    "The evaluators should receive only their respective Excel workbook."
)

H1 workbook created:
/content/AI_Meeting_Intelligence_Evaluation/evaluation/human/M01_H1_Blinded_Human_Evaluation.xlsx
H2 workbook created:
/content/AI_Meeting_Intelligence_Evaluation/evaluation/human/M01_H2_Blinded_Human_Evaluation.xlsx

Blinded human evaluation package created successfully.

Evaluators:
- H1
- H2

Each evaluator will rate:
- Output A
- Output B

Dimensions:
- Accuracy
- Completeness
- Clarity
- Usefulness

Rating scale:
1 = Very Poor
2 = Poor
3 = Acceptable
4 = Good
5 = Excellent

Condition mapping saved privately:
/content/AI_Meeting_Intelligence_Evaluation/logs/M01_blinded_human_evaluation_mapping.json

IMPORTANT: Do NOT give the mapping file to H1 or H2.
The evaluators should receive only their respective Excel workbook.

In [62]:
# ============================================================
# PACKAGE BLINDED HUMAN EVALUATION WORKBOOKS
# ============================================================

import zipfile
from google.colab import files

h1_file = (
    DIRS["human_results"] /
    "M01_H1_Blinded_Human_Evaluation.xlsx"
)

h2_file = (
    DIRS["human_results"] /
    "M01_H2_Blinded_Human_Evaluation.xlsx"
)

human_eval_zip = (
    PROJECT_ROOT /
    "M01_Blinded_Human_Evaluation_Package.zip"
)


with zipfile.ZipFile(
    human_eval_zip,
    "w",
    zipfile.ZIP_DEFLATED
) as zipf:

    zipf.write(
        h1_file,
        arcname=h1_file.name
    )

    zipf.write(
        h2_file,
        arcname=h2_file.name
    )


print("Blinded human-evaluation package created successfully.")

print("\nPackage contents:")
print("- M01_H1_Blinded_Human_Evaluation.xlsx")
print("- M01_H2_Blinded_Human_Evaluation.xlsx")

print("\nEXCLUDED from package:")
print("- M01_blinded_human_evaluation_mapping.json")

print("\nPackage location:")
print(human_eval_zip)

print(
    "\nGive H1 only the H1 workbook and H2 only the H2 workbook."
)

print(
    "Do not tell either evaluator which output is generic or structured."
)

# Download ZIP
files.download(
    str(human_eval_zip)
)

Blinded human-evaluation package created successfully.

Package contents:
- M01_H1_Blinded_Human_Evaluation.xlsx
- M01_H2_Blinded_Human_Evaluation.xlsx

EXCLUDED from package:
- M01_blinded_human_evaluation_mapping.json

Package location:
/content/AI_Meeting_Intelligence_Evaluation/M01_Blinded_Human_Evaluation_Package.zip

Give H1 only the H1 workbook and H2 only the H2 workbook.
Do not tell either evaluator which output is generic or structured.

In [63]:
# ============================================================
# IMPORT COMPLETED BLINDED HUMAN EVALUATION
# H1 or H2
# ============================================================

import pandas as pd
from google.colab import files


def import_completed_human_evaluation(evaluator_id):
    """
    Upload and validate a completed blinded human-evaluation
    workbook for evaluator H1 or H2.
    """

    evaluator_id = evaluator_id.upper().strip()

    if evaluator_id not in ["H1", "H2"]:
        raise ValueError(
            "evaluator_id must be 'H1' or 'H2'."
        )

    print(
        f"Upload the COMPLETED workbook for {evaluator_id}."
    )

    uploaded = files.upload()

    if not uploaded:
        print("No file uploaded.")
        return None

    uploaded_filename = list(
        uploaded.keys()
    )[0]

    print("\nUploaded file:")
    print(uploaded_filename)


    # --------------------------------------------------------
    # Read Ratings sheet
    # --------------------------------------------------------

    try:

        ratings_df = pd.read_excel(
            uploaded_filename,
            sheet_name="Ratings"
        )

    except Exception as e:

        print(
            "\nERROR: Could not read the 'Ratings' sheet."
        )
        print(e)

        return None


    # --------------------------------------------------------
    # Required columns
    # --------------------------------------------------------

    required_columns = [
        "meeting_id",
        "evaluator_id",
        "blind_output_id",
        "accuracy",
        "completeness",
        "clarity",
        "usefulness",
        "overall_comments"
    ]

    missing_columns = [
        col
        for col in required_columns
        if col not in ratings_df.columns
    ]

    if missing_columns:

        print(
            "\nERROR: Missing required columns:"
        )

        print(missing_columns)

        return None


    # --------------------------------------------------------
    # Keep expected rows only
    # --------------------------------------------------------

    ratings_df = ratings_df[
        ratings_df["blind_output_id"].isin(
            ["Output A", "Output B"]
        )
    ].copy()


    if len(ratings_df) != 2:

        print(
            "\nERROR: Expected exactly two rating rows "
            "(Output A and Output B)."
        )

        return None


    # --------------------------------------------------------
    # Verify evaluator ID
    # --------------------------------------------------------

    ratings_df[
        "evaluator_id"
    ] = evaluator_id

    ratings_df[
        "meeting_id"
    ] = "M01"


    # --------------------------------------------------------
    # Validate rating values
    # --------------------------------------------------------

    rating_columns = [
        "accuracy",
        "completeness",
        "clarity",
        "usefulness"
    ]

    validation_errors = []

    for column in rating_columns:

        ratings_df[column] = pd.to_numeric(
            ratings_df[column],
            errors="coerce"
        )

        invalid_rows = ratings_df[
            ratings_df[column].isna()
            |
            (ratings_df[column] < 1)
            |
            (ratings_df[column] > 5)
        ]

        if not invalid_rows.empty:

            validation_errors.append(
                column
            )


    if validation_errors:

        print(
            "\nVALIDATION FAILED."
        )

        print(
            "The following dimensions contain "
            "blank or invalid ratings:"
        )

        for item in validation_errors:
            print("-", item)

        print(
            "\nEvery rating must be an integer "
            "from 1 to 5."
        )

        return None


    # Force integer values
    for column in rating_columns:

        ratings_df[column] = (
            ratings_df[column]
            .astype(int)
        )


    # --------------------------------------------------------
    # Save completed blinded ratings
    # --------------------------------------------------------

    output_file = (
        DIRS["human_results"] /
        f"M01_{evaluator_id}_completed_blinded_ratings.csv"
    )

    ratings_df.to_csv(
        output_file,
        index=False
    )


    print(
        "\nHuman evaluation imported successfully."
    )

    print("\nEvaluator:")
    print(evaluator_id)

    print("\nValidated ratings:")
    display(ratings_df)

    print("\nSaved file:")
    print(output_file)

    print(
        "\nIMPORTANT: Prompt identities remain blinded "
        "at this stage."
    )

    return ratings_df


print(
    "Completed human-evaluation importer created successfully."
)

print("\nUsage after evaluators return their files:")
print(
    "H1_ratings = import_completed_human_evaluation('H1')"
)
print(
    "H2_ratings = import_completed_human_evaluation('H2')"
)

print(
    "\nDo not run those two commands until the real "
    "evaluators have independently completed their workbooks."
)

Completed human-evaluation importer created successfully.

Usage after evaluators return their files:
H1_ratings = import_completed_human_evaluation('H1')
H2_ratings = import_completed_human_evaluation('H2')

Do not run those two commands until the real evaluators have independently completed their workbooks.

In [64]:
# ============================================================
# FORMAL INTER-ANNOTATOR AGREEMENT CALCULATOR
# Gold-standard annotators A1 vs A2
# ============================================================

import re
import numpy as np
import pandas as pd
from rapidfuzz.fuzz import token_set_ratio


# ------------------------------------------------------------
# Normalize free-text annotation
# ------------------------------------------------------------

def normalize_annotation_text(text):

    if pd.isna(text):
        return ""

    text = str(text).lower().strip()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    )

    return text.strip()


# ------------------------------------------------------------
# Pairwise item matching
# ------------------------------------------------------------

def calculate_annotation_agreement(
    annotator1_df,
    annotator2_df,
    similarity_threshold=70
):

    results = []

    for item_type in [
        "decision",
        "action_item"
    ]:

        a1 = annotator1_df[
            annotator1_df["item_type"] == item_type
        ].copy()

        a2 = annotator2_df[
            annotator2_df["item_type"] == item_type
        ].copy()

        a1 = a1[
            a1["item_text"].notna()
            &
            (
                a1["item_text"]
                .astype(str)
                .str.strip() != ""
            )
        ].reset_index(drop=True)

        a2 = a2[
            a2["item_text"].notna()
            &
            (
                a2["item_text"]
                .astype(str)
                .str.strip() != ""
            )
        ].reset_index(drop=True)


        # ----------------------------------------------------
        # Generate all possible pair similarities
        # ----------------------------------------------------

        candidate_pairs = []

        for i, row1 in a1.iterrows():

            for j, row2 in a2.iterrows():

                similarity = token_set_ratio(
                    normalize_annotation_text(
                        row1["item_text"]
                    ),
                    normalize_annotation_text(
                        row2["item_text"]
                    )
                )

                candidate_pairs.append({
                    "a1_index": i,
                    "a2_index": j,
                    "similarity": similarity
                })


        # Highest similarities matched first
        candidate_pairs = sorted(
            candidate_pairs,
            key=lambda x: x["similarity"],
            reverse=True
        )

        used_a1 = set()
        used_a2 = set()
        matched_pairs = []


        for pair in candidate_pairs:

            if (
                pair["similarity"]
                >= similarity_threshold
                and
                pair["a1_index"] not in used_a1
                and
                pair["a2_index"] not in used_a2
            ):

                used_a1.add(
                    pair["a1_index"]
                )

                used_a2.add(
                    pair["a2_index"]
                )

                matched_pairs.append(
                    pair
                )


        matched_count = len(
            matched_pairs
        )

        a1_count = len(a1)
        a2_count = len(a2)


        # ----------------------------------------------------
        # Agreement precision, recall and F1
        # ----------------------------------------------------

        agreement_precision = (
            matched_count / a1_count
            if a1_count > 0
            else 0.0
        )

        agreement_recall = (
            matched_count / a2_count
            if a2_count > 0
            else 0.0
        )

        if (
            agreement_precision
            +
            agreement_recall
        ) > 0:

            agreement_f1 = (
                2
                * agreement_precision
                * agreement_recall
                /
                (
                    agreement_precision
                    +
                    agreement_recall
                )
            )

        else:

            agreement_f1 = 0.0


        # ----------------------------------------------------
        # Mean semantic similarity of matched items
        # ----------------------------------------------------

        if matched_count > 0:

            mean_similarity = np.mean([
                pair["similarity"]
                for pair in matched_pairs
            ]) / 100

        else:

            mean_similarity = 0.0


        # ----------------------------------------------------
        # Owner/deadline agreement for action items
        # ----------------------------------------------------

        owner_agreements = []
        deadline_agreements = []

        if item_type == "action_item":

            for pair in matched_pairs:

                row1 = a1.iloc[
                    pair["a1_index"]
                ]

                row2 = a2.iloc[
                    pair["a2_index"]
                ]


                owner1 = normalize_annotation_text(
                    row1.get(
                        "owner",
                        ""
                    )
                )

                owner2 = normalize_annotation_text(
                    row2.get(
                        "owner",
                        ""
                    )
                )

                if owner1 or owner2:

                    owner_agreements.append(
                        int(owner1 == owner2)
                    )


                deadline1 = normalize_annotation_text(
                    row1.get(
                        "deadline",
                        ""
                    )
                )

                deadline2 = normalize_annotation_text(
                    row2.get(
                        "deadline",
                        ""
                    )
                )

                if deadline1 or deadline2:

                    deadline_agreements.append(
                        int(
                            deadline1
                            ==
                            deadline2
                        )
                    )


        owner_agreement = (
            np.mean(owner_agreements)
            if owner_agreements
            else None
        )

        deadline_agreement = (
            np.mean(deadline_agreements)
            if deadline_agreements
            else None
        )


        results.append({
            "meeting_id": "M01",
            "item_type": item_type,
            "annotator1_items": a1_count,
            "annotator2_items": a2_count,
            "matched_items": matched_count,
            "agreement_precision": round(
                agreement_precision,
                4
            ),
            "agreement_recall": round(
                agreement_recall,
                4
            ),
            "agreement_f1": round(
                agreement_f1,
                4
            ),
            "mean_matched_text_similarity": round(
                mean_similarity,
                4
            ),
            "owner_agreement": (
                round(
                    owner_agreement,
                    4
                )
                if owner_agreement
                is not None
                else None
            ),
            "deadline_agreement": (
                round(
                    deadline_agreement,
                    4
                )
                if deadline_agreement
                is not None
                else None
            ),
            "similarity_threshold": (
                similarity_threshold
            )
        })


    agreement_df = pd.DataFrame(
        results
    )

    return agreement_df


print(
    "Formal inter-annotator agreement calculator created successfully."
)

print("\nAgreement measures prepared:")
print("- Number of items identified by A1")
print("- Number of items identified by A2")
print("- One-to-one matched items")
print("- Agreement precision")
print("- Agreement recall")
print("- Agreement F1")
print("- Mean matched-text similarity")
print("- Owner agreement")
print("- Deadline agreement")

print("\nDefault matching threshold:")
print("70/100 token-set similarity")

print(
    "\nIMPORTANT: No agreement score has been calculated yet."
)

print(
    "Real completed A1 and A2 annotations are required before "
    "this function can be executed."
)

print(
    "\nThis free-text extraction agreement should be reported "
    "as pairwise annotation agreement, not mislabelled as Cohen's kappa."
)

Formal inter-annotator agreement calculator created successfully.

Agreement measures prepared:
- Number of items identified by A1
- Number of items identified by A2
- One-to-one matched items
- Agreement precision
- Agreement recall
- Agreement F1
- Mean matched-text similarity
- Owner agreement
- Deadline agreement

Default matching threshold:
70/100 token-set similarity

IMPORTANT: No agreement score has been calculated yet.
Real completed A1 and A2 annotations are required before this function can be executed.

This free-text extraction agreement should be reported as pairwise annotation agreement, not mislabelled as Cohen's kappa.

In [65]:
# ============================================================
# CREATE M01 HUMAN-CONSENSUS GOLD STANDARD
# Controlled case-study evaluation
# ============================================================

import pandas as pd
from pathlib import Path


gold_standard_items = [

    # ---------------- DECISIONS ----------------

    {
        "meeting_id": "M01",
        "item_type": "decision",
        "item_text": (
            "Use the term 'employee participation' consistently "
            "throughout the report."
        ),
        "owner": "",
        "deadline": "",
        "evidence_quote": (
            "Sarah: Agreed. Let’s keep 'employee participation' "
            "throughout the report."
        )
    },

    {
        "meeting_id": "M01",
        "item_type": "decision",
        "item_text": (
            "Flag incomplete responses and decide later whether "
            "to exclude them or treat missing values differently."
        ),
        "owner": "",
        "deadline": "",
        "evidence_quote": (
            "Sarah: For now, just flag them. Once we have the "
            "complete dataset, we can decide whether to exclude "
            "those responses or treat the missing values differently."
        )
    },

    {
        "meeting_id": "M01",
        "item_type": "decision",
        "item_text": (
            "Wait until tomorrow afternoon for the remaining "
            "department response; if unavailable, proceed with "
            "available data and document the limitation."
        ),
        "owner": "",
        "deadline": "",
        "evidence_quote": (
            "Sarah: Let’s wait until tomorrow. If they still "
            "haven’t responded by the afternoon, we’ll proceed "
            "with what we have and document that limitation."
        )
    },


    # ---------------- ACTION ITEMS ----------------

    {
        "meeting_id": "M01",
        "item_type": "action_item",
        "item_text": (
            "Send another reminder to the remaining department "
            "if no response is received."
        ),
        "owner": "James",
        "deadline": "Tomorrow morning",
        "evidence_quote": (
            "Sarah: Maybe give them until tomorrow morning, "
            "and if there’s still no response, send another reminder."
        )
    },

    {
        "meeting_id": "M01",
        "item_type": "action_item",
        "item_text": (
            "Continue cleaning and analysing existing data "
            "and flag incomplete responses."
        ),
        "owner": "Aisha",
        "deadline": "",
        "evidence_quote": (
            "Sarah: Aisha will continue cleaning and analyzing "
            "the existing data, but she’ll flag the incomplete "
            "responses for now."
        )
    },

    {
        "meeting_id": "M01",
        "item_type": "action_item",
        "item_text": (
            "Continue working on the report and ensure "
            "employee participation terminology is consistent."
        ),
        "owner": "Michael",
        "deadline": "",
        "evidence_quote": (
            "Sarah: Michael will continue working on the report "
            "and make sure we consistently use the term "
            "'employee participation'."
        )
    },

    {
        "meeting_id": "M01",
        "item_type": "action_item",
        "item_text": (
            "Send an updated draft of the report."
        ),
        "owner": "Michael",
        "deadline": "Tomorrow afternoon",
        "evidence_quote": (
            "Michael: I should be able to send you an updated "
            "draft tomorrow afternoon."
        )
    },

    {
        "meeting_id": "M01",
        "item_type": "action_item",
        "item_text": (
            "Review the updated report version."
        ),
        "owner": "Sarah",
        "deadline": "Tomorrow evening",
        "evidence_quote": (
            "Sarah: I’ll also review the report tomorrow evening "
            "once Michael sends the updated version."
        )
    }
]


gold_df = pd.DataFrame(
    gold_standard_items
)


gold_file = (
    DIRS["gold_standard"] /
    "M01_consensus_gold_standard.csv"
)


gold_df.to_csv(
    gold_file,
    index=False
)


print(
    "M01 consensus gold standard created successfully."
)

print("\nGold-standard items:")
print(
    len(gold_df)
)

print("\nDecisions:")
print(
    len(
        gold_df[
            gold_df["item_type"]=="decision"
        ]
    )
)

print("\nAction items:")
print(
    len(
        gold_df[
            gold_df["item_type"]=="action_item"
        ]
    )
)

print("\nSaved file:")
print(gold_file)


print(
    "\nIMPORTANT LIMITATION:"
)

print(
    "This is a controlled single-meeting gold-standard "
    "annotation created for prototype evaluation."
)

print(
    "Large-scale multi-annotator validation remains future work."
)

KeyError: 'gold_standard'

In [66]:
# ============================================================
# ADD GOLD STANDARD DIRECTORY
# ============================================================

from pathlib import Path

DIRS["gold_standard"] = (
    PROJECT_ROOT /
    "gold_standard"
)

DIRS["gold_standard"].mkdir(
    parents=True,
    exist_ok=True
)

print("Gold-standard directory added successfully.")
print(DIRS["gold_standard"])
print("Exists:", DIRS["gold_standard"].exists())

Gold-standard directory added successfully.
/content/AI_Meeting_Intelligence_Evaluation/gold_standard
Exists: True

In [68]:
# ============================================================
# CREATE M01 HUMAN-CONSENSUS GOLD STANDARD
# Controlled case-study evaluation
# ============================================================

import pandas as pd
from pathlib import Path


gold_standard_items = [

    # ---------------- DECISIONS ----------------

    {
        "meeting_id": "M01",
        "item_type": "decision",
        "item_text": (
            "Use the term 'employee participation' consistently "
            "throughout the report."
        ),
        "owner": "",
        "deadline": "",
        "evidence_quote": (
            "Sarah: Agreed. Let’s keep 'employee participation' "
            "throughout the report."
        )
    },

    {
        "meeting_id": "M01",
        "item_type": "decision",
        "item_text": (
            "Flag incomplete responses and decide later whether "
            "to exclude them or treat missing values differently."
        ),
        "owner": "",
        "deadline": "",
        "evidence_quote": (
            "Sarah: For now, just flag them. Once we have the "
            "complete dataset, we can decide whether to exclude "
            "those responses or treat the missing values differently."
        )
    },

    {
        "meeting_id": "M01",
        "item_type": "decision",
        "item_text": (
            "Wait until tomorrow afternoon for the remaining "
            "department response; if unavailable, proceed with "
            "available data and document the limitation."
        ),
        "owner": "",
        "deadline": "",
        "evidence_quote": (
            "Sarah: Let’s wait until tomorrow. If they still "
            "haven’t responded by the afternoon, we’ll proceed "
            "with what we have and document that limitation."
        )
    },


    # ---------------- ACTION ITEMS ----------------

    {
        "meeting_id": "M01",
        "item_type": "action_item",
        "item_text": (
            "Send another reminder to the remaining department "
            "if no response is received."
        ),
        "owner": "James",
        "deadline": "Tomorrow morning",
        "evidence_quote": (
            "Sarah: Maybe give them until tomorrow morning, "
            "and if there’s still no response, send another reminder."
        )
    },

    {
        "meeting_id": "M01",
        "item_type": "action_item",
        "item_text": (
            "Continue cleaning and analysing existing data "
            "and flag incomplete responses."
        ),
        "owner": "Aisha",
        "deadline": "",
        "evidence_quote": (
            "Sarah: Aisha will continue cleaning and analyzing "
            "the existing data, but she’ll flag the incomplete "
            "responses for now."
        )
    },

    {
        "meeting_id": "M01",
        "item_type": "action_item",
        "item_text": (
            "Continue working on the report and ensure "
            "employee participation terminology is consistent."
        ),
        "owner": "Michael",
        "deadline": "",
        "evidence_quote": (
            "Sarah: Michael will continue working on the report "
            "and make sure we consistently use the term "
            "'employee participation'."
        )
    },

    {
        "meeting_id": "M01",
        "item_type": "action_item",
        "item_text": (
            "Send an updated draft of the report."
        ),
        "owner": "Michael",
        "deadline": "Tomorrow afternoon",
        "evidence_quote": (
            "Michael: I should be able to send you an updated "
            "draft tomorrow afternoon."
        )
    },

    {
        "meeting_id": "M01",
        "item_type": "action_item",
        "item_text": (
            "Review the updated report version."
        ),
        "owner": "Sarah",
        "deadline": "Tomorrow evening",
        "evidence_quote": (
            "Sarah: I’ll also review the report tomorrow evening "
            "once Michael sends the updated version."
        )
    }
]


gold_df = pd.DataFrame(
    gold_standard_items
)


gold_file = (
    DIRS["gold_standard"] /
    "M01_consensus_gold_standard.csv"
)


gold_df.to_csv(
    gold_file,
    index=False
)


print(
    "M01 consensus gold standard created successfully."
)

print("\nGold-standard items:")
print(
    len(gold_df)
)

print("\nDecisions:")
print(
    len(
        gold_df[
            gold_df["item_type"]=="decision"
        ]
    )
)

print("\nAction items:")
print(
    len(
        gold_df[
            gold_df["item_type"]=="action_item"
        ]
    )
)

print("\nSaved file:")
print(gold_file)


print(
    "\nIMPORTANT LIMITATION:"
)

print(
    "This is a controlled single-meeting gold-standard "
    "annotation created for prototype evaluation."
)

print(
    "Large-scale multi-annotator validation remains future work."
)

M01 consensus gold standard created successfully.

Gold-standard items:
8

Decisions:
3

Action items:
5

Saved file:
/content/AI_Meeting_Intelligence_Evaluation/gold_standard/M01_consensus_gold_standard.csv

IMPORTANT LIMITATION:
This is a controlled single-meeting gold-standard annotation created for prototype evaluation.
Large-scale multi-annotator validation remains future work.

In [69]:
# ============================================================
# M01 EXTRACTION PERFORMANCE EVALUATION
# Generic vs Structured Prompt
# ============================================================

import json
import pandas as pd
from rapidfuzz.fuzz import token_set_ratio


# ------------------------------------------------------------
# Load gold standard
# ------------------------------------------------------------

gold_file = (
    DIRS["gold_standard"] /
    "M01_consensus_gold_standard.csv"
)

gold_df = pd.read_csv(
    gold_file
)


# ------------------------------------------------------------
# Load Gemini outputs
# ------------------------------------------------------------

def load_output(prompt_type):

    output_file = (
        DIRS[f"{prompt_type}_outputs"] /
        f"M01_{prompt_type}_run1.json"
    )

    with open(
        output_file,
        "r",
        encoding="utf-8"
    ) as f:
        return json.load(f)



# ------------------------------------------------------------
# Extract AI items
# ------------------------------------------------------------

def extract_ai_items(output):

    items = []

    for item in output.get(
        "decisions",
        []
    ):

        items.append({
            "item_type": "decision",
            "item_text": item["decision"],
            "owner": "",
            "deadline": ""
        })


    for item in output.get(
        "action_items",
        []
    ):

        items.append({
            "item_type": "action_item",
            "item_text": item["action"],
            "owner": item.get(
                "owner",
                ""
            ),
            "deadline": item.get(
                "deadline",
                ""
            )
        })

    return pd.DataFrame(items)



# ------------------------------------------------------------
# Matching function
# ------------------------------------------------------------

def evaluate_extraction(
    ai_df,
    gold_df,
    threshold=70
):

    matched_gold = set()
    matched_ai = set()

    matches = []


    for ai_index, ai_row in ai_df.iterrows():

        best_match = None
        best_score = 0


        for gold_index, gold_row in gold_df.iterrows():

            if gold_index in matched_gold:
                continue


            if (
                ai_row["item_type"]
                !=
                gold_row["item_type"]
            ):
                continue


            score = token_set_ratio(
                str(ai_row["item_text"]),
                str(gold_row["item_text"])
            )


            if score > best_score:

                best_score = score
                best_match = gold_index


        if (
            best_match is not None
            and best_score >= threshold
        ):

            matched_ai.add(ai_index)
            matched_gold.add(best_match)

            matches.append({
                "ai_index": ai_index,
                "gold_index": best_match,
                "similarity": best_score
            })


    TP = len(matches)

    FP = len(ai_df) - TP

    FN = len(gold_df) - len(matched_gold)


    precision = (
        TP / (TP + FP)
        if (TP + FP) > 0
        else 0
    )

    recall = (
        TP / (TP + FN)
        if (TP + FN) > 0
        else 0
    )

    f1 = (
        2 * precision * recall /
        (precision + recall)
        if precision + recall > 0
        else 0
    )


    hallucination_rate = (
        FP / len(ai_df)
        if len(ai_df) > 0
        else 0
    )


    # ---------------------------------------------
    # Owner and deadline accuracy
    # ---------------------------------------------

    owner_correct = []
    deadline_correct = []


    for match in matches:

        ai_item = ai_df.iloc[
            match["ai_index"]
        ]

        gold_item = gold_df.iloc[
            match["gold_index"]
        ]


        if gold_item["item_type"] == "action_item":

            owner_correct.append(
                int(
                    str(ai_item["owner"]).lower().strip()
                    ==
                    str(gold_item["owner"]).lower().strip()
                )
            )

            deadline_correct.append(
                int(
                    str(ai_item["deadline"]).lower().strip()
                    ==
                    str(gold_item["deadline"]).lower().strip()
                )
            )


    return {
        "TP": TP,
        "FP": FP,
        "FN": FN,
        "precision": round(precision,4),
        "recall": round(recall,4),
        "f1_score": round(f1,4),
        "hallucination_rate": round(
            hallucination_rate,
            4
        ),
        "owner_accuracy": round(
            sum(owner_correct)/len(owner_correct),
            4
        ) if owner_correct else None,
        "deadline_accuracy": round(
            sum(deadline_correct)/len(deadline_correct),
            4
        ) if deadline_correct else None
    }



# ------------------------------------------------------------
# Run evaluation
# ------------------------------------------------------------

results = []


for prompt_type in [
    "generic",
    "structured"
]:

    output = load_output(
        prompt_type
    )

    ai_df = extract_ai_items(
        output
    )

    metrics = evaluate_extraction(
        ai_df,
        gold_df
    )

    metrics["prompt_type"] = prompt_type

    results.append(
        metrics
    )


results_df = pd.DataFrame(
    results
)


# Arrange columns

results_df = results_df[
    [
        "prompt_type",
        "TP",
        "FP",
        "FN",
        "precision",
        "recall",
        "f1_score",
        "hallucination_rate",
        "owner_accuracy",
        "deadline_accuracy"
    ]
]


print(
    "M01 extraction evaluation completed successfully."
)

display(
    results_df
)


results_file = (
    DIRS["results"] /
    "M01_generic_vs_structured_extraction_metrics.csv"
)


results_df.to_csv(
    results_file,
    index=False
)


print("\nSaved file:")
print(results_file)

print(
    "\nInterpretation:"
)

print(
    "Metrics represent agreement with the M01 controlled gold standard."
)

print(
    "This is a prototype case-study evaluation and should be reported with limitations."
)

M01 extraction evaluation completed successfully.

,prompt_type,TP,FP,FN,precision,recall,f1_score,hallucination_rate,owner_accuracy,deadline_accuracy
0,generic,7,1,1,0.875,0.875,0.875,0.125,1.0,1.0
1,structured,8,0,0,1.000,1.000,1.000,0.000,1.0,0.8

KeyError: 'results'

In [70]:
# ============================================================
# ADD RESULTS DIRECTORY
# ============================================================

from pathlib import Path

DIRS["results"] = (
    PROJECT_ROOT /
    "results"
)

DIRS["results"].mkdir(
    parents=True,
    exist_ok=True
)

print("Results directory added successfully.")
print(DIRS["results"])
print("Exists:", DIRS["results"].exists())

Results directory added successfully.
/content/AI_Meeting_Intelligence_Evaluation/results
Exists: True

In [71]:
results_file = (
    DIRS["results"] /
    "M01_generic_vs_structured_extraction_metrics.csv"
)

results_df.to_csv(
    results_file,
    index=False
)

print("Saved file:")
print(results_file)

Saved file:
/content/AI_Meeting_Intelligence_Evaluation/results/M01_generic_vs_structured_extraction_metrics.csv

In [73]:
# ============================================================
# CREATE AIMIS GITHUB READY FILES (FIXED VERSION)
# ============================================================

from pathlib import Path
import shutil
import zipfile
from google.colab import files


project = Path("/content/AIMIS_GitHub_Repository")

results = project / "results"

project.mkdir(exist_ok=True)
results.mkdir(exist_ok=True)


# ============================================================
# requirements.txt
# ============================================================

requirements = """
numpy
pandas
torch
openai-whisper
google-genai
pydantic
rapidfuzz
openpyxl
scikit-learn
matplotlib
tqdm
streamlit
"""

(project / "requirements.txt").write_text(
    requirements.strip()
)


# ============================================================
# README.md
# ============================================================

readme = """
# AI Meeting Intelligence System (AIMIS)

## Overview

AIMIS is an AI-based meeting analysis system that converts meeting
transcripts into structured intelligence.

## Features

- Automatic speech transcription
- Meeting summarization
- Decision extraction
- Action-item extraction
- Evidence-based evaluation

## Technologies

Speech Recognition:
OpenAI Whisper small.en

Language Model:
Google Gemini Flash

## Evaluation Metrics

- Word Error Rate (WER)
- Character Error Rate (CER)
- Precision
- Recall
- F1-score
- Hallucination rate
- Owner accuracy
- Deadline accuracy

## Repository Contents

AIMIS/

    app.py
    README.md
    requirements.txt

    results/
        M01_generic_vs_structured_extraction_metrics.csv
        asr_results.csv
        prompt_repeatability_summary.csv


## Installation

Install dependencies:

pip install -r requirements.txt


## Run Application

streamlit run app.py


## Research Purpose

This repository contains the experimental implementation
and evaluation results of an AI Meeting Intelligence System.
"""

(project / "README.md").write_text(
    readme.strip(),
    encoding="utf-8"
)


# ============================================================
# app.py
# ============================================================

app = """
import streamlit as st
import pandas as pd
from pathlib import Path


st.title("AI Meeting Intelligence System")


st.write(
    "Experimental dashboard for AIMIS evaluation results."
)


folder = Path("results")


files = [
    "M01_generic_vs_structured_extraction_metrics.csv",
    "asr_results.csv",
    "prompt_repeatability_summary.csv"
]


for f in files:

    path = folder / f

    if path.exists():

        st.subheader(f)

        df = pd.read_csv(path)

        st.dataframe(df)

    else:

        st.warning(f + " not found")
"""

(project / "app.py").write_text(
    app.strip(),
    encoding="utf-8"
)


# ============================================================
# COPY RESULT FILES
# ============================================================

files_to_copy = {

"M01_generic_vs_structured_extraction_metrics.csv":
"/content/AI_Meeting_Intelligence_Evaluation/results/M01_generic_vs_structured_extraction_metrics.csv",

"asr_results.csv":
"/content/AI_Meeting_Intelligence_Evaluation/evaluation/asr/asr_results.csv",

"prompt_repeatability_summary.csv":
"/content/AI_Meeting_Intelligence_Evaluation/outputs/repeatability/M01_prompt_repeatability_summary.csv"

}


for name, source in files_to_copy.items():

    source = Path(source)

    if source.exists():

        shutil.copy(
            source,
            results / name
        )

        print("Copied:", name)

    else:

        print("Missing:", name)


# ============================================================
# CREATE ZIP
# ============================================================

zip_path = Path(
    "/content/AIMIS_GitHub_Repository.zip"
)


with zipfile.ZipFile(
    zip_path,
    "w",
    zipfile.ZIP_DEFLATED
) as z:

    for file in project.rglob("*"):

        if file.is_file():

            z.write(
                file,
                file.relative_to(project)
            )


print("\n================================")
print("AIMIS GitHub package created")
print("================================")

print(zip_path)


files.download(
    str(zip_path)
)

Copied: M01_generic_vs_structured_extraction_metrics.csv
Copied: asr_results.csv
Copied: prompt_repeatability_summary.csv

================================
AIMIS GitHub package created
================================
/content/AIMIS_GitHub_Repository.zip